// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package main

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that cronRootSenderMock does implement cronRootSender.
// If this is not the case, regenerate this file with mockery.
var _ cronRootSender = &cronRootSenderMock{}

// cronRootSenderMock is a mock implementation of cronRootSender.
//
//	func TestSomethingThatUsescronRootSender(t *testing.T) {
//
//		// make and configure a mocked cronRootSender
//		mockedcronRootSender := &cronRootSenderMock{
//			SendCronjobRootFunc: func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
//				panic("mock out the SendCronjobRoot method")
//			},
//		}
//
//		// use mockedcronRootSender in code that requires cronRootSender
//		// and then make assertions.
//
//	}
type cronRootSenderMock struct {
	// SendCronjobRootFunc mocks the SendCronjobRoot method.
	SendCronjobRootFunc func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendCronjobRoot holds details about calls to the SendCronjobRoot method.
		SendCronjobRoot []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// OutboundMessage is the outboundMessage argument value.
			OutboundMessage *protocol.OutboundMessage
		}
	}
	lockSendCronjobRoot sync.RWMutex
}

// SendCronjobRoot calls SendCronjobRootFunc.
func (mock *cronRootSenderMock) SendCronjobRoot(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
	if mock.SendCronjobRootFunc == nil {
		panic("cronRootSenderMock.SendCronjobRootFunc: method is nil but cronRootSender.SendCronjobRoot was just called")
	}
	callInfo := struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}{
		Context1:        context1,
		OutboundMessage: outboundMessage,
	}
	mock.lockSendCronjobRoot.Lock()
	mock.calls.SendCronjobRoot = append(mock.calls.SendCronjobRoot, callInfo)
	mock.lockSendCronjobRoot.Unlock()
	return mock.SendCronjobRootFunc(context1, outboundMessage)
}

// SendCronjobRootCalls gets all the calls that were made to SendCronjobRoot.
// Check the length with:
//
//	len(mockedcronRootSender.SendCronjobRootCalls())
func (mock *cronRootSenderMock) SendCronjobRootCalls() []struct {
	Context1        context.Context
	OutboundMessage *protocol.OutboundMessage
} {
	var calls []struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}
	mock.lockSendCronjobRoot.RLock()
	calls = mock.calls.SendCronjobRoot
	mock.lockSendCronjobRoot.RUnlock()
	return calls
}
