// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package main

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that SlackFrontendMock does implement backend.SlackFrontend.
// If this is not the case, regenerate this file with mockery.
var _ backend.SlackFrontend = &SlackFrontendMock{}

// SlackFrontendMock is a mock implementation of backend.SlackFrontend.
//
//	func TestSomethingThatUsesSlackFrontend(t *testing.T) {
//
//		// make and configure a mocked backend.SlackFrontend
//		mockedSlackFrontend := &SlackFrontendMock{
//			ActivateEnqueueFunc: func(context1 context.Context, threadQueueItem *protocol.ThreadQueueItem, inboundMessage *protocol.InboundMessage) error {
//				panic("mock out the ActivateEnqueue method")
//			},
//			AskUserQuestionFunc: func(context1 context.Context, askUserQuestionRequest *protocol.AskUserQuestionRequest) (protocol.AskUserQuestionAnswer, error) {
//				panic("mock out the AskUserQuestion method")
//			},
//			DiscardPendingSteersFunc: func(context1 context.Context, pendingSteers []protocol.PendingSteer)  {
//				panic("mock out the DiscardPendingSteers method")
//			},
//			DrainSteersFunc: func(context1 context.Context, s string) []string {
//				panic("mock out the DrainSteers method")
//			},
//			RestorePendingSteersFunc: func(s string, pendingSteers []protocol.PendingSteer)  {
//				panic("mock out the RestorePendingSteers method")
//			},
//			SetPendingSteersSinkFunc: func(pendingSteersSink protocol.PendingSteersSink)  {
//				panic("mock out the SetPendingSteersSink method")
//			},
//			StartFunc: func(context1 context.Context) error {
//				panic("mock out the Start method")
//			},
//			StartNewThreadRootFunc: func(context1 context.Context, startNewThreadRequest *protocol.StartNewThreadRequest) (protocol.StartNewThreadRootResult, error) {
//				panic("mock out the StartNewThreadRoot method")
//			},
//			StopFunc: func(context1 context.Context) error {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedSlackFrontend in code that requires backend.SlackFrontend
//		// and then make assertions.
//
//	}
type SlackFrontendMock struct {

	// ActivateEnqueueFunc mocks the ActivateEnqueue method.
	ActivateEnqueueFunc func(context1 context.Context, threadQueueItem *protocol.ThreadQueueItem, inboundMessage *protocol.InboundMessage) error

	// AskUserQuestionFunc mocks the AskUserQuestion method.
	AskUserQuestionFunc func(context1 context.Context, askUserQuestionRequest *protocol.AskUserQuestionRequest) (protocol.AskUserQuestionAnswer, error)

	// DiscardPendingSteersFunc mocks the DiscardPendingSteers method.
	DiscardPendingSteersFunc func(context1 context.Context, pendingSteers []protocol.PendingSteer)

	// DrainSteersFunc mocks the DrainSteers method.
	DrainSteersFunc func(context1 context.Context, s string) []string

	// RestorePendingSteersFunc mocks the RestorePendingSteers method.
	RestorePendingSteersFunc func(s string, pendingSteers []protocol.PendingSteer)

	// SetPendingSteersSinkFunc mocks the SetPendingSteersSink method.
	SetPendingSteersSinkFunc func(pendingSteersSink protocol.PendingSteersSink)

	// StartFunc mocks the Start method.
	StartFunc func(context1 context.Context) error

	// StartNewThreadRootFunc mocks the StartNewThreadRoot method.
	StartNewThreadRootFunc func(context1 context.Context, startNewThreadRequest *protocol.StartNewThreadRequest) (protocol.StartNewThreadRootResult, error)

	// StopFunc mocks the Stop method.
	StopFunc func(context1 context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// ActivateEnqueue holds details about calls to the ActivateEnqueue method.
		ActivateEnqueue []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ThreadQueueItem is the threadQueueItem argument value.
			ThreadQueueItem *protocol.ThreadQueueItem
			// InboundMessage is the inboundMessage argument value.
			InboundMessage *protocol.InboundMessage
		}
		// AskUserQuestion holds details about calls to the AskUserQuestion method.
		AskUserQuestion []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// AskUserQuestionRequest is the askUserQuestionRequest argument value.
			AskUserQuestionRequest *protocol.AskUserQuestionRequest
		}
		// DiscardPendingSteers holds details about calls to the DiscardPendingSteers method.
		DiscardPendingSteers []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// PendingSteers is the pendingSteers argument value.
			PendingSteers []protocol.PendingSteer
		}
		// DrainSteers holds details about calls to the DrainSteers method.
		DrainSteers []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// RestorePendingSteers holds details about calls to the RestorePendingSteers method.
		RestorePendingSteers []struct {
			// S is the s argument value.
			S string
			// PendingSteers is the pendingSteers argument value.
			PendingSteers []protocol.PendingSteer
		}
		// SetPendingSteersSink holds details about calls to the SetPendingSteersSink method.
		SetPendingSteersSink []struct {
			// PendingSteersSink is the pendingSteersSink argument value.
			PendingSteersSink protocol.PendingSteersSink
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// StartNewThreadRoot holds details about calls to the StartNewThreadRoot method.
		StartNewThreadRoot []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// StartNewThreadRequest is the startNewThreadRequest argument value.
			StartNewThreadRequest *protocol.StartNewThreadRequest
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
	}
	lockActivateEnqueue      sync.RWMutex
	lockAskUserQuestion      sync.RWMutex
	lockDiscardPendingSteers sync.RWMutex
	lockDrainSteers          sync.RWMutex
	lockRestorePendingSteers sync.RWMutex
	lockSetPendingSteersSink sync.RWMutex
	lockStart                sync.RWMutex
	lockStartNewThreadRoot   sync.RWMutex
	lockStop                 sync.RWMutex
}

// ActivateEnqueue calls ActivateEnqueueFunc.
func (mock *SlackFrontendMock) ActivateEnqueue(context1 context.Context, threadQueueItem *protocol.ThreadQueueItem, inboundMessage *protocol.InboundMessage) error {
	if mock.ActivateEnqueueFunc == nil {
		panic("SlackFrontendMock.ActivateEnqueueFunc: method is nil but SlackFrontend.ActivateEnqueue was just called")
	}
	callInfo := struct {
		Context1        context.Context
		ThreadQueueItem *protocol.ThreadQueueItem
		InboundMessage  *protocol.InboundMessage
	}{
		Context1:        context1,
		ThreadQueueItem: threadQueueItem,
		InboundMessage:  inboundMessage,
	}
	mock.lockActivateEnqueue.Lock()
	mock.calls.ActivateEnqueue = append(mock.calls.ActivateEnqueue, callInfo)
	mock.lockActivateEnqueue.Unlock()
	return mock.ActivateEnqueueFunc(context1, threadQueueItem, inboundMessage)
}

// ActivateEnqueueCalls gets all the calls that were made to ActivateEnqueue.
// Check the length with:
//
//	len(mockedSlackFrontend.ActivateEnqueueCalls())
func (mock *SlackFrontendMock) ActivateEnqueueCalls() []struct {
	Context1        context.Context
	ThreadQueueItem *protocol.ThreadQueueItem
	InboundMessage  *protocol.InboundMessage
} {
	var calls []struct {
		Context1        context.Context
		ThreadQueueItem *protocol.ThreadQueueItem
		InboundMessage  *protocol.InboundMessage
	}
	mock.lockActivateEnqueue.RLock()
	calls = mock.calls.ActivateEnqueue
	mock.lockActivateEnqueue.RUnlock()
	return calls
}

// AskUserQuestion calls AskUserQuestionFunc.
func (mock *SlackFrontendMock) AskUserQuestion(context1 context.Context, askUserQuestionRequest *protocol.AskUserQuestionRequest) (protocol.AskUserQuestionAnswer, error) {
	if mock.AskUserQuestionFunc == nil {
		panic("SlackFrontendMock.AskUserQuestionFunc: method is nil but SlackFrontend.AskUserQuestion was just called")
	}
	callInfo := struct {
		Context1               context.Context
		AskUserQuestionRequest *protocol.AskUserQuestionRequest
	}{
		Context1:               context1,
		AskUserQuestionRequest: askUserQuestionRequest,
	}
	mock.lockAskUserQuestion.Lock()
	mock.calls.AskUserQuestion = append(mock.calls.AskUserQuestion, callInfo)
	mock.lockAskUserQuestion.Unlock()
	return mock.AskUserQuestionFunc(context1, askUserQuestionRequest)
}

// AskUserQuestionCalls gets all the calls that were made to AskUserQuestion.
// Check the length with:
//
//	len(mockedSlackFrontend.AskUserQuestionCalls())
func (mock *SlackFrontendMock) AskUserQuestionCalls() []struct {
	Context1               context.Context
	AskUserQuestionRequest *protocol.AskUserQuestionRequest
} {
	var calls []struct {
		Context1               context.Context
		AskUserQuestionRequest *protocol.AskUserQuestionRequest
	}
	mock.lockAskUserQuestion.RLock()
	calls = mock.calls.AskUserQuestion
	mock.lockAskUserQuestion.RUnlock()
	return calls
}

// DiscardPendingSteers calls DiscardPendingSteersFunc.
func (mock *SlackFrontendMock) DiscardPendingSteers(context1 context.Context, pendingSteers []protocol.PendingSteer) {
	if mock.DiscardPendingSteersFunc == nil {
		panic("SlackFrontendMock.DiscardPendingSteersFunc: method is nil but SlackFrontend.DiscardPendingSteers was just called")
	}
	callInfo := struct {
		Context1      context.Context
		PendingSteers []protocol.PendingSteer
	}{
		Context1:      context1,
		PendingSteers: pendingSteers,
	}
	mock.lockDiscardPendingSteers.Lock()
	mock.calls.DiscardPendingSteers = append(mock.calls.DiscardPendingSteers, callInfo)
	mock.lockDiscardPendingSteers.Unlock()
	mock.DiscardPendingSteersFunc(context1, pendingSteers)
}

// DiscardPendingSteersCalls gets all the calls that were made to DiscardPendingSteers.
// Check the length with:
//
//	len(mockedSlackFrontend.DiscardPendingSteersCalls())
func (mock *SlackFrontendMock) DiscardPendingSteersCalls() []struct {
	Context1      context.Context
	PendingSteers []protocol.PendingSteer
} {
	var calls []struct {
		Context1      context.Context
		PendingSteers []protocol.PendingSteer
	}
	mock.lockDiscardPendingSteers.RLock()
	calls = mock.calls.DiscardPendingSteers
	mock.lockDiscardPendingSteers.RUnlock()
	return calls
}

// DrainSteers calls DrainSteersFunc.
func (mock *SlackFrontendMock) DrainSteers(context1 context.Context, s string) []string {
	if mock.DrainSteersFunc == nil {
		panic("SlackFrontendMock.DrainSteersFunc: method is nil but SlackFrontend.DrainSteers was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockDrainSteers.Lock()
	mock.calls.DrainSteers = append(mock.calls.DrainSteers, callInfo)
	mock.lockDrainSteers.Unlock()
	return mock.DrainSteersFunc(context1, s)
}

// DrainSteersCalls gets all the calls that were made to DrainSteers.
// Check the length with:
//
//	len(mockedSlackFrontend.DrainSteersCalls())
func (mock *SlackFrontendMock) DrainSteersCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockDrainSteers.RLock()
	calls = mock.calls.DrainSteers
	mock.lockDrainSteers.RUnlock()
	return calls
}

// RestorePendingSteers calls RestorePendingSteersFunc.
func (mock *SlackFrontendMock) RestorePendingSteers(s string, pendingSteers []protocol.PendingSteer) {
	if mock.RestorePendingSteersFunc == nil {
		panic("SlackFrontendMock.RestorePendingSteersFunc: method is nil but SlackFrontend.RestorePendingSteers was just called")
	}
	callInfo := struct {
		S             string
		PendingSteers []protocol.PendingSteer
	}{
		S:             s,
		PendingSteers: pendingSteers,
	}
	mock.lockRestorePendingSteers.Lock()
	mock.calls.RestorePendingSteers = append(mock.calls.RestorePendingSteers, callInfo)
	mock.lockRestorePendingSteers.Unlock()
	mock.RestorePendingSteersFunc(s, pendingSteers)
}

// RestorePendingSteersCalls gets all the calls that were made to RestorePendingSteers.
// Check the length with:
//
//	len(mockedSlackFrontend.RestorePendingSteersCalls())
func (mock *SlackFrontendMock) RestorePendingSteersCalls() []struct {
	S             string
	PendingSteers []protocol.PendingSteer
} {
	var calls []struct {
		S             string
		PendingSteers []protocol.PendingSteer
	}
	mock.lockRestorePendingSteers.RLock()
	calls = mock.calls.RestorePendingSteers
	mock.lockRestorePendingSteers.RUnlock()
	return calls
}

// SetPendingSteersSink calls SetPendingSteersSinkFunc.
func (mock *SlackFrontendMock) SetPendingSteersSink(pendingSteersSink protocol.PendingSteersSink) {
	if mock.SetPendingSteersSinkFunc == nil {
		panic("SlackFrontendMock.SetPendingSteersSinkFunc: method is nil but SlackFrontend.SetPendingSteersSink was just called")
	}
	callInfo := struct {
		PendingSteersSink protocol.PendingSteersSink
	}{
		PendingSteersSink: pendingSteersSink,
	}
	mock.lockSetPendingSteersSink.Lock()
	mock.calls.SetPendingSteersSink = append(mock.calls.SetPendingSteersSink, callInfo)
	mock.lockSetPendingSteersSink.Unlock()
	mock.SetPendingSteersSinkFunc(pendingSteersSink)
}

// SetPendingSteersSinkCalls gets all the calls that were made to SetPendingSteersSink.
// Check the length with:
//
//	len(mockedSlackFrontend.SetPendingSteersSinkCalls())
func (mock *SlackFrontendMock) SetPendingSteersSinkCalls() []struct {
	PendingSteersSink protocol.PendingSteersSink
} {
	var calls []struct {
		PendingSteersSink protocol.PendingSteersSink
	}
	mock.lockSetPendingSteersSink.RLock()
	calls = mock.calls.SetPendingSteersSink
	mock.lockSetPendingSteersSink.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *SlackFrontendMock) Start(context1 context.Context) error {
	if mock.StartFunc == nil {
		panic("SlackFrontendMock.StartFunc: method is nil but SlackFrontend.Start was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(context1)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedSlackFrontend.StartCalls())
func (mock *SlackFrontendMock) StartCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// StartNewThreadRoot calls StartNewThreadRootFunc.
func (mock *SlackFrontendMock) StartNewThreadRoot(context1 context.Context, startNewThreadRequest *protocol.StartNewThreadRequest) (protocol.StartNewThreadRootResult, error) {
	if mock.StartNewThreadRootFunc == nil {
		panic("SlackFrontendMock.StartNewThreadRootFunc: method is nil but SlackFrontend.StartNewThreadRoot was just called")
	}
	callInfo := struct {
		Context1              context.Context
		StartNewThreadRequest *protocol.StartNewThreadRequest
	}{
		Context1:              context1,
		StartNewThreadRequest: startNewThreadRequest,
	}
	mock.lockStartNewThreadRoot.Lock()
	mock.calls.StartNewThreadRoot = append(mock.calls.StartNewThreadRoot, callInfo)
	mock.lockStartNewThreadRoot.Unlock()
	return mock.StartNewThreadRootFunc(context1, startNewThreadRequest)
}

// StartNewThreadRootCalls gets all the calls that were made to StartNewThreadRoot.
// Check the length with:
//
//	len(mockedSlackFrontend.StartNewThreadRootCalls())
func (mock *SlackFrontendMock) StartNewThreadRootCalls() []struct {
	Context1              context.Context
	StartNewThreadRequest *protocol.StartNewThreadRequest
} {
	var calls []struct {
		Context1              context.Context
		StartNewThreadRequest *protocol.StartNewThreadRequest
	}
	mock.lockStartNewThreadRoot.RLock()
	calls = mock.calls.StartNewThreadRoot
	mock.lockStartNewThreadRoot.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *SlackFrontendMock) Stop(context1 context.Context) error {
	if mock.StopFunc == nil {
		panic("SlackFrontendMock.StopFunc: method is nil but SlackFrontend.Stop was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(context1)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedSlackFrontend.StopCalls())
func (mock *SlackFrontendMock) StopCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
