// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package main

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that SlackFrontendMock does implement backend.SlackFrontend.
// If this is not the case, regenerate this file with mockery.
var _ backend.SlackFrontend = &SlackFrontendMock{}

// SlackFrontendMock is a mock implementation of backend.SlackFrontend.
//
//	func TestSomethingThatUsesSlackFrontend(t *testing.T) {
//
//		// make and configure a mocked backend.SlackFrontend
//		mockedSlackFrontend := &SlackFrontendMock{
//			EditCronjobRootFooterFunc: func(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error {
//				panic("mock out the EditCronjobRootFooter method")
//			},
//			SendCronjobRootFunc: func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
//				panic("mock out the SendCronjobRoot method")
//			},
//			SidebarChannelAgentChoicesFunc: func(context1 context.Context, s string) (string, []string, error) {
//				panic("mock out the SidebarChannelAgentChoices method")
//			},
//			SlackTagsMatchingFunc: func(context1 context.Context, s string) []string {
//				panic("mock out the SlackTagsMatching method")
//			},
//			StartFunc: func(context1 context.Context) error {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(context1 context.Context) error {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedSlackFrontend in code that requires backend.SlackFrontend
//		// and then make assertions.
//
//	}
type SlackFrontendMock struct {
	// EditCronjobRootFooterFunc mocks the EditCronjobRootFooter method.
	EditCronjobRootFooterFunc func(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error

	// SendCronjobRootFunc mocks the SendCronjobRoot method.
	SendCronjobRootFunc func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error)

	// SidebarChannelAgentChoicesFunc mocks the SidebarChannelAgentChoices method.
	SidebarChannelAgentChoicesFunc func(context1 context.Context, s string) (string, []string, error)

	// SlackTagsMatchingFunc mocks the SlackTagsMatching method.
	SlackTagsMatchingFunc func(context1 context.Context, s string) []string

	// StartFunc mocks the Start method.
	StartFunc func(context1 context.Context) error

	// StopFunc mocks the Stop method.
	StopFunc func(context1 context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// EditCronjobRootFooter holds details about calls to the EditCronjobRootFooter method.
		EditCronjobRootFooter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg *protocol.OutboundMessage
			// Root is the root argument value.
			Root protocol.TextConversationTarget
			// ConversationID is the conversationID argument value.
			ConversationID string
		}
		// SendCronjobRoot holds details about calls to the SendCronjobRoot method.
		SendCronjobRoot []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// OutboundMessage is the outboundMessage argument value.
			OutboundMessage *protocol.OutboundMessage
		}
		// SidebarChannelAgentChoices holds details about calls to the SidebarChannelAgentChoices method.
		SidebarChannelAgentChoices []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// SlackTagsMatching holds details about calls to the SlackTagsMatching method.
		SlackTagsMatching []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
	}
	lockEditCronjobRootFooter      sync.RWMutex
	lockSendCronjobRoot            sync.RWMutex
	lockSidebarChannelAgentChoices sync.RWMutex
	lockSlackTagsMatching          sync.RWMutex
	lockStart                      sync.RWMutex
	lockStop                       sync.RWMutex
}

// EditCronjobRootFooter calls EditCronjobRootFooterFunc.
func (mock *SlackFrontendMock) EditCronjobRootFooter(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error {
	if mock.EditCronjobRootFooterFunc == nil {
		panic("SlackFrontendMock.EditCronjobRootFooterFunc: method is nil but SlackFrontend.EditCronjobRootFooter was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Msg            *protocol.OutboundMessage
		Root           protocol.TextConversationTarget
		ConversationID string
	}{
		Ctx:            ctx,
		Msg:            msg,
		Root:           root,
		ConversationID: conversationID,
	}
	mock.lockEditCronjobRootFooter.Lock()
	mock.calls.EditCronjobRootFooter = append(mock.calls.EditCronjobRootFooter, callInfo)
	mock.lockEditCronjobRootFooter.Unlock()
	return mock.EditCronjobRootFooterFunc(ctx, msg, root, conversationID)
}

// EditCronjobRootFooterCalls gets all the calls that were made to EditCronjobRootFooter.
// Check the length with:
//
//	len(mockedSlackFrontend.EditCronjobRootFooterCalls())
func (mock *SlackFrontendMock) EditCronjobRootFooterCalls() []struct {
	Ctx            context.Context
	Msg            *protocol.OutboundMessage
	Root           protocol.TextConversationTarget
	ConversationID string
} {
	var calls []struct {
		Ctx            context.Context
		Msg            *protocol.OutboundMessage
		Root           protocol.TextConversationTarget
		ConversationID string
	}
	mock.lockEditCronjobRootFooter.RLock()
	calls = mock.calls.EditCronjobRootFooter
	mock.lockEditCronjobRootFooter.RUnlock()
	return calls
}

// SendCronjobRoot calls SendCronjobRootFunc.
func (mock *SlackFrontendMock) SendCronjobRoot(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
	if mock.SendCronjobRootFunc == nil {
		panic("SlackFrontendMock.SendCronjobRootFunc: method is nil but SlackFrontend.SendCronjobRoot was just called")
	}
	callInfo := struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}{
		Context1:        context1,
		OutboundMessage: outboundMessage,
	}
	mock.lockSendCronjobRoot.Lock()
	mock.calls.SendCronjobRoot = append(mock.calls.SendCronjobRoot, callInfo)
	mock.lockSendCronjobRoot.Unlock()
	return mock.SendCronjobRootFunc(context1, outboundMessage)
}

// SendCronjobRootCalls gets all the calls that were made to SendCronjobRoot.
// Check the length with:
//
//	len(mockedSlackFrontend.SendCronjobRootCalls())
func (mock *SlackFrontendMock) SendCronjobRootCalls() []struct {
	Context1        context.Context
	OutboundMessage *protocol.OutboundMessage
} {
	var calls []struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}
	mock.lockSendCronjobRoot.RLock()
	calls = mock.calls.SendCronjobRoot
	mock.lockSendCronjobRoot.RUnlock()
	return calls
}

// SidebarChannelAgentChoices calls SidebarChannelAgentChoicesFunc.
func (mock *SlackFrontendMock) SidebarChannelAgentChoices(context1 context.Context, s string) (string, []string, error) {
	if mock.SidebarChannelAgentChoicesFunc == nil {
		panic("SlackFrontendMock.SidebarChannelAgentChoicesFunc: method is nil but SlackFrontend.SidebarChannelAgentChoices was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockSidebarChannelAgentChoices.Lock()
	mock.calls.SidebarChannelAgentChoices = append(mock.calls.SidebarChannelAgentChoices, callInfo)
	mock.lockSidebarChannelAgentChoices.Unlock()
	return mock.SidebarChannelAgentChoicesFunc(context1, s)
}

// SidebarChannelAgentChoicesCalls gets all the calls that were made to SidebarChannelAgentChoices.
// Check the length with:
//
//	len(mockedSlackFrontend.SidebarChannelAgentChoicesCalls())
func (mock *SlackFrontendMock) SidebarChannelAgentChoicesCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockSidebarChannelAgentChoices.RLock()
	calls = mock.calls.SidebarChannelAgentChoices
	mock.lockSidebarChannelAgentChoices.RUnlock()
	return calls
}

// SlackTagsMatching calls SlackTagsMatchingFunc.
func (mock *SlackFrontendMock) SlackTagsMatching(context1 context.Context, s string) []string {
	if mock.SlackTagsMatchingFunc == nil {
		panic("SlackFrontendMock.SlackTagsMatchingFunc: method is nil but SlackFrontend.SlackTagsMatching was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockSlackTagsMatching.Lock()
	mock.calls.SlackTagsMatching = append(mock.calls.SlackTagsMatching, callInfo)
	mock.lockSlackTagsMatching.Unlock()
	return mock.SlackTagsMatchingFunc(context1, s)
}

// SlackTagsMatchingCalls gets all the calls that were made to SlackTagsMatching.
// Check the length with:
//
//	len(mockedSlackFrontend.SlackTagsMatchingCalls())
func (mock *SlackFrontendMock) SlackTagsMatchingCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockSlackTagsMatching.RLock()
	calls = mock.calls.SlackTagsMatching
	mock.lockSlackTagsMatching.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *SlackFrontendMock) Start(context1 context.Context) error {
	if mock.StartFunc == nil {
		panic("SlackFrontendMock.StartFunc: method is nil but SlackFrontend.Start was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(context1)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedSlackFrontend.StartCalls())
func (mock *SlackFrontendMock) StartCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *SlackFrontendMock) Stop(context1 context.Context) error {
	if mock.StopFunc == nil {
		panic("SlackFrontendMock.StopFunc: method is nil but SlackFrontend.Stop was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(context1)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedSlackFrontend.StopCalls())
func (mock *SlackFrontendMock) StopCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
