// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package main

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/frontend/cron"
	"github.com/Rocketable/platform/internal/rocketclaw/frontend/rpc"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that mockWebCron does implement rpc.CronJobs.
// If this is not the case, regenerate this file with mockery.
var _ rpc.CronJobs = &mockWebCron{}

// mockWebCron is a mock implementation of rpc.CronJobs.
//
//	func TestSomethingThatUsesCronJobs(t *testing.T) {
//
//		// make and configure a mocked rpc.CronJobs
//		mockedCronJobs := &mockWebCron{
//			JobsFunc: func() ([]cronfrontend.Job, error) {
//				panic("mock out the Jobs method")
//			},
//			LoadOneOffCronjobFunc: func(s string) (protocol.OneOffCronjob, error) {
//				panic("mock out the LoadOneOffCronjob method")
//			},
//			RunOneOffCronjobFunc: func(context1 context.Context, oneOffCronjob *protocol.OneOffCronjob) (protocol.CronRunResult, error) {
//				panic("mock out the RunOneOffCronjob method")
//			},
//		}
//
//		// use mockedCronJobs in code that requires rpc.CronJobs
//		// and then make assertions.
//
//	}
type mockWebCron struct {
	// JobsFunc mocks the Jobs method.
	JobsFunc func() ([]cronfrontend.Job, error)

	// LoadOneOffCronjobFunc mocks the LoadOneOffCronjob method.
	LoadOneOffCronjobFunc func(s string) (protocol.OneOffCronjob, error)

	// RunOneOffCronjobFunc mocks the RunOneOffCronjob method.
	RunOneOffCronjobFunc func(context1 context.Context, oneOffCronjob *protocol.OneOffCronjob) (protocol.CronRunResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Jobs holds details about calls to the Jobs method.
		Jobs []struct {
		}
		// LoadOneOffCronjob holds details about calls to the LoadOneOffCronjob method.
		LoadOneOffCronjob []struct {
			// S is the s argument value.
			S string
		}
		// RunOneOffCronjob holds details about calls to the RunOneOffCronjob method.
		RunOneOffCronjob []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// OneOffCronjob is the oneOffCronjob argument value.
			OneOffCronjob *protocol.OneOffCronjob
		}
	}
	lockJobs              sync.RWMutex
	lockLoadOneOffCronjob sync.RWMutex
	lockRunOneOffCronjob  sync.RWMutex
}

// Jobs calls JobsFunc.
func (mock *mockWebCron) Jobs() ([]cronfrontend.Job, error) {
	if mock.JobsFunc == nil {
		panic("mockWebCron.JobsFunc: method is nil but CronJobs.Jobs was just called")
	}
	callInfo := struct {
	}{}
	mock.lockJobs.Lock()
	mock.calls.Jobs = append(mock.calls.Jobs, callInfo)
	mock.lockJobs.Unlock()
	return mock.JobsFunc()
}

// JobsCalls gets all the calls that were made to Jobs.
// Check the length with:
//
//	len(mockedCronJobs.JobsCalls())
func (mock *mockWebCron) JobsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockJobs.RLock()
	calls = mock.calls.Jobs
	mock.lockJobs.RUnlock()
	return calls
}

// LoadOneOffCronjob calls LoadOneOffCronjobFunc.
func (mock *mockWebCron) LoadOneOffCronjob(s string) (protocol.OneOffCronjob, error) {
	if mock.LoadOneOffCronjobFunc == nil {
		panic("mockWebCron.LoadOneOffCronjobFunc: method is nil but CronJobs.LoadOneOffCronjob was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockLoadOneOffCronjob.Lock()
	mock.calls.LoadOneOffCronjob = append(mock.calls.LoadOneOffCronjob, callInfo)
	mock.lockLoadOneOffCronjob.Unlock()
	return mock.LoadOneOffCronjobFunc(s)
}

// LoadOneOffCronjobCalls gets all the calls that were made to LoadOneOffCronjob.
// Check the length with:
//
//	len(mockedCronJobs.LoadOneOffCronjobCalls())
func (mock *mockWebCron) LoadOneOffCronjobCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockLoadOneOffCronjob.RLock()
	calls = mock.calls.LoadOneOffCronjob
	mock.lockLoadOneOffCronjob.RUnlock()
	return calls
}

// RunOneOffCronjob calls RunOneOffCronjobFunc.
func (mock *mockWebCron) RunOneOffCronjob(context1 context.Context, oneOffCronjob *protocol.OneOffCronjob) (protocol.CronRunResult, error) {
	if mock.RunOneOffCronjobFunc == nil {
		panic("mockWebCron.RunOneOffCronjobFunc: method is nil but CronJobs.RunOneOffCronjob was just called")
	}
	callInfo := struct {
		Context1      context.Context
		OneOffCronjob *protocol.OneOffCronjob
	}{
		Context1:      context1,
		OneOffCronjob: oneOffCronjob,
	}
	mock.lockRunOneOffCronjob.Lock()
	mock.calls.RunOneOffCronjob = append(mock.calls.RunOneOffCronjob, callInfo)
	mock.lockRunOneOffCronjob.Unlock()
	return mock.RunOneOffCronjobFunc(context1, oneOffCronjob)
}

// RunOneOffCronjobCalls gets all the calls that were made to RunOneOffCronjob.
// Check the length with:
//
//	len(mockedCronJobs.RunOneOffCronjobCalls())
func (mock *mockWebCron) RunOneOffCronjobCalls() []struct {
	Context1      context.Context
	OneOffCronjob *protocol.OneOffCronjob
} {
	var calls []struct {
		Context1      context.Context
		OneOffCronjob *protocol.OneOffCronjob
	}
	mock.lockRunOneOffCronjob.RLock()
	calls = mock.calls.RunOneOffCronjob
	mock.lockRunOneOffCronjob.RUnlock()
	return calls
}
