-- +migrate Up
CREATE TABLE store_bootstrap (id INTEGER PRIMARY KEY CHECK (id = 1), imported_at_unix_ns BIGINT NOT NULL);
CREATE TABLE session_entries (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id TEXT NOT NULL, entry_json TEXT NOT NULL, entry_timestamp TEXT NOT NULL);
CREATE INDEX session_entries_conversation_id_id ON session_entries (conversation_id, id);
CREATE INDEX session_entries_conversation_id_timestamp ON session_entries (conversation_id, entry_timestamp);
CREATE TABLE managed_conversations (conversation_id TEXT PRIMARY KEY, agent TEXT NOT NULL, created_by TEXT NOT NULL);
CREATE TABLE conversation_goals (conversation_id TEXT PRIMARY KEY, objective TEXT NOT NULL, check_script TEXT NOT NULL, max_turns INTEGER NOT NULL, turns_used INTEGER NOT NULL, status TEXT NOT NULL, note TEXT NOT NULL, slack_recipient_team_id TEXT NOT NULL DEFAULT '', slack_recipient_user_id TEXT NOT NULL DEFAULT '', created_at_unix_ns BIGINT NOT NULL, updated_at_unix_ns BIGINT NOT NULL);
CREATE TABLE external_mcp_sessions (external_conversation_id TEXT PRIMARY KEY, private_conversation_id TEXT UNIQUE CHECK (private_conversation_id IS NULL OR trim(private_conversation_id) <> ''), managed_conversation_id TEXT NOT NULL UNIQUE CHECK (trim(managed_conversation_id) <> ''), agent TEXT NOT NULL, slack_channel TEXT NOT NULL);
CREATE TABLE scheduled_messages (scheduled_message_id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, agent TEXT NOT NULL, message TEXT NOT NULL, due_at_unix_ns BIGINT NOT NULL, recurring INTEGER NOT NULL, interval_ns BIGINT NOT NULL);
CREATE TABLE cron_schedules (schedule_id TEXT PRIMARY KEY, relative_path TEXT NOT NULL, next_due_unix_ns BIGINT NOT NULL, updated_at_unix_ns BIGINT NOT NULL);
CREATE TABLE cron_schedule_runs (relative_path TEXT PRIMARY KEY, running INTEGER NOT NULL, running_since_unix_ns BIGINT NOT NULL, updated_at_unix_ns BIGINT NOT NULL);
CREATE INDEX cron_schedules_next_due_id ON cron_schedules (next_due_unix_ns, schedule_id);
CREATE INDEX cron_schedules_relative_path ON cron_schedules (relative_path);
CREATE INDEX cron_schedule_runs_running_path ON cron_schedule_runs (running, relative_path);
CREATE TABLE pending_restart_notifications (conversation_id TEXT PRIMARY KEY);
CREATE TABLE active_turns (id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, agent TEXT NOT NULL, model TEXT NOT NULL, display_model TEXT NOT NULL, replay_input_json TEXT NOT NULL, output_trace_json TEXT NOT NULL, token_usage_json TEXT NOT NULL, response_id TEXT NOT NULL, open_function_calls_json TEXT NOT NULL, completed_function_outputs_json TEXT NOT NULL, restart_notice_json TEXT NOT NULL, source_metadata_json TEXT NOT NULL, created_at_unix_ns BIGINT NOT NULL, updated_at_unix_ns BIGINT NOT NULL);
CREATE INDEX active_turns_conversation_updated ON active_turns (conversation_id, updated_at_unix_ns);

-- +migrate Down
DROP TABLE active_turns;
DROP TABLE pending_restart_notifications;
DROP TABLE cron_schedule_runs;
DROP TABLE cron_schedules;
DROP TABLE scheduled_messages;
DROP TABLE external_mcp_sessions;
DROP TABLE conversation_goals;
DROP TABLE managed_conversations;
DROP TABLE session_entries;
DROP TABLE store_bootstrap;
