// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rpc

import (
	"context"
	"iter"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/frontend"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that mockBackend does implement frontend.Backend.
// If this is not the case, regenerate this file with mockery.
var _ frontend.Backend = &mockBackend{}

// mockBackend is a mock implementation of frontend.Backend.
//
//	func TestSomethingThatUsesBackend(t *testing.T) {
//
//		// make and configure a mocked frontend.Backend
//		mockedBackend := &mockBackend{
//			CreateConversationFunc: func(context1 context.Context, conversation protocol.Conversation) error {
//				panic("mock out the CreateConversation method")
//			},
//			DeleteQueueItemFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the DeleteQueueItem method")
//			},
//			ListConversationsFunc: func(context1 context.Context) ([]protocol.Conversation, error) {
//				panic("mock out the ListConversations method")
//			},
//			PromoteQueueItemFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the PromoteQueueItem method")
//			},
//			QueueItemsFunc: func(context1 context.Context, s string) ([]protocol.ThreadQueueItem, error) {
//				panic("mock out the QueueItems method")
//			},
//			ReorderQueueItemsFunc: func(context1 context.Context, s string, strings []string) error {
//				panic("mock out the ReorderQueueItems method")
//			},
//			RunTurnFunc: func(context1 context.Context, inboundMessage *protocol.InboundMessage) error {
//				panic("mock out the RunTurn method")
//			},
//			StashQueueItemFunc: func(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error {
//				panic("mock out the StashQueueItem method")
//			},
//			SubscribeFunc: func(context1 context.Context) iter.Seq[protocol.Event] {
//				panic("mock out the Subscribe method")
//			},
//			SwitchConversationAgentFunc: func(s string, s1 string) (bool, error) {
//				panic("mock out the SwitchConversationAgent method")
//			},
//			SyncConversationFunc: func(context1 context.Context, s string, s1 string) error {
//				panic("mock out the SyncConversation method")
//			},
//		}
//
//		// use mockedBackend in code that requires frontend.Backend
//		// and then make assertions.
//
//	}
type mockBackend struct {
	// CreateConversationFunc mocks the CreateConversation method.
	CreateConversationFunc func(context1 context.Context, conversation protocol.Conversation) error

	// DeleteQueueItemFunc mocks the DeleteQueueItem method.
	DeleteQueueItemFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// ListConversationsFunc mocks the ListConversations method.
	ListConversationsFunc func(context1 context.Context) ([]protocol.Conversation, error)

	// PromoteQueueItemFunc mocks the PromoteQueueItem method.
	PromoteQueueItemFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// QueueItemsFunc mocks the QueueItems method.
	QueueItemsFunc func(context1 context.Context, s string) ([]protocol.ThreadQueueItem, error)

	// ReorderQueueItemsFunc mocks the ReorderQueueItems method.
	ReorderQueueItemsFunc func(context1 context.Context, s string, strings []string) error

	// RunTurnFunc mocks the RunTurn method.
	RunTurnFunc func(context1 context.Context, inboundMessage *protocol.InboundMessage) error

	// StashQueueItemFunc mocks the StashQueueItem method.
	StashQueueItemFunc func(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(context1 context.Context) iter.Seq[protocol.Event]

	// SwitchConversationAgentFunc mocks the SwitchConversationAgent method.
	SwitchConversationAgentFunc func(s string, s1 string) (bool, error)

	// SyncConversationFunc mocks the SyncConversation method.
	SyncConversationFunc func(context1 context.Context, s string, s1 string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateConversation holds details about calls to the CreateConversation method.
		CreateConversation []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Conversation is the conversation argument value.
			Conversation protocol.Conversation
		}
		// DeleteQueueItem holds details about calls to the DeleteQueueItem method.
		DeleteQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// ListConversations holds details about calls to the ListConversations method.
		ListConversations []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// PromoteQueueItem holds details about calls to the PromoteQueueItem method.
		PromoteQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// QueueItems holds details about calls to the QueueItems method.
		QueueItems []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// ReorderQueueItems holds details about calls to the ReorderQueueItems method.
		ReorderQueueItems []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// Strings is the strings argument value.
			Strings []string
		}
		// RunTurn holds details about calls to the RunTurn method.
		RunTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// InboundMessage is the inboundMessage argument value.
			InboundMessage *protocol.InboundMessage
		}
		// StashQueueItem holds details about calls to the StashQueueItem method.
		StashQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// ThreadQueueItem is the threadQueueItem argument value.
			ThreadQueueItem *protocol.ThreadQueueItem
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// SwitchConversationAgent holds details about calls to the SwitchConversationAgent method.
		SwitchConversationAgent []struct {
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// SyncConversation holds details about calls to the SyncConversation method.
		SyncConversation []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
	}
	lockCreateConversation      sync.RWMutex
	lockDeleteQueueItem         sync.RWMutex
	lockListConversations       sync.RWMutex
	lockPromoteQueueItem        sync.RWMutex
	lockQueueItems              sync.RWMutex
	lockReorderQueueItems       sync.RWMutex
	lockRunTurn                 sync.RWMutex
	lockStashQueueItem          sync.RWMutex
	lockSubscribe               sync.RWMutex
	lockSwitchConversationAgent sync.RWMutex
	lockSyncConversation        sync.RWMutex
}

// CreateConversation calls CreateConversationFunc.
func (mock *mockBackend) CreateConversation(context1 context.Context, conversation protocol.Conversation) error {
	if mock.CreateConversationFunc == nil {
		panic("mockBackend.CreateConversationFunc: method is nil but Backend.CreateConversation was just called")
	}
	callInfo := struct {
		Context1     context.Context
		Conversation protocol.Conversation
	}{
		Context1:     context1,
		Conversation: conversation,
	}
	mock.lockCreateConversation.Lock()
	mock.calls.CreateConversation = append(mock.calls.CreateConversation, callInfo)
	mock.lockCreateConversation.Unlock()
	return mock.CreateConversationFunc(context1, conversation)
}

// CreateConversationCalls gets all the calls that were made to CreateConversation.
// Check the length with:
//
//	len(mockedBackend.CreateConversationCalls())
func (mock *mockBackend) CreateConversationCalls() []struct {
	Context1     context.Context
	Conversation protocol.Conversation
} {
	var calls []struct {
		Context1     context.Context
		Conversation protocol.Conversation
	}
	mock.lockCreateConversation.RLock()
	calls = mock.calls.CreateConversation
	mock.lockCreateConversation.RUnlock()
	return calls
}

// DeleteQueueItem calls DeleteQueueItemFunc.
func (mock *mockBackend) DeleteQueueItem(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.DeleteQueueItemFunc == nil {
		panic("mockBackend.DeleteQueueItemFunc: method is nil but Backend.DeleteQueueItem was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockDeleteQueueItem.Lock()
	mock.calls.DeleteQueueItem = append(mock.calls.DeleteQueueItem, callInfo)
	mock.lockDeleteQueueItem.Unlock()
	return mock.DeleteQueueItemFunc(context1, s, s1)
}

// DeleteQueueItemCalls gets all the calls that were made to DeleteQueueItem.
// Check the length with:
//
//	len(mockedBackend.DeleteQueueItemCalls())
func (mock *mockBackend) DeleteQueueItemCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockDeleteQueueItem.RLock()
	calls = mock.calls.DeleteQueueItem
	mock.lockDeleteQueueItem.RUnlock()
	return calls
}

// ListConversations calls ListConversationsFunc.
func (mock *mockBackend) ListConversations(context1 context.Context) ([]protocol.Conversation, error) {
	if mock.ListConversationsFunc == nil {
		panic("mockBackend.ListConversationsFunc: method is nil but Backend.ListConversations was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockListConversations.Lock()
	mock.calls.ListConversations = append(mock.calls.ListConversations, callInfo)
	mock.lockListConversations.Unlock()
	return mock.ListConversationsFunc(context1)
}

// ListConversationsCalls gets all the calls that were made to ListConversations.
// Check the length with:
//
//	len(mockedBackend.ListConversationsCalls())
func (mock *mockBackend) ListConversationsCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockListConversations.RLock()
	calls = mock.calls.ListConversations
	mock.lockListConversations.RUnlock()
	return calls
}

// PromoteQueueItem calls PromoteQueueItemFunc.
func (mock *mockBackend) PromoteQueueItem(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.PromoteQueueItemFunc == nil {
		panic("mockBackend.PromoteQueueItemFunc: method is nil but Backend.PromoteQueueItem was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockPromoteQueueItem.Lock()
	mock.calls.PromoteQueueItem = append(mock.calls.PromoteQueueItem, callInfo)
	mock.lockPromoteQueueItem.Unlock()
	return mock.PromoteQueueItemFunc(context1, s, s1)
}

// PromoteQueueItemCalls gets all the calls that were made to PromoteQueueItem.
// Check the length with:
//
//	len(mockedBackend.PromoteQueueItemCalls())
func (mock *mockBackend) PromoteQueueItemCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockPromoteQueueItem.RLock()
	calls = mock.calls.PromoteQueueItem
	mock.lockPromoteQueueItem.RUnlock()
	return calls
}

// QueueItems calls QueueItemsFunc.
func (mock *mockBackend) QueueItems(context1 context.Context, s string) ([]protocol.ThreadQueueItem, error) {
	if mock.QueueItemsFunc == nil {
		panic("mockBackend.QueueItemsFunc: method is nil but Backend.QueueItems was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockQueueItems.Lock()
	mock.calls.QueueItems = append(mock.calls.QueueItems, callInfo)
	mock.lockQueueItems.Unlock()
	return mock.QueueItemsFunc(context1, s)
}

// QueueItemsCalls gets all the calls that were made to QueueItems.
// Check the length with:
//
//	len(mockedBackend.QueueItemsCalls())
func (mock *mockBackend) QueueItemsCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockQueueItems.RLock()
	calls = mock.calls.QueueItems
	mock.lockQueueItems.RUnlock()
	return calls
}

// ReorderQueueItems calls ReorderQueueItemsFunc.
func (mock *mockBackend) ReorderQueueItems(context1 context.Context, s string, strings []string) error {
	if mock.ReorderQueueItemsFunc == nil {
		panic("mockBackend.ReorderQueueItemsFunc: method is nil but Backend.ReorderQueueItems was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		Strings  []string
	}{
		Context1: context1,
		S:        s,
		Strings:  strings,
	}
	mock.lockReorderQueueItems.Lock()
	mock.calls.ReorderQueueItems = append(mock.calls.ReorderQueueItems, callInfo)
	mock.lockReorderQueueItems.Unlock()
	return mock.ReorderQueueItemsFunc(context1, s, strings)
}

// ReorderQueueItemsCalls gets all the calls that were made to ReorderQueueItems.
// Check the length with:
//
//	len(mockedBackend.ReorderQueueItemsCalls())
func (mock *mockBackend) ReorderQueueItemsCalls() []struct {
	Context1 context.Context
	S        string
	Strings  []string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		Strings  []string
	}
	mock.lockReorderQueueItems.RLock()
	calls = mock.calls.ReorderQueueItems
	mock.lockReorderQueueItems.RUnlock()
	return calls
}

// RunTurn calls RunTurnFunc.
func (mock *mockBackend) RunTurn(context1 context.Context, inboundMessage *protocol.InboundMessage) error {
	if mock.RunTurnFunc == nil {
		panic("mockBackend.RunTurnFunc: method is nil but Backend.RunTurn was just called")
	}
	callInfo := struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
	}{
		Context1:       context1,
		InboundMessage: inboundMessage,
	}
	mock.lockRunTurn.Lock()
	mock.calls.RunTurn = append(mock.calls.RunTurn, callInfo)
	mock.lockRunTurn.Unlock()
	return mock.RunTurnFunc(context1, inboundMessage)
}

// RunTurnCalls gets all the calls that were made to RunTurn.
// Check the length with:
//
//	len(mockedBackend.RunTurnCalls())
func (mock *mockBackend) RunTurnCalls() []struct {
	Context1       context.Context
	InboundMessage *protocol.InboundMessage
} {
	var calls []struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
	}
	mock.lockRunTurn.RLock()
	calls = mock.calls.RunTurn
	mock.lockRunTurn.RUnlock()
	return calls
}

// StashQueueItem calls StashQueueItemFunc.
func (mock *mockBackend) StashQueueItem(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error {
	if mock.StashQueueItemFunc == nil {
		panic("mockBackend.StashQueueItemFunc: method is nil but Backend.StashQueueItem was just called")
	}
	callInfo := struct {
		Context1        context.Context
		S               string
		ThreadQueueItem *protocol.ThreadQueueItem
	}{
		Context1:        context1,
		S:               s,
		ThreadQueueItem: threadQueueItem,
	}
	mock.lockStashQueueItem.Lock()
	mock.calls.StashQueueItem = append(mock.calls.StashQueueItem, callInfo)
	mock.lockStashQueueItem.Unlock()
	return mock.StashQueueItemFunc(context1, s, threadQueueItem)
}

// StashQueueItemCalls gets all the calls that were made to StashQueueItem.
// Check the length with:
//
//	len(mockedBackend.StashQueueItemCalls())
func (mock *mockBackend) StashQueueItemCalls() []struct {
	Context1        context.Context
	S               string
	ThreadQueueItem *protocol.ThreadQueueItem
} {
	var calls []struct {
		Context1        context.Context
		S               string
		ThreadQueueItem *protocol.ThreadQueueItem
	}
	mock.lockStashQueueItem.RLock()
	calls = mock.calls.StashQueueItem
	mock.lockStashQueueItem.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *mockBackend) Subscribe(context1 context.Context) iter.Seq[protocol.Event] {
	if mock.SubscribeFunc == nil {
		panic("mockBackend.SubscribeFunc: method is nil but Backend.Subscribe was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(context1)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedBackend.SubscribeCalls())
func (mock *mockBackend) SubscribeCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// SwitchConversationAgent calls SwitchConversationAgentFunc.
func (mock *mockBackend) SwitchConversationAgent(s string, s1 string) (bool, error) {
	if mock.SwitchConversationAgentFunc == nil {
		panic("mockBackend.SwitchConversationAgentFunc: method is nil but Backend.SwitchConversationAgent was just called")
	}
	callInfo := struct {
		S  string
		S1 string
	}{
		S:  s,
		S1: s1,
	}
	mock.lockSwitchConversationAgent.Lock()
	mock.calls.SwitchConversationAgent = append(mock.calls.SwitchConversationAgent, callInfo)
	mock.lockSwitchConversationAgent.Unlock()
	return mock.SwitchConversationAgentFunc(s, s1)
}

// SwitchConversationAgentCalls gets all the calls that were made to SwitchConversationAgent.
// Check the length with:
//
//	len(mockedBackend.SwitchConversationAgentCalls())
func (mock *mockBackend) SwitchConversationAgentCalls() []struct {
	S  string
	S1 string
} {
	var calls []struct {
		S  string
		S1 string
	}
	mock.lockSwitchConversationAgent.RLock()
	calls = mock.calls.SwitchConversationAgent
	mock.lockSwitchConversationAgent.RUnlock()
	return calls
}

// SyncConversation calls SyncConversationFunc.
func (mock *mockBackend) SyncConversation(context1 context.Context, s string, s1 string) error {
	if mock.SyncConversationFunc == nil {
		panic("mockBackend.SyncConversationFunc: method is nil but Backend.SyncConversation was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockSyncConversation.Lock()
	mock.calls.SyncConversation = append(mock.calls.SyncConversation, callInfo)
	mock.lockSyncConversation.Unlock()
	return mock.SyncConversationFunc(context1, s, s1)
}

// SyncConversationCalls gets all the calls that were made to SyncConversation.
// Check the length with:
//
//	len(mockedBackend.SyncConversationCalls())
func (mock *mockBackend) SyncConversationCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockSyncConversation.RLock()
	calls = mock.calls.SyncConversation
	mock.lockSyncConversation.RUnlock()
	return calls
}
