// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rpc

import (
	"context"
	"log/slog"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/frontend/cron"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that mockCronRunner does implement cronfrontend.Runner.
// If this is not the case, regenerate this file with mockery.
var _ cronfrontend.Runner = &mockCronRunner{}

// mockCronRunner is a mock implementation of cronfrontend.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked cronfrontend.Runner
//		mockedRunner := &mockCronRunner{
//			RunFunc: func(context1 context.Context, s string, s1 string, logger *slog.Logger, rawRunProgress *backend.RawRunProgress) (protocol.CronRunResult, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires cronfrontend.Runner
//		// and then make assertions.
//
//	}
type mockCronRunner struct {
	// RunFunc mocks the Run method.
	RunFunc func(context1 context.Context, s string, s1 string, logger *slog.Logger, rawRunProgress *backend.RawRunProgress) (protocol.CronRunResult, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// Logger is the logger argument value.
			Logger *slog.Logger
			// RawRunProgress is the rawRunProgress argument value.
			RawRunProgress *backend.RawRunProgress
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *mockCronRunner) Run(context1 context.Context, s string, s1 string, logger *slog.Logger, rawRunProgress *backend.RawRunProgress) (protocol.CronRunResult, error) {
	if mock.RunFunc == nil {
		panic("mockCronRunner.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Context1       context.Context
		S              string
		S1             string
		Logger         *slog.Logger
		RawRunProgress *backend.RawRunProgress
	}{
		Context1:       context1,
		S:              s,
		S1:             s1,
		Logger:         logger,
		RawRunProgress: rawRunProgress,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(context1, s, s1, logger, rawRunProgress)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *mockCronRunner) RunCalls() []struct {
	Context1       context.Context
	S              string
	S1             string
	Logger         *slog.Logger
	RawRunProgress *backend.RawRunProgress
} {
	var calls []struct {
		Context1       context.Context
		S              string
		S1             string
		Logger         *slog.Logger
		RawRunProgress *backend.RawRunProgress
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
