// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rpc

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/config"
)

// Ensure that mockFrontendAssembler does implement backend.FrontendAssembler.
// If this is not the case, regenerate this file with mockery.
var _ backend.FrontendAssembler = &mockFrontendAssembler{}

// mockFrontendAssembler is a mock implementation of backend.FrontendAssembler.
//
//	func TestSomethingThatUsesFrontendAssembler(t *testing.T) {
//
//		// make and configure a mocked backend.FrontendAssembler
//		mockedFrontendAssembler := &mockFrontendAssembler{
//			AssembleFunc: func(runtime *backend.Runtime) (backend.SlackFrontend, <-chan struct{}, []func(context.Context) error, error) {
//				panic("mock out the Assemble method")
//			},
//			ValidateAssetsFunc: func(config1 *config.Config, s string, strings []string) error {
//				panic("mock out the ValidateAssets method")
//			},
//		}
//
//		// use mockedFrontendAssembler in code that requires backend.FrontendAssembler
//		// and then make assertions.
//
//	}
type mockFrontendAssembler struct {
	// AssembleFunc mocks the Assemble method.
	AssembleFunc func(runtime *backend.Runtime) (backend.SlackFrontend, <-chan struct{}, []func(context.Context) error, error)

	// ValidateAssetsFunc mocks the ValidateAssets method.
	ValidateAssetsFunc func(config1 *config.Config, s string, strings []string) error

	// calls tracks calls to the methods.
	calls struct {
		// Assemble holds details about calls to the Assemble method.
		Assemble []struct {
			// Runtime is the runtime argument value.
			Runtime *backend.Runtime
		}
		// ValidateAssets holds details about calls to the ValidateAssets method.
		ValidateAssets []struct {
			// Config1 is the config1 argument value.
			Config1 *config.Config
			// S is the s argument value.
			S string
			// Strings is the strings argument value.
			Strings []string
		}
	}
	lockAssemble       sync.RWMutex
	lockValidateAssets sync.RWMutex
}

// Assemble calls AssembleFunc.
func (mock *mockFrontendAssembler) Assemble(runtime *backend.Runtime) (backend.SlackFrontend, <-chan struct{}, []func(context.Context) error, error) {
	if mock.AssembleFunc == nil {
		panic("mockFrontendAssembler.AssembleFunc: method is nil but FrontendAssembler.Assemble was just called")
	}
	callInfo := struct {
		Runtime *backend.Runtime
	}{
		Runtime: runtime,
	}
	mock.lockAssemble.Lock()
	mock.calls.Assemble = append(mock.calls.Assemble, callInfo)
	mock.lockAssemble.Unlock()
	return mock.AssembleFunc(runtime)
}

// AssembleCalls gets all the calls that were made to Assemble.
// Check the length with:
//
//	len(mockedFrontendAssembler.AssembleCalls())
func (mock *mockFrontendAssembler) AssembleCalls() []struct {
	Runtime *backend.Runtime
} {
	var calls []struct {
		Runtime *backend.Runtime
	}
	mock.lockAssemble.RLock()
	calls = mock.calls.Assemble
	mock.lockAssemble.RUnlock()
	return calls
}

// ValidateAssets calls ValidateAssetsFunc.
func (mock *mockFrontendAssembler) ValidateAssets(config1 *config.Config, s string, strings []string) error {
	if mock.ValidateAssetsFunc == nil {
		panic("mockFrontendAssembler.ValidateAssetsFunc: method is nil but FrontendAssembler.ValidateAssets was just called")
	}
	callInfo := struct {
		Config1 *config.Config
		S       string
		Strings []string
	}{
		Config1: config1,
		S:       s,
		Strings: strings,
	}
	mock.lockValidateAssets.Lock()
	mock.calls.ValidateAssets = append(mock.calls.ValidateAssets, callInfo)
	mock.lockValidateAssets.Unlock()
	return mock.ValidateAssetsFunc(config1, s, strings)
}

// ValidateAssetsCalls gets all the calls that were made to ValidateAssets.
// Check the length with:
//
//	len(mockedFrontendAssembler.ValidateAssetsCalls())
func (mock *mockFrontendAssembler) ValidateAssetsCalls() []struct {
	Config1 *config.Config
	S       string
	Strings []string
} {
	var calls []struct {
		Config1 *config.Config
		S       string
		Strings []string
	}
	mock.lockValidateAssets.RLock()
	calls = mock.calls.ValidateAssets
	mock.lockValidateAssets.RUnlock()
	return calls
}
