// Package rpc adapts the retained Web protocol to Go-owned conversation storage.
//
//go:generate protoc -I ../../web/proto --go_out=. --go_opt=paths=source_relative ../../web/proto/web.proto
//go:generate sh -c "printf '// Code generated by go generate; DO NOT EDIT.\n\npackage rpc\n\nconst protoSHA256 = \"%s\"\n' $(shasum -a 256 ../../web/proto/web.proto | cut -d ' ' -f 1) > protocol.gen.go"
package rpc

import (
	"cmp"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"time"
	"unicode"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/config"
	"github.com/Rocketable/platform/internal/rocketclaw/frontend"
	cronfrontend "github.com/Rocketable/platform/internal/rocketclaw/frontend/cron"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
	"github.com/Rocketable/platform/internal/rocketcode"
	"github.com/openai/openai-go/v3/responses"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Server supplies concrete Web handlers. The host owns transport registration.
type Server struct {
	backend   frontend.Backend
	sessions  *backend.SessionService
	usernames map[netip.Addr]string
	cfg       *config.Config
	channels  ChannelAgentChoices
	cronjobs  CronJobs
}

// ChannelAgentChoices supplies live policy for actions and stored facts for display.
type ChannelAgentChoices interface {
	ChannelAgentChoices(context.Context, string) ([]string, error)
	SidebarChannelAgentChoices(context.Context, string) (string, []string, error)
}

// CronJobs uses the process's existing Cron manager for reads and execution.
type CronJobs interface {
	Jobs() ([]cronfrontend.Job, error)
	LoadOneOffCronjob(string) (protocol.OneOffCronjob, error)
	RunOneOffCronjob(context.Context, *protocol.OneOffCronjob) (protocol.CronRunResult, error)
}

// New snapshots WebUsers from the validated startup configuration.
// The host must restrict RPC access to the trusted Web proxy: the metadata
// carries the browser IP, not an independently authenticated network peer.
func New(core frontend.Backend, sessions *backend.SessionService, cfg *config.Config, channels ChannelAgentChoices, cronjobs CronJobs) *Server {
	return &Server{backend: core, sessions: sessions, usernames: maps.Clone(cfg.WebUsers), cfg: cfg, channels: channels, cronjobs: cronjobs}
}

// ListSessionEntries returns ordered entry identifiers and metadata.
func (s *Server) ListSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*ListSessionEntriesResponse, error) {
	entries, err := s.entries(ctx, request.Id)
	if err != nil {
		return nil, err
	}

	response := &ListSessionEntriesResponse{}

	for i := range entries {
		entry := &entries[i]
		response.Entries = append(response.Entries, &SessionEntryMeta{
			Id: entry.ID, Type: entry.Entry.Type, Timestamp: entry.Entry.Timestamp.Format(time.RFC3339Nano),
		})
	}

	return response, nil
}

// LoadSessionEntries returns stored entry values as JSON, preserving int64 IDs.
func (s *Server) LoadSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*LoadSessionEntriesResponse, error) {
	entries, err := s.entries(ctx, request.Id)
	if err != nil {
		return nil, err
	}

	response := &LoadSessionEntriesResponse{}

	for i := range entries {
		entry := &entries[i]

		data, err := json.Marshal(entry.Entry)
		if err != nil {
			return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "encode session entry"))
		}

		response.Entries = append(response.Entries, &SessionEntryData{Id: entry.ID, Json: string(data)})
	}

	return response, nil
}

// DeleteSessionEntries deletes entries only; conversation and goal records remain.
func (s *Server) DeleteSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*DeleteSessionEntriesResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	deleted, err := s.sessions.DeleteSession(ctx, request.Id)
	if err != nil {
		return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "delete session entries"))
	}

	return &DeleteSessionEntriesResponse{Deleted: deleted}, nil
}

func (s *Server) listSessions(stream grpc.ServerStream) error {
	ctx := stream.Context()

	owner, err := s.principal(ctx)
	if err != nil {
		return err
	}

	complete := true
	metadataByChannel := make(map[string]*Session)

	settleAfter, err := s.cfg.Web.SettleAfter()
	if err != nil {
		return fmt.Errorf("web session inactivity period: %w", err)
	}

	for row, err := range s.sessions.SidebarSessions(ctx, time.Now().Add(-settleAfter)) {
		if err != nil {
			return err
		}

		conversation := row.Conversation
		complete = complete && row.Summary != nil

		allChoices, loaded := metadataByChannel[""]
		if !loaded {
			choices, err := s.agentChoices(ctx, "")
			if err != nil {
				return err
			}

			allChoices = &Session{AllowedAgents: choices}
			metadataByChannel[""] = allChoices
		}

		channel, _, slack := protocol.SlackThreadTarget(conversation.ID)
		if !slack {
			channel = ""
		}

		channelMetadata, loaded := metadataByChannel[channel]
		if !loaded {
			name, allowed, err := s.channels.SidebarChannelAgentChoices(ctx, channel)
			if err != nil {
				return fmt.Errorf("web channel choices: %w", err)
			}

			choices := slices.DeleteFunc(slices.Clone(allChoices.AllowedAgents), func(name string) bool { return !slices.Contains(allowed, name) })
			channelMetadata = &Session{Title: name, AllowedAgents: choices}
			metadataByChannel[channel] = channelMetadata
		}

		session := &Session{Id: conversation.ID, Title: channelMetadata.Title, Agent: conversation.Agent, AllowedAgents: channelMetadata.AllowedAgents, Settled: conversation.Settled, Running: row.Running, Pinned: row.Pinned, Name: row.Name}
		if strings.HasPrefix(conversation.ID, "web:") {
			session.AllowedAgents, err = s.agentChoices(ctx, conversation.ID)
			if err != nil {
				return err
			}
		}

		if summary := row.Summary; summary != nil {
			session.Preview = summary.LastMessage
			if !summary.LastUpdated.IsZero() {
				session.UpdatedAt = summary.LastUpdated.Format(time.RFC3339Nano)
			}
		}

		if err := stream.SendMsg(&ListSessionsResponse{Sessions: []*Session{session}, Owner: owner, SummariesComplete: row.Summary != nil}); err != nil {
			return fmt.Errorf("send web session: %w", err)
		}
	}

	if err := stream.SendMsg(&ListSessionsResponse{Owner: owner, UpstreamSuccess: true, SummariesComplete: complete}); err != nil {
		return fmt.Errorf("send web session completion: %w", err)
	}

	return nil
}

func (s *Server) history(ctx context.Context, request *HistoryRequest) (*HistoryResponse, error) {
	if _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	// Cron producer history is readable without granting chat or mutation access.
	cronTrace := strings.HasPrefix(request.Id, "cron:") || strings.HasPrefix(request.Id, "one-off-cron:")
	if !cronTrace {
		if err := s.visibleConversation(ctx, request.Id); err != nil {
			return nil, err
		}
	}

	entries, err := s.sessions.ObserveEntries(ctx, request.Id)
	if err != nil {
		return nil, fmt.Errorf("read web history: %w", err)
	}

	response := &HistoryResponse{}

	if !cronTrace {
		origin, err := s.chatOrigin(ctx, request.Id, entries)
		if err != nil {
			return nil, err
		}

		response.Origin = origin
	}

	if request.OriginOnly {
		return response, nil
	}

	root, err := os.OpenRoot(s.cfg.Workspace)
	if err != nil {
		return nil, fmt.Errorf("open attachment workspace: %w", err)
	}

	defer func() { _ = root.Close() }()

	calls := make(map[string]map[string]string)

	for i := range entries {
		entry := &entries[i]
		if entry.Synced && entry.SourceConversationID == "" && !cronTrace {
			continue
		}

		producer := cmp.Or(entry.SourceConversationID, request.Id)

		if calls[producer] == nil {
			calls[producer] = make(map[string]string)
		}

		if request.GetSourceConversationId() != "" && entry.SourceConversationID != request.GetSourceConversationId() {
			continue
		}

		items, err := rocketcode.ReplayInputToParams(entry.Entry.ReplayInput)
		if err != nil {
			return nil, fmt.Errorf("decode web history: %w", err)
		}

		deliveryText, err := backend.ReplayDeliveryText(items)
		if err != nil {
			return nil, fmt.Errorf("web history: %w", err)
		}

		lastReply := ""

		for i := range items {
			attachments, err := s.sessions.ReplayAttachments(ctx, producer, root, entry.Entry.ReplayInput[i], calls[producer])
			if err != nil {
				return nil, fmt.Errorf("project history attachments: %w", err)
			}

			event, err := historyEvent(&items[i], entry.Entry.ReplayInput[i])
			if err != nil {
				return nil, err
			}

			if event != nil {
				for j := range attachments {
					event.Attachments = append(event.Attachments, attachmentMetadata(producer, &attachments[j]))
				}

				if event.Role == "user" {
					event, err = s.inputEvent(ctx, producer, event.Text)
					if err != nil {
						return nil, err
					}

					event.Complete = true
				}

				response.Messages = append(response.Messages, event)
				if event.Role == "assistant" {
					lastReply = event.Text
				}
			}
		}

		if strings.TrimSpace(deliveryText) != "" && deliveryText != lastReply {
			response.Messages = append(response.Messages, &TranscriptEvent{Role: "assistant", Text: deliveryText, Complete: true})
		}
	}

	return response, nil
}

func (s *Server) inputEvent(ctx context.Context, id, text string) (*TranscriptEvent, error) {
	var attachments []*Attachment

	for word := range strings.FieldsSeq(text) {
		if attachmentID, ok := strings.CutPrefix(word, "attachment:"); ok {
			attachment, err := s.sessions.AttachmentMetadata(ctx, id, attachmentID, true)
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}

			if err != nil {
				return nil, fmt.Errorf("load input attachment metadata: %w", err)
			}

			attachments = append(attachments, attachmentMetadata(id, &attachment))
		}
	}

	for _, file := range slices.Backward(attachments) {
		reference := fmt.Sprintf("attachment:%s %q (workspace path %q)", file.Id, file.Name, filepath.Join("artifacts", "uploads", file.Id, file.Name))
		if text == reference {
			text = ""
		} else {
			text = strings.TrimSuffix(text, "\n\n"+reference)
		}
	}

	return &TranscriptEvent{Role: "user", Text: text, Attachments: attachments}, nil
}

func historyEvent(item *responses.ResponseInputItemUnionParam, raw json.RawMessage) (*TranscriptEvent, error) {
	var kind struct {
		Type      string `json:"type"`
		Name      string `json:"name"`
		CallID    string `json:"call_id"`
		Arguments string `json:"arguments"`
		Output    string `json:"output"`
		Summary   []struct {
			Text string `json:"text"`
		} `json:"summary"`
	}
	if err := json.Unmarshal(raw, &kind); err != nil {
		return nil, fmt.Errorf("decode web history item: %w", err)
	}

	switch kind.Type {
	case "reasoning":
		parts := make([]string, 0, len(kind.Summary))
		for _, part := range kind.Summary {
			if text := strings.TrimSpace(part.Text); text != "" {
				parts = append(parts, text)
			}
		}

		text := strings.Join(parts, "\n")
		if text == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "thinking", Text: text, Complete: true}, nil
	case "function_call":
		text := strings.TrimSpace(kind.Name)
		if kind.Name == "rocketclaw_attach_files_to_response" {
			kind.Arguments = ""
		}

		if kind.Arguments != "" {
			if text != "" {
				text += "\n"
			}

			text += kind.Arguments
		}

		if strings.TrimSpace(text) == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "tool", Text: text, Complete: true, ToolCallId: kind.CallID, ToolName: kind.Name}, nil
	case "function_call_output":
		if strings.TrimSpace(kind.Output) == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "tool", Text: kind.Output, Complete: true, ToolCallId: kind.CallID}, nil
	}

	role, text, ok, err := backend.ReplayInputMessageRoleText(item, raw)
	if err != nil {
		return nil, fmt.Errorf("project web history: %w", err)
	}

	if !ok || strings.TrimSpace(text) == "" {
		return nil, nil
	}

	return &TranscriptEvent{Role: role, Text: text, Complete: true}, nil
}

func (s *Server) humanConversation(id string) (bool, error) {
	// These are the private producer locators minted by frontend/cron/manager.go.
	if strings.HasPrefix(id, "cron:") || strings.HasPrefix(id, "one-off-cron:") {
		return false, nil
	}

	_, pair, recorded, err := s.sessions.ExternalMCPSessionByConversationID(id)
	if err != nil {
		return false, fmt.Errorf("resolve web conversation visibility: %w", err)
	}

	return !recorded || pair.PrivateConversationID != id, nil
}

func (s *Server) listCronJobs(ctx context.Context) (*ListCronJobsResponse, error) {
	if _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	jobs, err := s.cronjobs.Jobs()
	if err != nil {
		return nil, fmt.Errorf("list web cron jobs: %w", err)
	}

	response := &ListCronJobsResponse{}

	for _, job := range jobs {
		row := &CronJob{Stem: strings.TrimSuffix(strings.TrimPrefix(job.RelativePath, "cron/"), ".md"), Schedule: strings.Join(job.Schedules, ", "), Body: job.Body, Agent: job.Agent, Channel: job.TextChannel, Origin: job.RelativePath}
		for _, at := range job.Upcoming {
			row.Upcoming = append(row.Upcoming, at.Format(time.RFC3339Nano))
		}

		if len(row.Upcoming) > 0 {
			row.NextRun = row.Upcoming[0]
		}

		response.Jobs = append(response.Jobs, row)
	}

	conversations, err := s.backend.ListConversations(ctx)
	if err != nil {
		return nil, fmt.Errorf("list cron history destinations: %w", err)
	}

	var (
		runs       []*CronJob
		executions []*CronJob
	)

	delivered := map[string]bool{}

	for _, conversation := range conversations {
		visible, err := s.humanConversation(conversation.ID)
		if err != nil {
			return nil, err
		}

		if !visible {
			// Private cron records contribute timing only, never replay content.
			if strings.HasPrefix(conversation.ID, "cron:") || strings.HasPrefix(conversation.ID, "one-off-cron:") {
				entries, err := s.sessions.ObserveEntries(ctx, conversation.ID)
				if err != nil {
					return nil, fmt.Errorf("read cron execution: %w", err)
				}

				if len(entries) > 0 {
					executions = append(executions, cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: conversation.ID}}, "")...)
				}
			}

			continue
		}

		entries, err := s.sessions.ObserveEntries(ctx, conversation.ID)
		if err != nil {
			return nil, fmt.Errorf("read cron history provenance: %w", err)
		}

		for _, run := range cronHistory(entries, conversation.ID) {
			delivered[run.Origin] = true
			runs = append(runs, run)
		}
	}

	for _, run := range executions {
		if !delivered[run.Origin] {
			runs = append(runs, run)
		}
	}

	slices.SortFunc(runs, func(a, b *CronJob) int {
		return cmp.Or(cmp.Compare(b.LastRun, a.LastRun), cmp.Compare(a.NextRun, b.NextRun), cmp.Compare(a.Origin, b.Origin))
	})
	response.Jobs = append(response.Jobs, runs...)

	return response, nil
}

func cronHistory(entries []backend.ObservedSessionEntry, destination string) []*CronJob {
	var runs []*CronJob

	seen := map[string]bool{}

	for i := range entries {
		source := entries[i].SourceConversationID
		if seen[source] {
			continue
		}

		run, ok := parseCronRun(source)
		if !ok {
			continue
		}

		seen[source] = true
		runs = append(runs, &CronJob{Stem: run.stem, Status: "ran", LastRun: run.at.Format("2006-01-02T15:04:05.000000000Z"), NextRun: destination, Origin: source})
	}

	return runs
}

func (s *Server) runCronJob(ctx context.Context, request *RunCronJobRequest) (*RunCronJobResponse, error) {
	principal, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	job, err := s.cronjobs.LoadOneOffCronjob(request.Stem)
	if err != nil {
		return nil, fmt.Errorf("load web cron job: %w", err)
	}

	id := rand.Text()
	if err := s.backend.CreateConversation(ctx, protocol.Conversation{ID: id, Agent: job.Agent, CreatedBy: principal}); err != nil {
		return nil, fmt.Errorf("create web cron conversation: %w", err)
	}

	job.ConversationID = id
	// The response has to name the session before the private run finishes, so the browser can open it.
	go func() {
		if _, err := s.cronjobs.RunOneOffCronjob(context.WithoutCancel(ctx), &job); err != nil {
			slog.Error("run web cron job", "stem", request.Stem, "id", id, "error", err)
		}
	}()

	return &RunCronJobResponse{Id: id}, nil
}

func (s *Server) settleSession(ctx context.Context, request *SettleSessionRequest) (*SettleSessionResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	updated, err := s.sessions.SetConversationSettled(ctx, request.Id, request.Settled)
	if err != nil {
		return nil, fmt.Errorf("settle web conversation: %w", err)
	}

	if !updated {
		return nil, fmt.Errorf("settle web conversation: %w", status.Error(codes.NotFound, "conversation is not recorded"))
	}

	return &SettleSessionResponse{}, nil
}

func (s *Server) updateSession(ctx context.Context, request *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	if request.Name != nil {
		if strings.ContainsRune(*request.Name, '\x00') {
			return nil, fmt.Errorf("update web conversation: %w", status.Error(codes.InvalidArgument, "name cannot contain a null character"))
		}

		request.Name = new(strings.TrimSpace(*request.Name))
	}

	updated, err := s.sessions.UpdateConversationDetails(ctx, request.Id, request.Pinned, request.Name)
	if err != nil {
		return nil, fmt.Errorf("update web conversation: %w", err)
	}

	if !updated {
		return nil, fmt.Errorf("update web conversation: %w", status.Error(codes.NotFound, "conversation is not recorded"))
	}

	return &UpdateSessionResponse{}, nil
}

func (s *Server) listConfig(ctx context.Context) (*ListConfigResponse, error) {
	if _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	settleAfter, err := s.cfg.Web.SettleAfter()
	if err != nil {
		return nil, fmt.Errorf("web config inactivity period: %w", err)
	}

	// This is the retained UI's allowlist, not serialization of the config.
	view := &ConfigView{
		Workspace: s.cfg.Workspace, Overlays: slices.Clone(s.cfg.Overlays),
		LoggingLevel: s.cfg.Logging.Level, AutoApproverModel: s.cfg.AutoApproverModel,
		InstrumentationEnabled: s.cfg.Instrumentation.Enabled, McpExternal: s.cfg.MCPExternal.Enabled,
		McpServers: slices.Sorted(maps.Keys(s.cfg.MCPServers)), WebAutoSettleAfter: settleAfter.String(),
	}
	// WhoIs is display-only; the configured IP mapping remains authoritative.
	output, errWhoIs := exec.CommandContext(ctx, "tailscale", "whois", "--json", metadata.ValueFromIncomingContext(ctx, "rocketclaw-principal")[0]).Output()
	if errWhoIs == nil {
		var identity struct {
			UserProfile struct{ LoginName string }
		}
		if errDecode := json.Unmarshal(output, &identity); errDecode == nil {
			view.TailscaleUser = identity.UserProfile.LoginName
		}
	}

	for _, name := range slices.Sorted(maps.Keys(s.cfg.Models)) {
		view.Models = append(view.Models, &ConfigModel{Name: name, Model: s.cfg.Models[name]})
	}

	for _, channel := range s.cfg.Slack.Channels {
		view.SlackChannels = append(view.SlackChannels, &ConfigChannel{Channel: channel.Channel, Agents: slices.Clone(channel.Agents)})
	}

	return &ListConfigResponse{Config: view}, nil
}

func (s *Server) listSkills(ctx context.Context, request *ListSkillsRequest) (*ListSkillsResponse, error) {
	if _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	agents, definitions, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web skills: %w", err)
	}

	response := &ListSkillsResponse{}

	var items []rocketcode.Skill

	if request.Agent != "" {
		agent, ok := agents.Items[request.Agent]
		if !ok {
			return response, nil
		}

		items = definitions.Available(&agent)
	} else {
		items = slices.SortedFunc(maps.Values(definitions.Items), func(a, b rocketcode.Skill) int {
			return strings.Compare(a.Name, b.Name)
		})
	}

	for _, skill := range items {
		response.Skills = append(response.Skills, &Skill{Name: skill.Name, Description: skill.Description, License: skill.License, Compatibility: skill.Compatibility, Content: skill.Content, Origin: skill.Location})
	}

	return response, nil
}

func (s *Server) listAgents(ctx context.Context, id string) (*ListAgentsResponse, error) {
	if _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	definitions, _, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web agents: %w", err)
	}

	response := &ListAgentsResponse{}

	allowed := slices.Sorted(maps.Keys(definitions.Items))

	channel, _, slack := protocol.SlackThreadTarget(id)
	if id != "" {
		if err := s.visibleConversation(ctx, id); err != nil {
			return nil, err
		}

		thread, _, err := s.sessions.Thread(id)
		if err != nil {
			return nil, fmt.Errorf("read selected conversation: %w", err)
		}

		response.CurrentAgent = thread.Agent
	}

	if slack {
		_, allowed, err = s.channels.SidebarChannelAgentChoices(ctx, channel)
	} else if strings.HasPrefix(id, "web:") {
		allowed, err = s.agentChoices(ctx, id)
	}

	if err != nil {
		return nil, fmt.Errorf("web channel choices: %w", err)
	}

	for _, name := range slices.Sorted(maps.Keys(definitions.Items)) {
		if !slices.Contains(allowed, name) {
			continue
		}

		agent := definitions.Items[name]
		response.Agents = append(response.Agents, &Agent{Name: name, Model: agent.Model, Reasoning: agent.ReasoningEffort, Description: agent.Description, Verbosity: agent.Verbosity, Prompt: agent.Prompt})
	}

	return response, nil
}

func (s *Server) agentChoices(ctx context.Context, id string) ([]string, error) {
	definitions, _, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web agents: %w", err)
	}

	choices := slices.Sorted(maps.Keys(definitions.Items))

	if channel, _, slack := protocol.SlackThreadTarget(id); slack {
		allowed, err := s.channels.ChannelAgentChoices(ctx, channel)
		if err != nil {
			return nil, fmt.Errorf("web channel choices: %w", err)
		}

		choices = slices.DeleteFunc(choices, func(name string) bool { return !slices.Contains(allowed, name) })
	} else if id != "" {
		for _, run := range cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: strings.TrimPrefix(id, "web:")}}, "") {
			job, err := s.cronjobs.LoadOneOffCronjob(run.Stem)
			if err != nil {
				continue
			}

			for _, channel := range s.cfg.Slack.Channels {
				if channel.Channel != job.TextChannel {
					continue
				}

				allowed := slices.DeleteFunc(slices.Clone(channel.Agents), func(name string) bool { return !slices.Contains(choices, name) })
				if len(allowed) > 0 {
					return allowed, nil
				}
			}
		}
	}

	return choices, nil
}

func (s *Server) createSession(ctx context.Context, request *CreateSessionRequest) (*CreateSessionResponse, error) {
	principal, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	source := request.SourceConversationId
	if source != "" && len(cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: source}}, "")) == 0 {
		return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.InvalidArgument, "source must be a recorded cron run"))
	}

	choices, err := s.agentChoices(ctx, source)
	if err != nil {
		return nil, err
	}

	if source != "" && len(choices) > 0 {
		request.Agent = choices[0]
	}

	if !slices.Contains(choices, request.Agent) {
		return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.InvalidArgument, "select a loaded agent"))
	}

	id := rand.Text()

	if source != "" {
		_, recorded, err := s.sessions.Thread(source)
		if err != nil {
			return nil, fmt.Errorf("read cron conversation: %w", err)
		}

		if !recorded {
			return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.NotFound, "cron run is not recorded"))
		}
		// CreateConversation preserves existing rows; a stable ID also survives failed syncs.
		id = "web:" + source
	}

	if err := s.backend.CreateConversation(ctx, protocol.Conversation{ID: id, Agent: request.Agent, CreatedBy: principal}); err != nil {
		return nil, fmt.Errorf("create web conversation: %w", err)
	}

	if source != "" {
		if err := s.backend.SyncConversation(ctx, source, id); err != nil {
			return nil, fmt.Errorf("sync cron conversation: %w", err)
		}
	}

	return &CreateSessionResponse{Id: id}, nil
}

func (s *Server) prompt(ctx context.Context, request *PromptRequest) (*PromptResponse, error) {
	principal, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	words := strings.Fields(request.Text)
	if len(words) > 0 && words[0] == "$stop" {
		if len(words) != 1 {
			return nil, fmt.Errorf("web stop: %w", status.Error(codes.InvalidArgument, "stop takes no arguments"))
		}

		inbound := protocol.NewInboundMessage(protocol.SourceWeb, protocol.InboundKindCancel, principal, "", true)
		inbound.ConversationID = request.Id

		inbound.Metadata = map[string]string{protocol.InboundPrincipalMetadataKey: principal}
		if err := s.backend.RunTurn(ctx, inbound); err != nil {
			return nil, fmt.Errorf("web prompt: %w", err)
		}

		return &PromptResponse{}, nil
	}

	if len(words) > 0 && words[0] == "$agent" {
		choices, err := s.agentChoices(ctx, request.Id)
		if err != nil {
			return nil, err
		}

		if len(words) == 1 {
			return &PromptResponse{PrivateText: strings.Join(choices, ", ")}, nil
		}

		if len(words) != 2 || !slices.Contains(choices, words[1]) {
			return nil, fmt.Errorf("web agent: %w", status.Error(codes.InvalidArgument, "agent is not currently allowed"))
		}

		switched, err := s.backend.SwitchConversationAgent(request.Id, words[1])
		if err != nil {
			return nil, fmt.Errorf("switch web agent: %w", err)
		}

		if !switched {
			return nil, fmt.Errorf("web agent: %w", status.Error(codes.NotFound, "conversation is not recorded"))
		}

		return &PromptResponse{PrivateText: "Agent: " + words[1]}, nil
	}

	text, delivery := request.Text, request.Delivery
	if len(words) > 0 && words[0] == "$enqueue" {
		text = strings.TrimLeftFunc(strings.TrimPrefix(strings.TrimLeftFunc(text, unicode.IsSpace), "$enqueue"), unicode.IsSpace)
		delivery = PromptDelivery_QUEUE
	}

	kind := protocol.InboundKindSteer

	switch delivery {
	case PromptDelivery_STEER:
	case PromptDelivery_QUEUE:
		kind = protocol.InboundKindEnqueue
	default:
		return nil, fmt.Errorf("web prompt: %w", status.Error(codes.InvalidArgument, "unknown prompt delivery"))
	}

	content, err := s.uploadContent(ctx, request.Id, text, request.AttachmentIds)
	if err != nil {
		return nil, err
	}

	if kind == protocol.InboundKindEnqueue {
		item := &protocol.ThreadQueueItem{
			ID: rand.Text(), Message: text, Principal: principal, Source: protocol.SourceWeb,
			Kind: protocol.InboundKindEnqueue, Content: content, StashAt: time.Now().UTC(),
		}
		if err := s.backend.StashQueueItem(ctx, request.Id, item); err != nil {
			return nil, fmt.Errorf("web prompt: %w", err)
		}

		return &PromptResponse{}, nil
	}

	inbound := protocol.NewInboundMessageFromContent(protocol.SourceWeb, kind, principal, &content, true)
	inbound.ConversationID = request.Id

	inbound.Metadata[protocol.InboundPrincipalMetadataKey] = principal

	inbound.Metadata["web_message_id"] = cmp.Or(request.MessageId, rand.Text())
	if err := s.backend.RunTurn(ctx, inbound); err != nil {
		return nil, fmt.Errorf("web prompt: %w", err)
	}

	return &PromptResponse{}, nil
}

func (s *Server) listQueue(ctx context.Context, request *ListQueueRequest) (*ListQueueResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	items, err := s.backend.QueueItems(request.Id)
	if err != nil {
		return nil, fmt.Errorf("list web queue: %w", err)
	}

	response := &ListQueueResponse{}

	for i := range items {
		input, err := s.inputEvent(ctx, request.Id, strings.Join(append([]string{items[i].Message}, items[i].Content.TextAttachments...), "\n\n"))
		if err != nil {
			return nil, err
		}

		delivery := PromptDelivery_QUEUE
		if items[i].Kind == protocol.InboundKindSteer {
			delivery = PromptDelivery_STEER
		}

		response.Items = append(response.Items, &QueueItem{Id: items[i].ID, Text: input.Text, Attachments: input.Attachments, Delivery: delivery})
	}

	return response, nil
}

func (s *Server) requireQueueItem(ctx context.Context, request *QueueItemRequest) error {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return err
	}

	if strings.TrimSpace(request.ItemId) == "" {
		return fmt.Errorf("web queue: %w", status.Error(codes.InvalidArgument, "queue item ID is required"))
	}

	return nil
}

func queueItemResponse(ok bool, err error, wrap string) (*QueueItemResponse, error) {
	if err != nil {
		return nil, fmt.Errorf("%s: %w", wrap, err)
	}

	if !ok {
		return nil, fmt.Errorf("web queue: %w", status.Error(codes.NotFound, "queue item is not recorded"))
	}

	return &QueueItemResponse{}, nil
}

func (s *Server) steerQueueItem(ctx context.Context, request *QueueItemRequest) (*QueueItemResponse, error) {
	if err := s.requireQueueItem(ctx, request); err != nil {
		return nil, err
	}

	ok, err := s.backend.PromoteQueueItem(ctx, request.Id, request.ItemId)

	return queueItemResponse(ok, err, "promote web queue item")
}

func (s *Server) removeQueueItem(ctx context.Context, request *QueueItemRequest) (*QueueItemResponse, error) {
	if err := s.requireQueueItem(ctx, request); err != nil {
		return nil, err
	}

	ok, err := s.backend.DeleteQueueItem(ctx, request.Id, request.ItemId)

	return queueItemResponse(ok, err, "remove web queue item")
}

func (s *Server) reorderQueue(ctx context.Context, request *ReorderQueueRequest) (*QueueItemResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	if err := s.backend.ReorderQueueItems(request.Id, request.ItemIds); err != nil {
		return nil, fmt.Errorf("reorder web queue: %w", err)
	}

	return &QueueItemResponse{}, nil
}

func (s *Server) visibleConversation(ctx context.Context, id string) error {
	if _, err := s.principal(ctx); err != nil {
		return err
	}

	if strings.TrimSpace(id) == "" {
		return fmt.Errorf("web queue: %w", status.Error(codes.InvalidArgument, "conversation ID is required"))
	}

	visible, err := s.humanConversation(id)
	if err != nil {
		return err
	}

	if !visible {
		return fmt.Errorf("web queue: %w", status.Error(codes.PermissionDenied, "private conversation"))
	}

	return nil
}

func (s *Server) join(request *JoinRequest, stream grpc.ServerStream) error {
	if err := s.visibleConversation(stream.Context(), request.Id); err != nil {
		return err
	}

	for event := range s.backend.Subscribe(stream.Context()) {
		message := event.Message

		var err error

		if message.ConversationID == request.Id {
			if message.ConsumedID != "" {
				var consumed *TranscriptEvent

				consumed, err = s.inputEvent(stream.Context(), request.Id, message.ConsumedText)
				if err == nil {
					consumed.MessageId = message.ConsumedID
					err = stream.SendMsg(consumed)
				}
			}

			if err == nil && message.ProgressText != "" {
				err = stream.SendMsg(&TranscriptEvent{Text: message.ProgressText, Role: "thinking", TurnId: message.TurnID})
			}

			if err == nil && (message.Text != "" || message.Complete || len(message.Attachments) > 0) {
				response := &TranscriptEvent{Text: message.Text, Role: "assistant", Complete: message.Complete, TurnId: message.TurnID}
				if len(message.Attachments) > 0 {
					history, errHistory := s.history(stream.Context(), &HistoryRequest{Id: request.Id})

					err = errHistory
					if err == nil {
						for _, item := range history.Messages {
							for _, attachment := range item.Attachments {
								if slices.ContainsFunc(message.Attachments, func(sent protocol.OutboundAttachment) bool { return sent.ID == attachment.Id }) {
									response.Attachments = append(response.Attachments, attachment)
								}
							}
						}
					}
				}

				if err == nil {
					err = stream.SendMsg(response)
				}
			}
		}

		event.Acknowledgement <- err

		if err != nil {
			return fmt.Errorf("web live event: %w", err)
		}
	}

	return nil
}

func (s *Server) principal(ctx context.Context) (string, error) {
	values := metadata.ValueFromIncomingContext(ctx, "rocketclaw-principal")
	if len(values) != 1 {
		return "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "browser IP is required"))
	}

	ip, err := netip.ParseAddr(values[0])
	if err != nil {
		return "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "invalid browser IP"))
	}

	username := s.usernames[ip]
	if username == "" {
		return "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "browser IP is not configured"))
	}

	return username, nil
}

func (s *Server) entries(ctx context.Context, id string) ([]backend.ObservedSessionEntry, error) {
	if err := s.visibleConversation(ctx, id); err != nil {
		return nil, err
	}

	entries, err := s.sessions.ObserveEntries(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "load session entries"))
	}

	return slices.DeleteFunc(entries, func(entry backend.ObservedSessionEntry) bool { return entry.Synced && entry.SourceConversationID == "" }), nil
}

type originKind string

const (
	originCron        originKind = "cron"
	originExternalMCP originKind = "external_mcp"
)

type cronRunKind string

const (
	cronScheduled cronRunKind = "scheduled"
	cronOneOff    cronRunKind = "one-off"
)

type cronRun struct {
	kind       cronRunKind
	path, stem string
	at         time.Time
}

type originPair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type cronOrigin struct {
	Agent      string      `json:"agent"`
	Kind       originKind  `json:"kind"`
	RanAt      string      `json:"ranAt"`
	RunID      string      `json:"runId"`
	RunKind    cronRunKind `json:"runKind"`
	SourcePath string      `json:"sourcePath"`
	Stem       string      `json:"stem"`
}

type externalMCPOrigin struct {
	Agent                  string       `json:"agent"`
	ExternalConversationID string       `json:"externalConversationId"`
	Kind                   originKind   `json:"kind"`
	Pairs                  []originPair `json:"pairs"`
}

func (s *Server) chatOrigin(ctx context.Context, id string, entries []backend.ObservedSessionEntry) (string, error) {
	thread, _, err := s.sessions.Thread(id)
	if err != nil {
		return "", fmt.Errorf("read origin thread: %w", err)
	}

	externalID, binding, paired, err := s.sessions.ExternalMCPSessionByConversationID(id)
	if err != nil {
		return "", fmt.Errorf("read origin external MCP binding: %w", err)
	}

	locator, cronOn := creatingCronLocator(id, thread.CreatedBy, entries)

	mcpOn := paired && binding.ManagedConversationID == id
	if mcpOn == cronOn {
		return "", nil
	}

	if mcpOn {
		pairs, err := s.startingPairs(ctx, binding.PrivateConversationID)
		if err != nil {
			return "", err
		}

		return originJSON(externalMCPOrigin{Kind: originExternalMCP, ExternalConversationID: externalID, Agent: binding.Agent, Pairs: pairs})
	}

	run, _ := parseCronRun(locator)

	producer, _, err := s.sessions.Thread(locator)
	if err != nil {
		return "", fmt.Errorf("read cron producer agent: %w", err)
	}

	return originJSON(cronOrigin{Kind: originCron, SourcePath: run.path, Stem: run.stem, RunKind: run.kind, RunID: locator, Agent: producer.Agent, RanAt: run.at.Format(time.RFC3339Nano)})
}

func originJSON(origin any) (string, error) {
	raw, err := json.Marshal(origin)
	if err != nil {
		return "", fmt.Errorf("encode chat origin: %w", err)
	}

	return string(raw), nil
}

func creatingCronLocator(id string, createdBy backend.ThreadCreator, entries []backend.ObservedSessionEntry) (string, bool) {
	if source, ok := strings.CutPrefix(id, "web:"); ok {
		if _, parsed := parseCronRun(source); parsed {
			return source, true
		}
	}

	if _, _, slack := protocol.SlackThreadTarget(id); slack && createdBy != backend.ThreadCreatedByCron {
		return "", false
	}

	for i := range entries {
		source := entries[i].SourceConversationID
		if _, ok := parseCronRun(source); ok {
			return source, true
		}
	}

	return "", false
}

func parseCronRun(source string) (cronRun, bool) {
	kind, path, ok := cronScheduled, "", false
	if rest, cut := strings.CutPrefix(source, "cron:"); cut {
		path, ok = rest, true
	} else if rest, cut := strings.CutPrefix(source, "one-off-cron:"); cut {
		kind, path, ok = cronOneOff, rest, true
	}

	end := strings.LastIndex(path, ":")

	start := strings.LastIndex(path[:max(end, 0)], ":")
	if !ok || start < 0 {
		return cronRun{}, false
	}

	at, err := time.Parse("20060102T150405.000000000Z", path[start+1:end])
	if err != nil {
		return cronRun{}, false
	}

	relative := path[:start]

	return cronRun{kind: kind, path: relative, stem: strings.TrimSuffix(strings.TrimPrefix(relative, "cron/"), ".md"), at: at}, true
}

func (s *Server) startingPairs(ctx context.Context, id string) ([]originPair, error) {
	if id == "" {
		return nil, nil
	}

	entries, err := s.sessions.ObserveEntries(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("read starting metadata pairs: %w", err)
	}

	for i := range entries {
		pairs, ok := backend.OriginPairsFromEntry(&entries[i].Entry)
		if !ok {
			continue
		}

		out := make([]originPair, 0, len(pairs))
		for _, key := range slices.Sorted(maps.Keys(pairs)) {
			out = append(out, originPair{Key: key, Value: pairs[key]})
		}

		return out, nil
	}

	return nil, nil
}
