// Package rpc adapts the retained Web protocol to Go-owned conversation storage.
//
//go:generate protoc -I ../../web/proto --go_out=. --go_opt=paths=source_relative ../../web/proto/web.proto
//go:generate sh -c "printf '// Code generated by go generate; DO NOT EDIT.\n\npackage rpc\n\nconst protoSHA256 = \"%s\"\n' $(shasum -a 256 ../../web/proto/web.proto | cut -d ' ' -f 1) > protocol.gen.go"
package rpc

import (
	"cmp"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	"github.com/Rocketable/platform/internal/rocketclaw/backend"
	"github.com/Rocketable/platform/internal/rocketclaw/config"
	"github.com/Rocketable/platform/internal/rocketclaw/frontend"
	cronfrontend "github.com/Rocketable/platform/internal/rocketclaw/frontend/cron"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
	"github.com/Rocketable/platform/internal/rocketcode"
	"github.com/openai/openai-go/v3/responses"
	"golang.org/x/sync/singleflight"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Server supplies concrete Web handlers. The host owns transport registration.
type Server struct {
	backend   frontend.Backend
	sessions  *backend.SessionService
	usernames map[netip.Addr]string
	cfg       *config.Config
	channels  ChannelAgentChoices
	cronjobs  CronJobs

	tailscaleMu    sync.Mutex
	tailscaleUsers map[netip.Addr]tailscaleUser

	searchMu    sync.Mutex
	searches    map[string]*messageSearchFlight
	searchGroup singleflight.Group
}

type messageSearchFlight struct {
	cancel  context.CancelFunc
	done    chan struct{}
	waiters int
}

type tailscaleUser struct {
	username  string
	principal string
	expires   time.Time
}

// ChannelAgentChoices supplies live policy for actions and stored facts for display.
type ChannelAgentChoices interface {
	ChannelAgentChoices(context.Context, string) ([]string, error)
	SidebarChannelAgentChoices(context.Context, string) (string, []string, error)
	SlackNames(context.Context, []string) map[string]string
	SlackTagsMatching(context.Context, string) []string
}

// CronJobs uses the process's existing Cron manager for reads and execution.
type CronJobs interface {
	Jobs() ([]cronfrontend.Job, error)
	LoadOneOffCronjob(string) (protocol.OneOffCronjob, error)
	RunOneOffCronjob(context.Context, *protocol.OneOffCronjob) (protocol.CronRunResult, error)
}

// New snapshots WebUsers from the validated startup configuration.
// The host must restrict RPC access to the trusted Web proxy: the metadata
// carries the browser IP, not an independently authenticated network peer.
func New(core frontend.Backend, sessions *backend.SessionService, cfg *config.Config, channels ChannelAgentChoices, cronjobs CronJobs) *Server {
	return &Server{backend: core, sessions: sessions, usernames: maps.Clone(cfg.WebUsers), cfg: cfg, channels: channels, cronjobs: cronjobs}
}

// ListSessionEntries returns ordered entry identifiers and metadata.
func (s *Server) ListSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*ListSessionEntriesResponse, error) {
	entries, err := s.entries(ctx, request.Id)
	if err != nil {
		return nil, err
	}

	response := &ListSessionEntriesResponse{}

	for i := range entries {
		entry := &entries[i]
		response.Entries = append(response.Entries, &SessionEntryMeta{
			Id: entry.ID, Type: entry.Entry.Type, Timestamp: entry.Entry.Timestamp.Format(time.RFC3339Nano),
		})
	}

	return response, nil
}

// LoadSessionEntries returns stored entry values as JSON, preserving int64 IDs.
func (s *Server) LoadSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*LoadSessionEntriesResponse, error) {
	entries, err := s.entries(ctx, request.Id)
	if err != nil {
		return nil, err
	}

	response := &LoadSessionEntriesResponse{}

	for i := range entries {
		entry := &entries[i]

		data, err := json.Marshal(entry.Entry)
		if err != nil {
			return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "encode session entry"))
		}

		response.Entries = append(response.Entries, &SessionEntryData{Id: entry.ID, Json: string(data)})
	}

	return response, nil
}

// DeleteSessionEntries deletes entries only; conversation and goal records remain.
func (s *Server) DeleteSessionEntries(ctx context.Context, request *SessionEntriesRequest) (*DeleteSessionEntriesResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	deleted, err := s.sessions.DeleteSession(ctx, request.Id)
	if err != nil {
		return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "delete session entries"))
	}

	return &DeleteSessionEntriesResponse{Deleted: deleted}, nil
}

func (s *Server) listSessions(stream grpc.ServerStream) error {
	ctx := stream.Context()

	owner, _, err := s.principal(ctx)
	if err != nil {
		return err
	}

	complete := true
	metadataByChannel := make(map[string]*Session)

	settleAfter, err := s.cfg.Web.SettleAfter()
	if err != nil {
		return fmt.Errorf("web session inactivity period: %w", err)
	}

	var cronOrigins map[string]string

	for row, err := range s.sessions.SidebarSessions(ctx, time.Now().Add(-settleAfter)) {
		if err != nil {
			return err
		}

		// Read origins after the row snapshot: a first cron sync must not add
		// a listed chat newer than its origin facts.
		if cronOrigins == nil {
			cronOrigins = make(map[string]string)

			for facts, err := range s.sessions.ChatOriginFacts(ctx, "") {
				if err != nil {
					return err
				}

				origin, _ := decideOrigin(&facts)
				if cron, ok := origin.(cronOrigin); ok {
					cronOrigins[facts.ConversationID] = cron.Stem
				}
			}
		}

		conversation := row.Conversation
		complete = complete && row.Summary != nil

		allChoices, loaded := metadataByChannel[""]
		if !loaded {
			choices, err := s.agentChoices(ctx, "")
			if err != nil {
				return err
			}

			allChoices = &Session{AllowedAgents: choices}
			metadataByChannel[""] = allChoices
		}

		channel, _, slack := protocol.SlackThreadTarget(conversation.ID)
		if !slack {
			channel = ""
		}

		channelMetadata, loaded := metadataByChannel[channel]
		if !loaded {
			name, allowed, err := s.channels.SidebarChannelAgentChoices(ctx, channel)
			if err != nil {
				return fmt.Errorf("web channel choices: %w", err)
			}

			choices := slices.DeleteFunc(slices.Clone(allChoices.AllowedAgents), func(name string) bool { return !slices.Contains(allowed, name) })
			channelMetadata = &Session{Title: name, AllowedAgents: choices}
			metadataByChannel[channel] = channelMetadata
		}

		cronName, cronOn := cronOrigins[conversation.ID]

		session := &Session{Id: conversation.ID, Title: channelMetadata.Title, Agent: conversation.Agent, AllowedAgents: channelMetadata.AllowedAgents, Settled: conversation.Settled, Running: row.Running, Pinned: row.Pinned, Name: row.Name, ForkedFrom: row.ForkedFrom, Tags: row.Tags, Cron: cronOn, CronName: cronName}
		if row.SnoozedUntil != nil {
			session.SnoozedUntil = row.SnoozedUntil.UTC().Format(time.RFC3339Nano)
		}

		if strings.HasPrefix(conversation.ID, "web:") {
			session.AllowedAgents, err = s.agentChoices(ctx, conversation.ID)
			if err != nil {
				return err
			}
		}

		if summary := row.Summary; summary != nil {
			session.Preview = summary.LastMessage
			if !summary.LastUpdated.IsZero() {
				session.UpdatedAt = summary.LastUpdated.Format(time.RFC3339Nano)
			}
		}

		if err := stream.SendMsg(&ListSessionsResponse{Sessions: []*Session{session}, Owner: owner, SummariesComplete: row.Summary != nil}); err != nil {
			return fmt.Errorf("send web session: %w", err)
		}
	}

	if err := stream.SendMsg(&ListSessionsResponse{Owner: owner, UpstreamSuccess: true, SummariesComplete: complete}); err != nil {
		return fmt.Errorf("send web session completion: %w", err)
	}

	return nil
}

// historyRevision is a stateless inventory, not an event-log cursor. The database
// returns readable payloads only for entries whose fingerprints have changed.
// A limited view follows entries from From onward; Oldest changes only when
// history is cleared, which restarts the view.
type historyRevision = backend.HistoryInventory

func (s *Server) history(ctx context.Context, request *HistoryRequest) (*HistoryResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	// Cron producer history is readable without granting chat or mutation access.
	cronTrace := strings.HasPrefix(request.Id, "cron:") || strings.HasPrefix(request.Id, "one-off-cron:")
	if !cronTrace {
		if err := s.visibleConversation(ctx, request.Id); err != nil {
			return nil, err
		}
	}

	var previous historyRevision

	data, errToken := base64.RawURLEncoding.DecodeString(request.Revision)
	if errToken != nil || json.Unmarshal(data, &previous) != nil || previous.ConversationID != request.Id || previous.Source != request.SourceConversationId {
		previous = historyRevision{}
	}

	view, err := s.sessions.ObserveHistory(ctx, request.Id, request.SourceConversationId, request.GetFrom(), request.GetBefore(), int(request.GetLimit()), previous)
	if err != nil {
		return nil, fmt.Errorf("read web history page: %w", err)
	}

	if view.Reset {
		previous = historyRevision{}
	}

	entries, from, oldest := view.Entries, view.Inventory.From, view.Inventory.Oldest
	response := &HistoryResponse{Reset_: view.Reset, Start: from, More: from > oldest, RevertEligible: view.Eligible, RevertMessageId: view.Inventory.Marker, CanUndo: view.Predecessor != "", Delegations: view.Delegations}

	if !cronTrace && request.GetBefore() == 0 {
		response.Origin, err = s.chatOrigin(ctx, request.Id)
		if err != nil {
			return nil, err
		}
	}

	root, err := os.OpenRoot(s.cfg.Workspace)
	if err != nil {
		return nil, fmt.Errorf("open attachment workspace: %w", err)
	}

	defer func() { _ = root.Close() }()

	calls := make(map[string]map[string]string)
	current := view.Inventory
	current.Entries = make(map[string]string)

	for i := range entries {
		entry := &entries[i]
		if entry.Synced && entry.SourceConversationID == "" && !cronTrace {
			continue
		}

		producer := cmp.Or(entry.SourceConversationID, request.Id)

		if calls[producer] == nil {
			calls[producer] = make(map[string]string)
		}

		if request.GetSourceConversationId() != "" && entry.SourceConversationID != request.GetSourceConversationId() {
			continue
		}

		current.Entries[entry.Key] = entry.Revision
		response.EntryKeys = append(response.EntryKeys, entry.Key)
		response.Running = response.Running || entry.Active

		response.Terminal = string(entry.Terminal)
		if previous.Entries[entry.Key] == entry.Revision {
			continue
		}

		response.ReplacedKeys = append(response.ReplacedKeys, entry.Key)

		messages, err := s.transcriptEntry(ctx, root, entry, request.Id, calls[producer])
		if err != nil {
			return nil, err
		}

		response.Messages = append(response.Messages, messages...)
	}

	if request.GetBefore() > 0 {
		return response, nil // Settled pages are read once, not followed.
	}

	for _, key := range slices.Sorted(maps.Keys(previous.Entries)) {
		if _, exists := current.Entries[key]; !exists {
			response.RemovedKeys = append(response.RemovedKeys, key)
		}
	}

	data, _ = json.Marshal(current)
	response.Revision = base64.RawURLEncoding.EncodeToString(data)

	return response, nil
}

func (s *Server) transcriptEntry(ctx context.Context, root *os.Root, entry *backend.ObservedSessionEntry, conversationID string, calls map[string]string) ([]*TranscriptEvent, error) {
	items, err := rocketcode.ReplayInputToParams(entry.Entry.ReplayInput)
	if err != nil {
		return nil, fmt.Errorf("decode web history: %w", err)
	}

	producer := cmp.Or(entry.SourceConversationID, conversationID)
	// Ponytail: replay/progress matching scans each turn; index identities if large turns make this costly.
	progress := rocketcode.PublicProgressFromTrace(entry.Entry.OutputTrace)
	replayText := make(map[string]bool)
	replayResults := make(map[string]bool)
	replayCalls := make(map[string]bool)

	hostParents, hostCalls := hostCallsByParent(entry.Entry.OutputTrace)

	var messages []*TranscriptEvent

	for i := range items {
		var identity struct {
			ID      string          `json:"id"`
			Type    string          `json:"type"`
			Role    string          `json:"role"`
			Status  string          `json:"status"`
			CallID  string          `json:"call_id"`
			Content json.RawMessage `json:"content"`
		}
		if err := json.Unmarshal(entry.Entry.ReplayInput[i], &identity); err != nil {
			return nil, fmt.Errorf("decode history identity: %w", err)
		}

		if identity.Role == "assistant" && identity.ID != "" {
			replayText[identity.ID] = true // Even an empty authoritative item replaces its partial.
		}

		if identity.Type == "function_call_output" {
			replayResults[identity.CallID] = true
		}

		if identity.Type == "function_call" {
			replayCalls[identity.CallID] = true
		}

		callProgress := slices.IndexFunc(progress, func(item rocketcode.PublicProgress) bool {
			return item.Kind != rocketcode.PublicProgressText && item.ID == identity.CallID
		})
		if identity.Type == "function_call_output" && callProgress >= 0 && (progress[callProgress].State == rocketcode.PublicProgressBlocked ||
			progress[callProgress].Kind == rocketcode.PublicProgressDelegation && slices.Contains([]rocketcode.PublicProgressState{rocketcode.PublicProgressFailed, rocketcode.PublicProgressStopped}, progress[callProgress].State)) {
			continue // Unapproved delegation/reviewer replay stays stored, never projected (including attachments).
		}

		attachments, err := s.sessions.ReplayAttachments(ctx, producer, root, entry.Entry.ReplayInput[i], calls)
		if err != nil {
			return nil, fmt.Errorf("project history attachments: %w", err)
		}

		event, err := historyEvent(&items[i], entry.Entry.ReplayInput[i])
		if err != nil {
			return nil, err
		}

		if event == nil {
			continue
		}

		for j := range attachments {
			event.Attachments = append(event.Attachments, attachmentMetadata(producer, &attachments[j]))
		}

		if event.Role == "user" {
			event, err = s.savedInputEvent(ctx, producer, event)
			if err != nil {
				return nil, err
			}
		}

		event.attribute(entry.Entry.AttributionAt(i), producer, conversationID)
		event.EntryKey, event.TurnId = entry.Key, entry.Entry.TurnID
		event.ItemId = fmt.Sprintf("%s:%d", entry.Key, i)

		if event.ToolCallId != "" {
			event.ParentId = entry.Key
		}

		if callProgress >= 0 {
			event.publicProgress(&progress[callProgress], entry, producer)

			if identity.Type == "function_call_output" {
				event.ItemId += ":outcome"
			}
		}

		event.linkReview(producer)

		if entry.ID != 0 {
			event.MessageId = fmt.Sprintf("%d:%d", entry.ID, i)
		}

		texts, err := event.publicText(identity.Content, identity.ID, identity.Status, progress, entry, producer)
		if err != nil {
			return nil, err
		}

		messages = append(messages, texts...)

		if identity.Type == "function_call" {
			hosted, err := s.hostCallEvents(ctx, root, entry, producer, conversationID, calls, hostCalls[identity.CallID], i)
			if err != nil {
				return nil, err
			}

			messages = append(messages, hosted...)

			delete(hostCalls, identity.CallID)
		}
	}
	// A running turn records host calls before its execute call reaches replay.
	for _, parent := range hostParents {
		hosted, err := s.hostCallEvents(ctx, root, entry, producer, conversationID, calls, hostCalls[parent], len(items))
		if err != nil {
			return nil, err
		}

		messages = append(messages, hosted...)
	}

	messages = fallbackProgress(entry, progress, replayText, replayResults, replayCalls, conversationID, messages)

	return messages, nil
}

// hostCallsByParent groups the trace's execute-script calls by their execute call, in trace order.
func hostCallsByParent(trace []json.RawMessage) (parents []string, calls map[string][]json.RawMessage) {
	calls = make(map[string][]json.RawMessage)

	for _, raw := range trace {
		var host struct {
			Type         string `json:"type"`
			ParentCallID string `json:"parent_call_id"`
		}
		if json.Unmarshal(raw, &host) != nil || host.ParentCallID == "" || host.Type != "function_call" && host.Type != "function_call_output" {
			continue
		}

		if _, seen := calls[host.ParentCallID]; !seen {
			parents = append(parents, host.ParentCallID)
		}

		calls[host.ParentCallID] = append(calls[host.ParentCallID], raw)
	}

	return parents, calls
}

// hostCallEvents projects calls made inside one execute script, after that script's call.
func (s *Server) hostCallEvents(ctx context.Context, root *os.Root, entry *backend.ObservedSessionEntry, producer, conversationID string, calls map[string]string, raws []json.RawMessage, index int) ([]*TranscriptEvent, error) {
	var events []*TranscriptEvent

	for k, raw := range raws {
		attachments, err := s.sessions.ReplayAttachments(ctx, producer, root, raw, calls)
		if err != nil {
			return nil, fmt.Errorf("project host call attachments: %w", err)
		}

		event, err := historyEvent(&responses.ResponseInputItemUnionParam{}, raw)
		if err != nil {
			return nil, err
		}

		if event == nil {
			continue
		}

		for j := range attachments {
			event.Attachments = append(event.Attachments, attachmentMetadata(producer, &attachments[j]))
		}

		event.attribute(entry.Entry.AttributionAt(index), producer, conversationID)
		event.EntryKey, event.TurnId, event.ParentId = entry.Key, entry.Entry.TurnID, entry.Key
		event.ItemId = fmt.Sprintf("%s:%d:host:%d", entry.Key, index, k)

		if entry.ID != 0 {
			event.MessageId = fmt.Sprintf("%d:%d:host:%d", entry.ID, index, k)
		}

		events = append(events, event)
	}

	return events, nil
}

// publicText reconciles native content parts and locally flattened provider text.
func (e *TranscriptEvent) publicText(content json.RawMessage, id, messageStatus string, progress []rocketcode.PublicProgress, entry *backend.ObservedSessionEntry, producer string) ([]*TranscriptEvent, error) {
	if e.Role != "assistant" || id == "" || len(content) == 0 {
		return []*TranscriptEvent{e}, nil
	}

	if content[0] == '"' {
		if overlap := slices.IndexFunc(progress, func(item rocketcode.PublicProgress) bool {
			index := strings.LastIndexByte(item.ID, '/')
			return item.Kind == rocketcode.PublicProgressText && index >= 0 && item.ID[:index] == id
		}); overlap >= 0 {
			e.publicProgress(&progress[overlap], entry, producer)
		}

		return []*TranscriptEvent{e}, nil
	}

	if content[0] != '[' {
		return []*TranscriptEvent{e}, nil
	}

	var parts []struct{ Type, Text string }
	if err := json.Unmarshal(content, &parts); err != nil {
		return nil, fmt.Errorf("decode history output text: %w", err)
	}

	var messages []*TranscriptEvent

	for index, part := range parts {
		if part.Type != "output_text" || strings.TrimSpace(part.Text) == "" {
			continue
		}

		text := proto.CloneOf(e)
		text.Text = part.Text
		itemID := fmt.Sprintf("%s/%d", id, index)

		text.ItemId = entry.Key + ":" + itemID
		if overlap := slices.IndexFunc(progress, func(item rocketcode.PublicProgress) bool {
			return item.Kind == rocketcode.PublicProgressText && item.ID == itemID
		}); overlap >= 0 {
			text.publicProgress(&progress[overlap], entry, producer)

			if messageStatus == "completed" {
				text.State, text.Complete = "completed", true
			}
		}

		messages = append(messages, text)
	}

	return messages, nil
}

// fallbackProgress merges missing observations before their next surviving public identity.
func fallbackProgress(entry *backend.ObservedSessionEntry, progress []rocketcode.PublicProgress, replayText, replayResults, replayCalls map[string]bool, conversationID string, messages []*TranscriptEvent) []*TranscriptEvent {
	producer := cmp.Or(entry.SourceConversationID, conversationID)

	for i := range progress {
		item := &progress[i]

		switch {
		case item.Kind == rocketcode.PublicProgressText:
			id := item.ID
			if index := strings.LastIndexByte(id, '/'); index >= 0 {
				id = id[:index]
			}

			if replayText[id] || strings.TrimSpace(item.Text) == "" {
				continue
			}
		case replayResults[item.ID] && item.State != rocketcode.PublicProgressBlocked &&
			(item.Kind != rocketcode.PublicProgressDelegation || !slices.Contains([]rocketcode.PublicProgressState{rocketcode.PublicProgressFailed, rocketcode.PublicProgressStopped}, item.State)):
			continue
		case replayCalls[item.ID] && (item.State == rocketcode.PublicProgressWorking || item.State == rocketcode.PublicProgressReview):
			continue // The existing call disclosure already carries this pending state.
		}

		event := &TranscriptEvent{Role: "tool", Text: string(item.State), EntryKey: entry.Key, TurnId: entry.Entry.TurnID}
		if item.Kind == rocketcode.PublicProgressText {
			event.Role, event.Text = "assistant", item.Text
		} else if item.Kind == rocketcode.PublicProgressTool && item.Text != "" {
			event.Text = item.Text
		}

		event.attribute(entry.Entry.AttributionAt(len(entry.Entry.ReplayInput)), producer, conversationID)
		event.publicProgress(item, entry, producer)

		if item.Kind != rocketcode.PublicProgressText {
			if item.Kind == rocketcode.PublicProgressDelegation || item.Text == "" {
				event.Text = event.State
			}

			event.ItemId += ":outcome"
		}

		position := len(messages)
		// Ponytail: O(progress² × rows) anchoring keeps no extra index; index
		// identities if long compacted turns make this scan expensive.
		for j := i + 1; j < len(progress); j++ {
			id := entry.Key + ":" + progress[j].ParentID + "/" + progress[j].ID

			if anchor := slices.IndexFunc(messages, func(message *TranscriptEvent) bool {
				return message.ItemId == id || message.ItemId == id+":outcome"
			}); anchor >= 0 {
				position = anchor
				break
			}
		}

		messages = slices.Insert(messages, position, event)
	}

	return messages
}

// publicProgress supplies display identity and safe attribution, never command identity. A task
// call's subagent and a call's permission review are direct children of producer, the history
// that holds the call.
func (e *TranscriptEvent) publicProgress(item *rocketcode.PublicProgress, entry *backend.ObservedSessionEntry, producer string) {
	e.ParentId = entry.Key + ":" + item.ParentID
	e.ItemId = e.ParentId + "/" + item.ID

	e.State = string(item.State)
	if entry.Terminal != "" && (item.State == rocketcode.PublicProgressWorking || item.State == rocketcode.PublicProgressReview) {
		e.State = string(entry.Terminal)
	}

	if item.SubagentKey != "" {
		e.Delegation = producer + item.SubagentKey[strings.LastIndexByte(item.SubagentKey, '/'):]
	}

	e.Complete = e.State != "working" && e.State != "review"
	if item.Kind == rocketcode.PublicProgressText {
		e.Complete = e.State == "completed"
	} else {
		e.ToolCallId = item.ID
	}

	if e.Agent != item.Agent || e.Model != item.Model {
		e.ReasoningEffort = nil // Root settings do not describe a delegated producer.
	}

	e.Agent, e.Model = item.Agent, item.Model
}

// linkReview names, on the row of a call producer made, the Delegation History its automatic
// permission reviews save to. The Web links it only while the response's delegations list it,
// which also covers a review a background script saves after its row was sent.
func (e *TranscriptEvent) linkReview(producer string) {
	if e.ToolName != "" {
		e.Review = producer + "/" + rocketcode.ReviewKey(e.TurnId, e.ToolCallId)
	}
}

func (e *TranscriptEvent) attribute(snapshot rocketcode.ReplayAttribution, source, destination string) {
	e.Agent, e.Model, e.ReasoningEffort = snapshot.Agent, snapshot.Model, snapshot.ReasoningEffort
	e.Origin = "canonical"

	_, cron := parseCronRun(source)
	if source != destination || cron {
		e.Origin = "sandboxed"
	}
}

// savedInputEvent projects a saved input of producer with its saved metadata. A system input's
// ID lists the jobs whose Completion Notes it delivers.
func (s *Server) savedInputEvent(ctx context.Context, producer string, saved *TranscriptEvent) (*TranscriptEvent, error) {
	event, err := s.inputEvent(ctx, producer, saved.Text)
	if err != nil {
		return nil, err
	}

	event.Header, event.InputId, event.Principal = saved.Header, saved.InputId, saved.Principal
	if event.InputId == "" || event.Header != "[System]" && !strings.HasPrefix(event.Header, "[System ") {
		return event, nil
	}

	notes, err := s.backend.CompletionNotes(ctx, producer, strings.Fields(event.InputId))
	if err != nil {
		return nil, fmt.Errorf("read web completion notes: %w", err)
	}

	event.CompletionNotes = backgroundJobs(notes)

	return event, nil
}

func (s *Server) inputEvent(ctx context.Context, id, text string) (*TranscriptEvent, error) {
	var attachments []*Attachment

	for word := range strings.FieldsSeq(text) {
		if attachmentID, ok := strings.CutPrefix(word, "attachment:"); ok {
			attachment, err := s.sessions.AttachmentMetadata(ctx, id, attachmentID, true)
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}

			if err != nil {
				return nil, fmt.Errorf("load input attachment metadata: %w", err)
			}

			attachments = append(attachments, attachmentMetadata(id, &attachment))
		}
	}

	for _, file := range slices.Backward(attachments) {
		reference := fmt.Sprintf("attachment:%s %q (workspace path %q)", file.Id, file.Name, filepath.Join("artifacts", "uploads", file.Id, file.Name))
		if text == reference {
			text = ""
		} else {
			text = strings.TrimSuffix(text, "\n\n"+reference)
		}
	}

	return &TranscriptEvent{Role: "user", Text: text, Attachments: attachments}, nil
}

func historyEvent(item *responses.ResponseInputItemUnionParam, raw json.RawMessage) (*TranscriptEvent, error) {
	var kind struct {
		Type      string `json:"type"`
		Name      string `json:"name"`
		CallID    string `json:"call_id"`
		Arguments string `json:"arguments"`
		Output    string `json:"output"`
		Summary   []struct {
			Text string `json:"text"`
		} `json:"summary"`
	}
	if err := json.Unmarshal(raw, &kind); err != nil {
		return nil, fmt.Errorf("decode web history item: %w", err)
	}

	switch kind.Type {
	case "reasoning":
		parts := make([]string, 0, len(kind.Summary))
		for _, part := range kind.Summary {
			if text := strings.TrimSpace(part.Text); text != "" {
				parts = append(parts, text)
			}
		}

		text := strings.Join(parts, "\n")
		if text == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "thinking", Text: text, Complete: true}, nil
	case "function_call":
		text := strings.TrimSpace(kind.Name)
		if kind.Name == "rocketclaw_attach_files_to_response" {
			kind.Arguments = ""
		}

		if kind.Arguments != "" {
			if text != "" {
				text += "\n"
			}

			text += kind.Arguments
		}

		if strings.TrimSpace(text) == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "tool", Text: text, Complete: true, ToolCallId: kind.CallID, ToolName: kind.Name}, nil
	case "function_call_output":
		if strings.TrimSpace(kind.Output) == "" {
			return nil, nil
		}

		return &TranscriptEvent{Role: "tool", Text: kind.Output, Complete: true, ToolCallId: kind.CallID}, nil
	}

	role, text, ok, err := backend.ReplayInputMessageRoleText(item, raw)
	if err != nil {
		return nil, fmt.Errorf("project web history: %w", err)
	}

	if !ok || strings.TrimSpace(text) == "" {
		return nil, nil
	}

	header, inputID := "", ""
	if item.OfMessage != nil && (role == "user" || role == "developer") {
		header, _ = item.OfMessage.ExtraFields()["prompt_header"].(string)
		inputID, _ = item.OfMessage.ExtraFields()["input_id"].(string)
	}

	return &TranscriptEvent{Role: role, Text: text, Header: header, Principal: headerPrincipal(header), InputId: inputID, Complete: true}, nil
}

// headerPrincipal reads top-level attributes from backend/bridge.go's provenanceHeader grammar.
func headerPrincipal(header string) string {
	inside, ok := strings.CutPrefix(header, "[")
	if !ok || !strings.HasSuffix(inside, "]") {
		return ""
	}

	_, attributes, _ := strings.Cut(strings.TrimSuffix(inside, "]"), " ")
	for attributes != "" {
		name, value, ok := strings.Cut(attributes, "=")
		if !ok {
			return ""
		}

		if strings.HasPrefix(value, `"`) {
			quoted, err := strconv.QuotedPrefix(value)
			if err != nil {
				return ""
			}

			attributes = value[len(quoted):]
			if attributes != "" && !strings.HasPrefix(attributes, " ") {
				return ""
			}

			if name == "principal" {
				principal, err := strconv.Unquote(quoted)
				if err != nil {
					return ""
				}

				return principal
			}
		} else {
			_, attributes, _ = strings.Cut(value, " ")
		}

		attributes = strings.TrimPrefix(attributes, " ")
	}

	return ""
}

func (s *Server) humanConversation(id string) (bool, error) {
	// These are the private producer locators minted by frontend/cron/manager.go.
	if strings.HasPrefix(id, "cron:") || strings.HasPrefix(id, "one-off-cron:") {
		return false, nil
	}

	_, pair, recorded, err := s.sessions.ExternalMCPSessionByConversationID(id)
	if err != nil {
		return false, fmt.Errorf("resolve web conversation visibility: %w", err)
	}

	return !recorded || pair.PrivateConversationID != id, nil
}

func (s *Server) listCronJobs(ctx context.Context) (*ListCronJobsResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	jobs, err := s.cronjobs.Jobs()
	if err != nil {
		return nil, fmt.Errorf("list web cron jobs: %w", err)
	}

	response := &ListCronJobsResponse{}

	for _, job := range jobs {
		row := &CronJob{Stem: strings.TrimSuffix(strings.TrimPrefix(job.RelativePath, "cron/"), ".md"), Schedule: strings.Join(job.Schedules, ", "), Body: job.Body, Agent: job.Agent, Channel: job.TextChannel, Origin: job.RelativePath}
		for _, at := range job.Upcoming {
			row.Upcoming = append(row.Upcoming, at.Format(time.RFC3339Nano))
		}

		if len(row.Upcoming) > 0 {
			row.NextRun = row.Upcoming[0]
		}

		response.Jobs = append(response.Jobs, row)
	}

	conversations, err := s.backend.ListConversations(ctx)
	if err != nil {
		return nil, fmt.Errorf("list cron history destinations: %w", err)
	}

	var (
		runs       []*CronJob
		executions []*CronJob
	)

	delivered := map[string]bool{}

	for _, conversation := range conversations {
		visible, err := s.humanConversation(conversation.ID)
		if err != nil {
			return nil, err
		}

		if !visible {
			// Private cron records contribute timing only, never replay content.
			if strings.HasPrefix(conversation.ID, "cron:") || strings.HasPrefix(conversation.ID, "one-off-cron:") {
				entries, err := s.sessions.ObserveEntries(ctx, conversation.ID)
				if err != nil {
					return nil, fmt.Errorf("read cron execution: %w", err)
				}

				if len(entries) > 0 {
					executions = append(executions, cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: conversation.ID}}, "")...)
				}
			}

			continue
		}

		entries, err := s.sessions.ObserveEntries(ctx, conversation.ID)
		if err != nil {
			return nil, fmt.Errorf("read cron history provenance: %w", err)
		}

		for _, run := range cronHistory(entries, conversation.ID) {
			delivered[run.Origin] = true
			runs = append(runs, run)
		}
	}

	for _, run := range executions {
		if !delivered[run.Origin] {
			runs = append(runs, run)
		}
	}

	slices.SortFunc(runs, func(a, b *CronJob) int {
		return cmp.Or(cmp.Compare(b.LastRun, a.LastRun), cmp.Compare(a.NextRun, b.NextRun), cmp.Compare(a.Origin, b.Origin))
	})
	response.Jobs = append(response.Jobs, runs...)

	return response, nil
}

func cronHistory(entries []backend.ObservedSessionEntry, destination string) []*CronJob {
	var runs []*CronJob

	seen := map[string]bool{}

	for i := range entries {
		source := entries[i].SourceConversationID
		if seen[source] {
			continue
		}

		run, ok := parseCronRun(source)
		if !ok {
			continue
		}

		seen[source] = true
		runs = append(runs, &CronJob{Stem: run.stem, Status: "ran", LastRun: run.at.Format("2006-01-02T15:04:05.000000000Z"), NextRun: destination, Origin: source})
	}

	return runs
}

func (s *Server) runCronJob(ctx context.Context, request *RunCronJobRequest) (*RunCronJobResponse, error) {
	principal, _, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	job, err := s.cronjobs.LoadOneOffCronjob(request.Stem)
	if err != nil {
		return nil, fmt.Errorf("load web cron job: %w", err)
	}

	id := rand.Text()
	if err := s.backend.CreateConversation(ctx, protocol.Conversation{ID: id, Agent: job.Agent, CreatedBy: principal}); err != nil {
		return nil, fmt.Errorf("create web cron conversation: %w", err)
	}

	job.ConversationID = id
	// The response has to name the session before the private run finishes, so the browser can open it.
	go func() {
		if _, err := s.cronjobs.RunOneOffCronjob(context.WithoutCancel(ctx), &job); err != nil {
			slog.Error("run web cron job", "stem", request.Stem, "id", id, "error", err)
		}
	}()

	return &RunCronJobResponse{Id: id}, nil
}

func (s *Server) settleSession(ctx context.Context, request *SettleSessionRequest) (*SettleSessionResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	updated, err := s.sessions.SetConversationSettled(ctx, request.Id, request.Settled)
	if err != nil {
		return nil, fmt.Errorf("settle web conversation: %w", err)
	}

	if !updated {
		return nil, fmt.Errorf("settle web conversation: %w", status.Error(codes.NotFound, "conversation is not recorded"))
	}

	return &SettleSessionResponse{}, nil
}

func (s *Server) updateSession(ctx context.Context, request *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	if request.Name != nil {
		if strings.ContainsRune(*request.Name, '\x00') {
			return nil, fmt.Errorf("update web conversation: %w", status.Error(codes.InvalidArgument, "name cannot contain a null character"))
		}

		request.Name = new(strings.TrimSpace(*request.Name))
	}

	var snoozedUntil *time.Time

	if request.SnoozedUntil != nil {
		until, err := time.Parse(time.RFC3339Nano, *request.SnoozedUntil)
		if err != nil || !until.After(time.Now()) {
			return nil, fmt.Errorf("update web conversation: %w", status.Error(codes.InvalidArgument, "snooze time must be a future RFC3339 timestamp"))
		}

		snoozedUntil = &until
	}

	updated, err := s.sessions.UpdateConversationDetails(ctx, request.Id, request.Pinned, request.Name, snoozedUntil)
	if err != nil {
		return nil, fmt.Errorf("update web conversation: %w", err)
	}

	if !updated {
		return nil, fmt.Errorf("update web conversation: %w", status.Error(codes.NotFound, "conversation is not recorded"))
	}

	return &UpdateSessionResponse{}, nil
}

func (s *Server) listConfig(ctx context.Context) (*ListConfigResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	settleAfter, err := s.cfg.Web.SettleAfter()
	if err != nil {
		return nil, fmt.Errorf("web config inactivity period: %w", err)
	}

	// This is the retained UI's allowlist, not serialization of the config.
	view := &ConfigView{
		Workspace: s.cfg.Workspace, Overlays: slices.Clone(s.cfg.Overlays),
		LoggingLevel: s.cfg.Logging.Level, AutoApproverModel: s.cfg.AutoApproverModel,
		InstrumentationEnabled: s.cfg.Instrumentation.Enabled, McpExternal: s.cfg.MCPExternal.Enabled,
		McpServers: slices.Sorted(maps.Keys(s.cfg.MCPServers)), WebAutoSettleAfter: settleAfter.String(),
	}
	ip := netip.MustParseAddr(metadata.ValueFromIncomingContext(ctx, "rocketclaw-principal")[0])

	username, _, errWhoIs := s.tailscaleUsername(ctx, ip)
	if errWhoIs == nil {
		view.TailscaleUser = username
	}

	for _, name := range slices.Sorted(maps.Keys(s.cfg.Models)) {
		view.Models = append(view.Models, &ConfigModel{Name: name, Model: s.cfg.Models[name]})
	}

	for _, channel := range s.cfg.Slack.Channels {
		view.SlackChannels = append(view.SlackChannels, &ConfigChannel{Channel: channel.Channel, Agents: slices.Clone(channel.Agents)})
	}

	return &ListConfigResponse{Config: view}, nil
}

// listWorkflows lists the saved workflows for the web $workflow picker.
func (s *Server) listWorkflows(ctx context.Context) (*ListWorkflowsResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	descriptions, err := s.backend.WorkflowDescriptions()
	if err != nil {
		return nil, fmt.Errorf("list web workflows: %w", err)
	}

	response := &ListWorkflowsResponse{}
	for _, description := range descriptions {
		response.Workflows = append(response.Workflows, &Workflow{Name: description.Name, Description: description.Description})
	}

	return response, nil
}

func (s *Server) listSkills(ctx context.Context, request *ListSkillsRequest) (*ListSkillsResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	agents, definitions, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web skills: %w", err)
	}

	response := &ListSkillsResponse{}

	var items []rocketcode.Skill

	if request.Agent != "" {
		agent, ok := agents.Items[request.Agent]
		if !ok {
			return response, nil
		}

		items = definitions.Available(&agent)
	} else {
		items = slices.SortedFunc(maps.Values(definitions.Items), func(a, b rocketcode.Skill) int {
			return strings.Compare(a.Name, b.Name)
		})
	}

	for _, skill := range items {
		response.Skills = append(response.Skills, &Skill{Name: skill.Name, Description: skill.Description, License: skill.License, Compatibility: skill.Compatibility, Content: skill.Content, Origin: skill.Location})
	}

	return response, nil
}

func (s *Server) listAgents(ctx context.Context, id string) (*ListAgentsResponse, error) {
	if _, _, err := s.principal(ctx); err != nil {
		return nil, err
	}

	definitions, _, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web agents: %w", err)
	}

	response := &ListAgentsResponse{}

	allowed := slices.Sorted(maps.Keys(definitions.Items))

	channel, _, slack := protocol.SlackThreadTarget(id)
	if id != "" {
		if err := s.visibleConversation(ctx, id); err != nil {
			return nil, err
		}

		thread, _, err := s.sessions.Thread(id)
		if err != nil {
			return nil, fmt.Errorf("read selected conversation: %w", err)
		}

		response.CurrentAgent = thread.Agent
	}

	if slack {
		_, allowed, err = s.channels.SidebarChannelAgentChoices(ctx, channel)
	} else if strings.HasPrefix(id, "web:") {
		allowed, err = s.agentChoices(ctx, id)
	}

	if err != nil {
		return nil, fmt.Errorf("web channel choices: %w", err)
	}

	// Keep the allowed order: Slack channels list their default agent first.
	for _, name := range allowed {
		agent, ok := definitions.Items[name]
		if !ok {
			continue
		}

		response.Agents = append(response.Agents, &Agent{Name: name, Model: agent.Model, Reasoning: agent.ReasoningEffort, Description: agent.Description, Verbosity: agent.Verbosity, Prompt: agent.Prompt})
	}

	return response, nil
}

func (s *Server) agentChoices(ctx context.Context, id string) ([]string, error) {
	definitions, _, err := backend.LoadRuntimeDefinitions(s.cfg, s.cfg.RuntimeDirName())
	if err != nil {
		return nil, fmt.Errorf("load web agents: %w", err)
	}

	choices := slices.Sorted(maps.Keys(definitions.Items))

	if channel, _, slack := protocol.SlackThreadTarget(id); slack {
		allowed, err := s.channels.ChannelAgentChoices(ctx, channel)
		if err != nil {
			return nil, fmt.Errorf("web channel choices: %w", err)
		}

		choices = slices.DeleteFunc(choices, func(name string) bool { return !slices.Contains(allowed, name) })
	} else if id != "" {
		for _, run := range cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: strings.TrimPrefix(id, "web:")}}, "") {
			job, err := s.cronjobs.LoadOneOffCronjob(run.Stem)
			if err != nil {
				continue
			}

			return s.cfg.CronWebAgentChoices(choices, &job), nil
		}
	}

	return choices, nil
}

func (s *Server) createSession(ctx context.Context, request *CreateSessionRequest) (*CreateSessionResponse, error) {
	principal, _, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	source := request.SourceConversationId
	if source != "" && len(cronHistory([]backend.ObservedSessionEntry{{SourceConversationID: source}}, "")) == 0 {
		return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.InvalidArgument, "source must be a recorded cron run"))
	}

	choices, err := s.agentChoices(ctx, source)
	if err != nil {
		return nil, err
	}

	if source != "" && len(choices) > 0 {
		request.Agent = choices[0]
	}

	if !slices.Contains(choices, request.Agent) {
		return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.InvalidArgument, "select a loaded agent"))
	}

	id := rand.Text()

	if source != "" {
		_, recorded, err := s.sessions.Thread(source)
		if err != nil {
			return nil, fmt.Errorf("read cron conversation: %w", err)
		}

		if !recorded {
			return nil, fmt.Errorf("create web conversation: %w", status.Error(codes.NotFound, "cron run is not recorded"))
		}
		// CreateConversation preserves existing rows; a stable ID also survives failed syncs.
		id = "web:" + source
	}

	if err := s.backend.CreateConversation(ctx, protocol.Conversation{ID: id, Agent: request.Agent, CreatedBy: principal}); err != nil {
		return nil, fmt.Errorf("create web conversation: %w", err)
	}

	if source != "" {
		if err := s.backend.SyncConversation(ctx, source, id); err != nil {
			return nil, fmt.Errorf("sync cron conversation: %w", err)
		}
	}

	return &CreateSessionResponse{Id: id}, nil
}

func (s *Server) prompt(ctx context.Context, request *PromptRequest) (*PromptResponse, error) {
	_, principal, err := s.principal(ctx)
	if err != nil {
		return nil, err
	}

	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	words := strings.Fields(request.Text)
	if request.Delivery == PromptDelivery_STASH {
		words = nil
	}

	if len(words) > 0 && words[0] == "$stop" {
		if len(words) != 1 {
			return nil, fmt.Errorf("web stop: %w", status.Error(codes.InvalidArgument, "stop takes no arguments"))
		}

		inbound := protocol.NewInboundMessage(protocol.SourceWeb, protocol.InboundKindCancel, "", true)
		inbound.ConversationID = request.Id

		inbound.Metadata = map[string]string{protocol.InboundPrincipalMetadataKey: principal}
		if err := s.backend.RunTurn(ctx, inbound); err != nil {
			return nil, fmt.Errorf("web prompt: %w", err)
		}

		return &PromptResponse{}, nil
	}

	if len(words) > 0 && words[0] == "$agent" {
		choices, err := s.agentChoices(ctx, request.Id)
		if err != nil {
			return nil, err
		}

		if len(words) == 1 {
			return &PromptResponse{PrivateText: strings.Join(choices, ", ")}, nil
		}

		if len(words) != 2 || !slices.Contains(choices, words[1]) {
			return nil, fmt.Errorf("web agent: %w", status.Error(codes.InvalidArgument, "agent is not currently allowed"))
		}

		switched, err := s.backend.SwitchConversationAgent(request.Id, words[1])
		if err != nil {
			return nil, fmt.Errorf("switch web agent: %w", err)
		}

		if !switched {
			return nil, fmt.Errorf("web agent: %w", status.Error(codes.NotFound, "conversation is not recorded"))
		}

		return &PromptResponse{PrivateText: "Agent: " + words[1]}, nil
	}

	if len(words) == 1 && strings.EqualFold(words[0], "$workflow") {
		return s.workflowListReply()
	}

	goal, text, rejection := webGoal(request.Text, words)
	if rejection != "" {
		return &PromptResponse{PrivateText: rejection}, nil
	}

	delivery := request.Delivery

	if len(words) > 0 && slices.Contains([]string{"$enqueue", "$stash", "$steer"}, words[0]) {
		text = strings.TrimLeftFunc(strings.TrimPrefix(strings.TrimLeftFunc(text, unicode.IsSpace), words[0]), unicode.IsSpace)
		delivery = map[string]PromptDelivery{
			"$enqueue": PromptDelivery_QUEUE, "$stash": PromptDelivery_STASH, "$steer": PromptDelivery_STEER,
		}[words[0]]
	}

	kind := protocol.InboundKindSteer

	switch delivery {
	case PromptDelivery_STEER:
	case PromptDelivery_QUEUE:
		kind = protocol.InboundKindEnqueue
	case PromptDelivery_STASH:
		kind = protocol.InboundKindHeld
	default:
		return nil, fmt.Errorf("web prompt: %w", status.Error(codes.InvalidArgument, "unknown prompt delivery"))
	}

	if goal.Objective != "" {
		kind = protocol.InboundKindPrompt
	}

	content, err := s.uploadContent(ctx, request.Id, text, request.AttachmentIds)
	if err != nil {
		return nil, err
	}

	if kind == protocol.InboundKindEnqueue || kind == protocol.InboundKindHeld {
		item := &protocol.ThreadQueueItem{
			ID: cmp.Or(request.MessageId, rand.Text()), Message: text, Principal: principal, Source: protocol.SourceWeb,
			Kind: kind, Content: content, StashAt: time.Now().UTC(),
		}
		if err := s.backend.StashQueueItem(ctx, request.Id, item); err != nil {
			return nil, fmt.Errorf("web prompt: %w", err)
		}

		return &PromptResponse{}, nil
	}

	inbound := protocol.NewInboundMessageFromContent(protocol.SourceWeb, kind, &content, true)
	inbound.ConversationID = request.Id

	inbound.Metadata[protocol.InboundPrincipalMetadataKey] = principal

	inbound.Metadata["web_message_id"] = cmp.Or(request.MessageId, rand.Text())
	if goal.Objective != "" {
		inbound.Metadata["web_goal_prompt"] = request.Text + strings.TrimPrefix(inbound.Text, text)
	}

	return s.submitPrompt(ctx, inbound, goal)
}

// webGoal parses a web $goal command. It returns the goal with its objective as
// the prompt text, or the zero goal and text unchanged when the prompt is not a
// $goal. A parsed goal always has an objective.
func webGoal(text string, words []string) (goal protocol.GoalRequest, prompt, rejection string) {
	if len(words) == 0 || !strings.EqualFold(words[0], "$goal") {
		return goal, text, ""
	}

	goal, rejection = protocol.ParseGoalRequest(strings.TrimPrefix(strings.TrimLeftFunc(text, unicode.IsSpace), words[0]))

	return goal, goal.Objective, rejection
}

// workflowListReply answers a bare $workflow privately with the saved workflows.
func (s *Server) workflowListReply() (*PromptResponse, error) {
	descriptions, err := s.backend.WorkflowDescriptions()
	if err != nil {
		return nil, fmt.Errorf("list web workflows: %w", err)
	}

	lines := make([]string, 0, len(descriptions))
	for _, description := range descriptions {
		lines = append(lines, description.Name+" - "+description.Description)
	}

	return &PromptResponse{PrivateText: cmp.Or(strings.Join(lines, "\n"), "No workflows are configured.")}, nil
}

// submitPrompt starts a parsed $goal, or runs any other prompt as a turn.
func (s *Server) submitPrompt(ctx context.Context, inbound *protocol.InboundMessage, goal protocol.GoalRequest) (*PromptResponse, error) {
	var err error
	if goal.Objective != "" {
		err = s.backend.StartGoal(ctx, inbound, goal)
	} else {
		err = s.backend.RunTurn(ctx, inbound)
	}

	if errors.Is(err, protocol.ErrGoalAlreadyActive) {
		return &PromptResponse{PrivateText: "A goal is already in progress in this conversation. Stop it before starting another."}, nil
	}

	if err != nil {
		return nil, fmt.Errorf("web prompt: %w", err)
	}

	return &PromptResponse{}, nil
}

func (s *Server) listQueue(ctx context.Context, request *ListQueueRequest) (*ListQueueResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	items, err := s.backend.QueueItems(request.Id)
	if err != nil {
		return nil, fmt.Errorf("list web queue: %w", err)
	}

	response := &ListQueueResponse{}

	for i := range items {
		input, err := s.inputEvent(ctx, request.Id, strings.Join(append([]string{items[i].Message}, items[i].Content.TextAttachments...), "\n\n"))
		if err != nil {
			return nil, err
		}

		delivery := map[protocol.InboundKind]PromptDelivery{
			"": PromptDelivery_QUEUE, protocol.InboundKindEnqueue: PromptDelivery_QUEUE,
			protocol.InboundKindSteer: PromptDelivery_STEER,
			protocol.InboundKindHeld:  PromptDelivery_STASH,
		}[items[i].Kind]

		response.Items = append(response.Items, &QueueItem{Id: items[i].ID, Text: input.Text, Attachments: input.Attachments, Delivery: delivery, Principal: items[i].Principal})
	}

	return response, nil
}

func (s *Server) queueItem(ctx context.Context, method string, request *QueueItemRequest) (*QueueItemResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	if strings.TrimSpace(request.ItemId) == "" {
		return nil, fmt.Errorf("web queue: %w", status.Error(codes.InvalidArgument, "queue item ID is required"))
	}

	var (
		ok  bool
		err error
	)

	switch method {
	case "SteerQueueItem":
		ok, err = s.backend.PromoteQueueItem(ctx, request.Id, request.ItemId)
	case "PopQueueItem":
		ok, err = s.backend.PopQueueItem(ctx, request.Id, request.ItemId)
	case "RemoveQueueItem":
		ok, err = s.backend.DeleteQueueItem(ctx, request.Id, request.ItemId)
	}

	if err != nil {
		return nil, fmt.Errorf("web %s: %w", method, err)
	}

	if !ok {
		return nil, fmt.Errorf("web queue: %w", status.Error(codes.NotFound, "queue item is not recorded"))
	}

	return &QueueItemResponse{}, nil
}

func (s *Server) reorderQueue(ctx context.Context, request *ReorderQueueRequest) (*QueueItemResponse, error) {
	if err := s.visibleConversation(ctx, request.Id); err != nil {
		return nil, err
	}

	if err := s.backend.ReorderQueueItems(request.Id, request.ItemIds); err != nil {
		return nil, fmt.Errorf("reorder web queue: %w", err)
	}

	return &QueueItemResponse{}, nil
}

// listBackgroundJobs adds the conversation's Background Jobs to response, and whether
// MoveToBackground has work there.
func (s *Server) listBackgroundJobs(ctx context.Context, response *HistoryResponse, request *HistoryRequest) error {
	// Only the History RPC's latest page of a chat carries the running list; cron traces and
	// internal history reads (search, attachments, session commands) never need it.
	if request.GetBefore() != 0 || strings.HasPrefix(request.Id, "cron:") || strings.HasPrefix(request.Id, "one-off-cron:") {
		return nil
	}

	jobs, movable, err := s.backend.BackgroundJobs(ctx, request.Id)
	if err != nil {
		return fmt.Errorf("read web background jobs: %w", err)
	}

	response.Movable, response.BackgroundJobs = movable, backgroundJobs(jobs)

	return nil
}

func backgroundJobs(jobs []protocol.BackgroundJob) []*BackgroundJob {
	listed := make([]*BackgroundJob, len(jobs))
	for i := range jobs {
		job := &jobs[i]
		listed[i] = &BackgroundJob{JobId: job.ID, Kind: job.Kind, State: job.State, Label: job.Label, ToolCallId: job.ToolCallID, SubagentKey: job.SubagentKey, StoppedBy: job.StoppedBy, Hidden: job.Hidden, Note: job.Note}
	}

	return listed
}

func (s *Server) moveToBackground(ctx context.Context, request *MoveToBackgroundRequest) (*MoveToBackgroundResponse, error) {
	if err := s.visibleConversation(ctx, request.ConversationId); err != nil {
		return nil, err
	}

	moved, err := s.backend.MoveToBackground(request.ConversationId)
	if err != nil {
		return nil, fmt.Errorf("web move to background: %w", err)
	}

	return &MoveToBackgroundResponse{Moved: moved}, nil
}

func (s *Server) stopBackgroundJob(ctx context.Context, request *StopBackgroundJobRequest) (*StopBackgroundJobResponse, error) {
	if err := s.visibleConversation(ctx, request.ConversationId); err != nil {
		return nil, err
	}

	if strings.TrimSpace(request.JobId) == "" {
		return nil, fmt.Errorf("web stop background job: %w", status.Error(codes.InvalidArgument, "background job ID is required"))
	}

	stopped, err := s.backend.StopBackgroundJob(ctx, request.ConversationId, request.JobId)
	if err != nil {
		return nil, fmt.Errorf("web stop background job: %w", err)
	}

	return &StopBackgroundJobResponse{Stopped: stopped}, nil
}

func (s *Server) visibleConversation(ctx context.Context, id string) error {
	if _, _, err := s.principal(ctx); err != nil {
		return err
	}

	if strings.TrimSpace(id) == "" {
		return fmt.Errorf("web queue: %w", status.Error(codes.InvalidArgument, "conversation ID is required"))
	}

	visible, err := s.humanConversation(id)
	if err != nil {
		return err
	}

	if !visible {
		return fmt.Errorf("web queue: %w", status.Error(codes.PermissionDenied, "private conversation"))
	}

	return nil
}

func (s *Server) join(request *JoinRequest, stream grpc.ServerStream) error {
	if err := s.visibleConversation(stream.Context(), request.Id); err != nil {
		return err
	}

	for change, err := range s.sessions.Changes(stream.Context(), request.Id) {
		if err != nil {
			return fmt.Errorf("web conversation changes: %w", err)
		}

		if err := stream.SendMsg(&ConversationChange{ConversationId: change.ConversationID, Revision: change.Revision}); err != nil {
			return fmt.Errorf("send web conversation change: %w", err)
		}
	}

	return nil
}

func (s *Server) principal(ctx context.Context) (username, principal string, err error) {
	values := metadata.ValueFromIncomingContext(ctx, "rocketclaw-principal")
	if len(values) != 1 {
		return "", "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "browser IP is required"))
	}

	ip, err := netip.ParseAddr(values[0])
	if err != nil {
		return "", "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "invalid browser IP"))
	}

	if username := s.usernames[ip]; username != "" {
		return username, username, nil
	}

	return s.tailscaleUsername(ctx, ip)
}

func (s *Server) tailscaleUsername(ctx context.Context, ip netip.Addr) (username, principal string, err error) {
	ip = ip.Unmap()
	// Cache misses serialize across IPs; use per-IP coordination if lookup contention grows.
	s.tailscaleMu.Lock()
	defer s.tailscaleMu.Unlock()

	now := time.Now()
	if user := s.tailscaleUsers[ip]; now.Before(user.expires) {
		return user.username, user.principal, nil
	}

	maps.DeleteFunc(s.tailscaleUsers, func(_ netip.Addr, user tailscaleUser) bool { return !now.Before(user.expires) })

	output, err := exec.CommandContext(ctx, "tailscale", "whois", "--json", ip.String()).Output()
	if err != nil {
		return "", "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "Tailscale could not identify browser IP"))
	}

	var identity struct {
		Node        struct{ Tags []string }
		UserProfile struct{ LoginName, DisplayName string }
	}
	if err := json.Unmarshal(output, &identity); err != nil {
		return "", "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "invalid Tailscale identity response"))
	}

	if len(identity.Node.Tags) > 0 || identity.UserProfile.LoginName == "" {
		return "", "", fmt.Errorf("web principal: %w", status.Error(codes.Unauthenticated, "browser IP has no Tailscale user"))
	}

	if s.tailscaleUsers == nil {
		s.tailscaleUsers = make(map[netip.Addr]tailscaleUser)
	}

	principal = identity.UserProfile.DisplayName
	if strings.TrimSpace(principal) == "" {
		principal = identity.UserProfile.LoginName
	}

	s.tailscaleUsers[ip] = tailscaleUser{username: identity.UserProfile.LoginName, principal: principal, expires: time.Now().Add(5 * time.Minute)}

	return identity.UserProfile.LoginName, principal, nil
}

func (s *Server) entries(ctx context.Context, id string) ([]backend.ObservedSessionEntry, error) {
	if err := s.visibleConversation(ctx, id); err != nil {
		return nil, err
	}

	entries, err := s.sessions.ObserveEntries(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("web entries: %w", status.Error(codes.Internal, "load session entries"))
	}

	return slices.DeleteFunc(entries, func(entry backend.ObservedSessionEntry) bool { return entry.Synced && entry.SourceConversationID == "" }), nil
}

type originKind string

const (
	originCron        originKind = "cron"
	originExternalMCP originKind = "external_mcp"
)

type cronRunKind string

const (
	cronScheduled cronRunKind = "scheduled"
	cronOneOff    cronRunKind = "one-off"
)

type cronRun struct {
	kind       cronRunKind
	path, stem string
	at         time.Time
}

type originPair struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type cronOrigin struct {
	Agent      string      `json:"agent"`
	Kind       originKind  `json:"kind"`
	RanAt      string      `json:"ranAt"`
	RunID      string      `json:"runId"`
	RunKind    cronRunKind `json:"runKind"`
	SourcePath string      `json:"sourcePath"`
	Stem       string      `json:"stem"`
}

type externalMCPOrigin struct {
	Agent                  string       `json:"agent"`
	ExternalConversationID string       `json:"externalConversationId"`
	Kind                   originKind   `json:"kind"`
	Pairs                  []originPair `json:"pairs"`
}

// chatOrigin reads only this session's physical origin, independent of its cutoff.
func (s *Server) chatOrigin(ctx context.Context, id string) (string, error) {
	for facts, err := range s.sessions.ChatOriginFacts(ctx, id) {
		if err != nil {
			return "", fmt.Errorf("read origin facts: %w", err)
		}

		origin, _ := decideOrigin(&facts)
		if origin == nil {
			return "", nil
		}

		raw, err := json.Marshal(origin)
		if err != nil {
			return "", fmt.Errorf("encode chat origin: %w", err)
		}

		return string(raw), nil
	}

	return "", nil
}

// decideOrigin applies the origin rules to stored facts and returns the origin with the
// lowercased text origin search matches; a nil origin means none.
func decideOrigin(facts *backend.ChatOriginFacts) (origin any, text string) {
	locator, cronOn := creatingCronLocator(facts.ConversationID, facts.CreatedBy, facts.CreatingSource)

	mcpOn := facts.Binding.ManagedConversationID == facts.ConversationID
	if mcpOn == cronOn {
		return nil, ""
	}

	if mcpOn {
		pairs := make([]originPair, 0, len(facts.Binding.OriginPairs))
		texts := make([]string, 0, len(facts.Binding.OriginPairs))

		for _, key := range slices.Sorted(maps.Keys(facts.Binding.OriginPairs)) {
			pairs = append(pairs, originPair{Key: key, Value: facts.Binding.OriginPairs[key]})
			texts = append(texts, key+"="+facts.Binding.OriginPairs[key])
		}

		return externalMCPOrigin{Kind: originExternalMCP, ExternalConversationID: facts.ExternalConversationID, Agent: facts.Binding.Agent, Pairs: pairs},
			strings.ToLower(fmt.Sprintf("External MCP External conversation: %s Agent: %s %s", facts.ExternalConversationID, facts.Binding.Agent, strings.Join(texts, " ")))
	}

	run, _ := parseCronRun(locator)
	cron := cronOrigin{Kind: originCron, SourcePath: run.path, Stem: run.stem, RunKind: run.kind, RunID: locator, Agent: facts.ProducerAgent, RanAt: run.at.Format(time.RFC3339Nano)}

	return cron, strings.ToLower(fmt.Sprintf("Cron Source: %s Stem: %s Run kind: %s Run ID: %s Agent: %s Ran at: %s", cron.SourcePath, cron.Stem, cron.RunKind, cron.RunID, cron.Agent, cron.RanAt))
}

func creatingCronLocator(id string, createdBy backend.ThreadCreator, creatingSource string) (string, bool) {
	if source, ok := strings.CutPrefix(id, "web:"); ok {
		if _, parsed := parseCronRun(source); parsed {
			return source, true
		}
	}

	if _, _, slack := protocol.SlackThreadTarget(id); slack && createdBy != backend.ThreadCreatedByCron {
		return "", false
	}

	if _, ok := parseCronRun(creatingSource); ok {
		return creatingSource, true
	}

	return "", false
}

func parseCronRun(source string) (cronRun, bool) {
	kind, path, ok := cronScheduled, "", false
	if rest, cut := strings.CutPrefix(source, "cron:"); cut {
		path, ok = rest, true
	} else if rest, cut := strings.CutPrefix(source, "one-off-cron:"); cut {
		kind, path, ok = cronOneOff, rest, true
	}

	end := strings.LastIndex(path, ":")

	start := strings.LastIndex(path[:max(end, 0)], ":")
	if !ok || start < 0 {
		return cronRun{}, false
	}

	at, err := time.Parse("20060102T150405.000000000Z", path[start+1:end])
	if err != nil {
		return cronRun{}, false
	}

	relative := path[:start]

	return cronRun{kind: kind, path: relative, stem: strings.TrimSuffix(strings.TrimPrefix(relative, "cron/"), ".md"), at: at}, true
}
