// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: web.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromptDelivery int32

const (
	PromptDelivery_STEER PromptDelivery = 0
	PromptDelivery_QUEUE PromptDelivery = 1
)

// Enum value maps for PromptDelivery.
var (
	PromptDelivery_name = map[int32]string{
		0: "STEER",
		1: "QUEUE",
	}
	PromptDelivery_value = map[string]int32{
		"STEER": 0,
		"QUEUE": 1,
	}
)

func (x PromptDelivery) Enum() *PromptDelivery {
	p := new(PromptDelivery)
	*p = x
	return p
}

func (x PromptDelivery) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromptDelivery) Descriptor() protoreflect.EnumDescriptor {
	return file_web_proto_enumTypes[0].Descriptor()
}

func (PromptDelivery) Type() protoreflect.EnumType {
	return &file_web_proto_enumTypes[0]
}

func (x PromptDelivery) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromptDelivery.Descriptor instead.
func (PromptDelivery) EnumDescriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Preview       string                 `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Agent         string                 `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	Settled       bool                   `protobuf:"varint,6,opt,name=settled,proto3" json:"settled,omitempty"`
	AllowedAgents []string               `protobuf:"bytes,7,rep,name=allowed_agents,json=allowedAgents,proto3" json:"allowed_agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Session) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *Session) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Session) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Session) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *Session) GetAllowedAgents() []string {
	if x != nil {
		return x.AllowedAgents
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_web_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*TranscriptEvent     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_web_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryResponse) GetMessages() []*TranscriptEvent {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_web_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_web_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_web_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_web_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TranscriptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Snapshot      bool                   `protobuf:"varint,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Complete      bool                   `protobuf:"varint,4,opt,name=complete,proto3" json:"complete,omitempty"`
	TurnId        string                 `protobuf:"bytes,5,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_web_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{8}
}

func (x *TranscriptEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptEvent) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *TranscriptEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *TranscriptEvent) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *TranscriptEvent) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Delivery      PromptDelivery         `protobuf:"varint,3,opt,name=delivery,proto3,enum=rpc.PromptDelivery" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_web_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{9}
}

func (x *PromptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromptRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PromptRequest) GetDelivery() PromptDelivery {
	if x != nil {
		return x.Delivery
	}
	return PromptDelivery_STEER
}

type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateText   string                 `protobuf:"bytes,1,opt,name=private_text,json=privateText,proto3" json:"private_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_web_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{10}
}

func (x *PromptResponse) GetPrivateText() string {
	if x != nil {
		return x.PrivateText
	}
	return ""
}

type CronJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stem          string                 `protobuf:"bytes,1,opt,name=stem,proto3" json:"stem,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastRun       string                 `protobuf:"bytes,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	NextRun       string                 `protobuf:"bytes,4,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	Schedule      string                 `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Agent         string                 `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	Channel       string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Upcoming      []string               `protobuf:"bytes,9,rep,name=upcoming,proto3" json:"upcoming,omitempty"`
	Origin        string                 `protobuf:"bytes,10,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_web_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{11}
}

func (x *CronJob) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *CronJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronJob) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *CronJob) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CronJob) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CronJob) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CronJob) GetUpcoming() []string {
	if x != nil {
		return x.Upcoming
	}
	return nil
}

func (x *CronJob) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Reasoning     string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Verbosity     string                 `protobuf:"bytes,5,opt,name=verbosity,proto3" json:"verbosity,omitempty"`
	Prompt        string                 `protobuf:"bytes,6,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Permissions   string                 `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Origin        string                 `protobuf:"bytes,8,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_web_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{12}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Agent) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetVerbosity() string {
	if x != nil {
		return x.Verbosity
	}
	return ""
}

func (x *Agent) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Agent) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *Agent) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_web_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{13}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_web_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{14}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	License       string                 `protobuf:"bytes,3,opt,name=license,proto3" json:"license,omitempty"`
	Compatibility string                 `protobuf:"bytes,4,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Origin        string                 `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_web_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{15}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *Skill) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

func (x *Skill) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Skill) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type ListSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_web_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{16}
}

type ListSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_web_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{17}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type ListCronJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsRequest) Reset() {
	*x = ListCronJobsRequest{}
	mi := &file_web_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsRequest) ProtoMessage() {}

func (x *ListCronJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsRequest.ProtoReflect.Descriptor instead.
func (*ListCronJobsRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{18}
}

type ListCronJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*CronJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsResponse) Reset() {
	*x = ListCronJobsResponse{}
	mi := &file_web_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsResponse) ProtoMessage() {}

func (x *ListCronJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsResponse.ProtoReflect.Descriptor instead.
func (*ListCronJobsResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{19}
}

func (x *ListCronJobsResponse) GetJobs() []*CronJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type RunCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stem          string                 `protobuf:"bytes,1,opt,name=stem,proto3" json:"stem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronJobRequest) Reset() {
	*x = RunCronJobRequest{}
	mi := &file_web_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronJobRequest) ProtoMessage() {}

func (x *RunCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronJobRequest.ProtoReflect.Descriptor instead.
func (*RunCronJobRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{20}
}

func (x *RunCronJobRequest) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

type RunCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronJobResponse) Reset() {
	*x = RunCronJobResponse{}
	mi := &file_web_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronJobResponse) ProtoMessage() {}

func (x *RunCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronJobResponse.ProtoReflect.Descriptor instead.
func (*RunCronJobResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{21}
}

func (x *RunCronJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AnswerQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AskId         string                 `protobuf:"bytes,1,opt,name=ask_id,json=askId,proto3" json:"ask_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Dismiss       bool                   `protobuf:"varint,3,opt,name=dismiss,proto3" json:"dismiss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionRequest) Reset() {
	*x = AnswerQuestionRequest{}
	mi := &file_web_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionRequest) ProtoMessage() {}

func (x *AnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{22}
}

func (x *AnswerQuestionRequest) GetAskId() string {
	if x != nil {
		return x.AskId
	}
	return ""
}

func (x *AnswerQuestionRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AnswerQuestionRequest) GetDismiss() bool {
	if x != nil {
		return x.Dismiss
	}
	return false
}

type AnswerQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionResponse) Reset() {
	*x = AnswerQuestionResponse{}
	mi := &file_web_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionResponse) ProtoMessage() {}

func (x *AnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{23}
}

type ConfigModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigModel) Reset() {
	*x = ConfigModel{}
	mi := &file_web_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigModel) ProtoMessage() {}

func (x *ConfigModel) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigModel.ProtoReflect.Descriptor instead.
func (*ConfigModel) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigModel) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ConfigChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Agents        []string               `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChannel) Reset() {
	*x = ConfigChannel{}
	mi := &file_web_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChannel) ProtoMessage() {}

func (x *ConfigChannel) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChannel.ProtoReflect.Descriptor instead.
func (*ConfigChannel) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigChannel) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ConfigChannel) GetAgents() []string {
	if x != nil {
		return x.Agents
	}
	return nil
}

type ConfigView struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Workspace              string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Overlays               []string               `protobuf:"bytes,2,rep,name=overlays,proto3" json:"overlays,omitempty"`
	Models                 []*ConfigModel         `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	SlackChannels          []*ConfigChannel       `protobuf:"bytes,4,rep,name=slack_channels,json=slackChannels,proto3" json:"slack_channels,omitempty"`
	McpServers             []string               `protobuf:"bytes,5,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	LoggingLevel           string                 `protobuf:"bytes,6,opt,name=logging_level,json=loggingLevel,proto3" json:"logging_level,omitempty"`
	AutoApproverModel      string                 `protobuf:"bytes,7,opt,name=auto_approver_model,json=autoApproverModel,proto3" json:"auto_approver_model,omitempty"`
	InstrumentationEnabled bool                   `protobuf:"varint,8,opt,name=instrumentation_enabled,json=instrumentationEnabled,proto3" json:"instrumentation_enabled,omitempty"`
	McpExternal            bool                   `protobuf:"varint,9,opt,name=mcp_external,json=mcpExternal,proto3" json:"mcp_external,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigView) Reset() {
	*x = ConfigView{}
	mi := &file_web_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigView) ProtoMessage() {}

func (x *ConfigView) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigView.ProtoReflect.Descriptor instead.
func (*ConfigView) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{26}
}

func (x *ConfigView) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ConfigView) GetOverlays() []string {
	if x != nil {
		return x.Overlays
	}
	return nil
}

func (x *ConfigView) GetModels() []*ConfigModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ConfigView) GetSlackChannels() []*ConfigChannel {
	if x != nil {
		return x.SlackChannels
	}
	return nil
}

func (x *ConfigView) GetMcpServers() []string {
	if x != nil {
		return x.McpServers
	}
	return nil
}

func (x *ConfigView) GetLoggingLevel() string {
	if x != nil {
		return x.LoggingLevel
	}
	return ""
}

func (x *ConfigView) GetAutoApproverModel() string {
	if x != nil {
		return x.AutoApproverModel
	}
	return ""
}

func (x *ConfigView) GetInstrumentationEnabled() bool {
	if x != nil {
		return x.InstrumentationEnabled
	}
	return false
}

func (x *ConfigView) GetMcpExternal() bool {
	if x != nil {
		return x.McpExternal
	}
	return false
}

type ListConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigRequest) Reset() {
	*x = ListConfigRequest{}
	mi := &file_web_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigRequest) ProtoMessage() {}

func (x *ListConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigRequest.ProtoReflect.Descriptor instead.
func (*ListConfigRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{27}
}

type ListConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ConfigView            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigResponse) Reset() {
	*x = ListConfigResponse{}
	mi := &file_web_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigResponse) ProtoMessage() {}

func (x *ListConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigResponse.ProtoReflect.Descriptor instead.
func (*ListConfigResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{28}
}

func (x *ListConfigResponse) GetConfig() *ConfigView {
	if x != nil {
		return x.Config
	}
	return nil
}

type SettleSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Settled       bool                   `protobuf:"varint,2,opt,name=settled,proto3" json:"settled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleSessionRequest) Reset() {
	*x = SettleSessionRequest{}
	mi := &file_web_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleSessionRequest) ProtoMessage() {}

func (x *SettleSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleSessionRequest.ProtoReflect.Descriptor instead.
func (*SettleSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{29}
}

func (x *SettleSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SettleSessionRequest) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

type SettleSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleSessionResponse) Reset() {
	*x = SettleSessionResponse{}
	mi := &file_web_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleSessionResponse) ProtoMessage() {}

func (x *SettleSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleSessionResponse.ProtoReflect.Descriptor instead.
func (*SettleSessionResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{30}
}

type ProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolRequest) Reset() {
	*x = ProtocolRequest{}
	mi := &file_web_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolRequest) ProtoMessage() {}

func (x *ProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolRequest.ProtoReflect.Descriptor instead.
func (*ProtocolRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{31}
}

type ProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoSha256   string                 `protobuf:"bytes,1,opt,name=proto_sha256,json=protoSha256,proto3" json:"proto_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolResponse) Reset() {
	*x = ProtocolResponse{}
	mi := &file_web_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolResponse) ProtoMessage() {}

func (x *ProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolResponse.ProtoReflect.Descriptor instead.
func (*ProtocolResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{32}
}

func (x *ProtocolResponse) GetProtoSha256() string {
	if x != nil {
		return x.ProtoSha256
	}
	return ""
}

type QueueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueItem) Reset() {
	*x = QueueItem{}
	mi := &file_web_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueItem) ProtoMessage() {}

func (x *QueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueItem.ProtoReflect.Descriptor instead.
func (*QueueItem) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{33}
}

func (x *QueueItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ListQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueRequest) Reset() {
	*x = ListQueueRequest{}
	mi := &file_web_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueRequest) ProtoMessage() {}

func (x *ListQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueRequest.ProtoReflect.Descriptor instead.
func (*ListQueueRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{34}
}

func (x *ListQueueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueueItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueResponse) Reset() {
	*x = ListQueueResponse{}
	mi := &file_web_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueResponse) ProtoMessage() {}

func (x *ListQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueResponse.ProtoReflect.Descriptor instead.
func (*ListQueueResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{35}
}

func (x *ListQueueResponse) GetItems() []*QueueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueueItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueItemRequest) Reset() {
	*x = QueueItemRequest{}
	mi := &file_web_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueItemRequest) ProtoMessage() {}

func (x *QueueItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueItemRequest.ProtoReflect.Descriptor instead.
func (*QueueItemRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{36}
}

func (x *QueueItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueueItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type QueueItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueItemResponse) Reset() {
	*x = QueueItemResponse{}
	mi := &file_web_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueItemResponse) ProtoMessage() {}

func (x *QueueItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueItemResponse.ProtoReflect.Descriptor instead.
func (*QueueItemResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{37}
}

type ReorderQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemIds       []string               `protobuf:"bytes,2,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderQueueRequest) Reset() {
	*x = ReorderQueueRequest{}
	mi := &file_web_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderQueueRequest) ProtoMessage() {}

func (x *ReorderQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderQueueRequest.ProtoReflect.Descriptor instead.
func (*ReorderQueueRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{38}
}

func (x *ReorderQueueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReorderQueueRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type SessionEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEntriesRequest) Reset() {
	*x = SessionEntriesRequest{}
	mi := &file_web_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEntriesRequest) ProtoMessage() {}

func (x *SessionEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEntriesRequest.ProtoReflect.Descriptor instead.
func (*SessionEntriesRequest) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{39}
}

func (x *SessionEntriesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SessionEntryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEntryMeta) Reset() {
	*x = SessionEntryMeta{}
	mi := &file_web_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEntryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEntryMeta) ProtoMessage() {}

func (x *SessionEntryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEntryMeta.ProtoReflect.Descriptor instead.
func (*SessionEntryMeta) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{40}
}

func (x *SessionEntryMeta) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionEntryMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionEntryMeta) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ListSessionEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SessionEntryMeta    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionEntriesResponse) Reset() {
	*x = ListSessionEntriesResponse{}
	mi := &file_web_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionEntriesResponse) ProtoMessage() {}

func (x *ListSessionEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListSessionEntriesResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{41}
}

func (x *ListSessionEntriesResponse) GetEntries() []*SessionEntryMeta {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SessionEntryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Json          string                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEntryData) Reset() {
	*x = SessionEntryData{}
	mi := &file_web_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEntryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEntryData) ProtoMessage() {}

func (x *SessionEntryData) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEntryData.ProtoReflect.Descriptor instead.
func (*SessionEntryData) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{42}
}

func (x *SessionEntryData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionEntryData) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type LoadSessionEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SessionEntryData    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSessionEntriesResponse) Reset() {
	*x = LoadSessionEntriesResponse{}
	mi := &file_web_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSessionEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSessionEntriesResponse) ProtoMessage() {}

func (x *LoadSessionEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSessionEntriesResponse.ProtoReflect.Descriptor instead.
func (*LoadSessionEntriesResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{43}
}

func (x *LoadSessionEntriesResponse) GetEntries() []*SessionEntryData {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeleteSessionEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionEntriesResponse) Reset() {
	*x = DeleteSessionEntriesResponse{}
	mi := &file_web_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionEntriesResponse) ProtoMessage() {}

func (x *DeleteSessionEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionEntriesResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionEntriesResponse) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{44}
}

func (x *DeleteSessionEntriesResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_web_proto protoreflect.FileDescriptor

const file_web_proto_rawDesc = "" +
	"\n" +
	"\tweb.proto\x12\x03rpc\"\x15\n" +
	"\x13ListSessionsRequest\"\xbf\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\apreview\x18\x03 \x01(\tR\apreview\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05agent\x18\x05 \x01(\tR\x05agent\x12\x18\n" +
	"\asettled\x18\x06 \x01(\bR\asettled\x12%\n" +
	"\x0eallowed_agents\x18\a \x03(\tR\rallowedAgents\" \n" +
	"\x0eHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x0fHistoryResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.rpc.TranscriptEventR\bmessages\"@\n" +
	"\x14ListSessionsResponse\x12(\n" +
	"\bsessions\x18\x01 \x03(\v2\f.rpc.SessionR\bsessions\"@\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\"'\n" +
	"\x15CreateSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\vJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8a\x01\n" +
	"\x0fTranscriptEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\bR\bsnapshot\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\bR\bcomplete\x12\x17\n" +
	"\aturn_id\x18\x05 \x01(\tR\x06turnId\"d\n" +
	"\rPromptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12/\n" +
	"\bdelivery\x18\x03 \x01(\x0e2\x13.rpc.PromptDeliveryR\bdelivery\"3\n" +
	"\x0ePromptResponse\x12!\n" +
	"\fprivate_text\x18\x01 \x01(\tR\vprivateText\"\xff\x01\n" +
	"\aCronJob\x12\x12\n" +
	"\x04stem\x18\x01 \x01(\tR\x04stem\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\blast_run\x18\x03 \x01(\tR\alastRun\x12\x19\n" +
	"\bnext_run\x18\x04 \x01(\tR\anextRun\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x14\n" +
	"\x05agent\x18\a \x01(\tR\x05agent\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12\x1a\n" +
	"\bupcoming\x18\t \x03(\tR\bupcoming\x12\x16\n" +
	"\x06origin\x18\n" +
	" \x01(\tR\x06origin\"\xe1\x01\n" +
	"\x05Agent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tverbosity\x18\x05 \x01(\tR\tverbosity\x12\x16\n" +
	"\x06prompt\x18\x06 \x01(\tR\x06prompt\x12 \n" +
	"\vpermissions\x18\a \x01(\tR\vpermissions\x12\x16\n" +
	"\x06origin\x18\b \x01(\tR\x06origin\"\x13\n" +
	"\x11ListAgentsRequest\"8\n" +
	"\x12ListAgentsResponse\x12\"\n" +
	"\x06agents\x18\x01 \x03(\v2\n" +
	".rpc.AgentR\x06agents\"\xaf\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\alicense\x18\x03 \x01(\tR\alicense\x12$\n" +
	"\rcompatibility\x18\x04 \x01(\tR\rcompatibility\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06origin\x18\x06 \x01(\tR\x06origin\"\x13\n" +
	"\x11ListSkillsRequest\"8\n" +
	"\x12ListSkillsResponse\x12\"\n" +
	"\x06skills\x18\x01 \x03(\v2\n" +
	".rpc.SkillR\x06skills\"\x15\n" +
	"\x13ListCronJobsRequest\"8\n" +
	"\x14ListCronJobsResponse\x12 \n" +
	"\x04jobs\x18\x01 \x03(\v2\f.rpc.CronJobR\x04jobs\"'\n" +
	"\x11RunCronJobRequest\x12\x12\n" +
	"\x04stem\x18\x01 \x01(\tR\x04stem\"$\n" +
	"\x12RunCronJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x15AnswerQuestionRequest\x12\x15\n" +
	"\x06ask_id\x18\x01 \x01(\tR\x05askId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x18\n" +
	"\adismiss\x18\x03 \x01(\bR\adismiss\"\x18\n" +
	"\x16AnswerQuestionResponse\"7\n" +
	"\vConfigModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"A\n" +
	"\rConfigChannel\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06agents\x18\x02 \x03(\tR\x06agents\"\xfd\x02\n" +
	"\n" +
	"ConfigView\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\boverlays\x18\x02 \x03(\tR\boverlays\x12(\n" +
	"\x06models\x18\x03 \x03(\v2\x10.rpc.ConfigModelR\x06models\x129\n" +
	"\x0eslack_channels\x18\x04 \x03(\v2\x12.rpc.ConfigChannelR\rslackChannels\x12\x1f\n" +
	"\vmcp_servers\x18\x05 \x03(\tR\n" +
	"mcpServers\x12#\n" +
	"\rlogging_level\x18\x06 \x01(\tR\floggingLevel\x12.\n" +
	"\x13auto_approver_model\x18\a \x01(\tR\x11autoApproverModel\x127\n" +
	"\x17instrumentation_enabled\x18\b \x01(\bR\x16instrumentationEnabled\x12!\n" +
	"\fmcp_external\x18\t \x01(\bR\vmcpExternal\"\x13\n" +
	"\x11ListConfigRequest\"=\n" +
	"\x12ListConfigResponse\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.rpc.ConfigViewR\x06config\"@\n" +
	"\x14SettleSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asettled\x18\x02 \x01(\bR\asettled\"\x17\n" +
	"\x15SettleSessionResponse\"\x11\n" +
	"\x0fProtocolRequest\"5\n" +
	"\x10ProtocolResponse\x12!\n" +
	"\fproto_sha256\x18\x01 \x01(\tR\vprotoSha256\"/\n" +
	"\tQueueItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\"\n" +
	"\x10ListQueueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x11ListQueueResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.rpc.QueueItemR\x05items\";\n" +
	"\x10QueueItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\"\x13\n" +
	"\x11QueueItemResponse\"@\n" +
	"\x13ReorderQueueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\tR\aitemIds\"'\n" +
	"\x15SessionEntriesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x10SessionEntryMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"M\n" +
	"\x1aListSessionEntriesResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.rpc.SessionEntryMetaR\aentries\"6\n" +
	"\x10SessionEntryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"M\n" +
	"\x1aLoadSessionEntriesResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.rpc.SessionEntryDataR\aentries\"8\n" +
	"\x1cDeleteSessionEntriesResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted*&\n" +
	"\x0ePromptDelivery\x12\t\n" +
	"\x05STEER\x10\x00\x12\t\n" +
	"\x05QUEUE\x10\x012\xb8\n" +
	"\n" +
	"\x03Web\x12C\n" +
	"\fListSessions\x12\x18.rpc.ListSessionsRequest\x1a\x19.rpc.ListSessionsResponse\x12F\n" +
	"\rCreateSession\x12\x19.rpc.CreateSessionRequest\x1a\x1a.rpc.CreateSessionResponse\x120\n" +
	"\x04Join\x12\x10.rpc.JoinRequest\x1a\x14.rpc.TranscriptEvent0\x01\x121\n" +
	"\x06Prompt\x12\x12.rpc.PromptRequest\x1a\x13.rpc.PromptResponse\x12C\n" +
	"\fListCronJobs\x12\x18.rpc.ListCronJobsRequest\x1a\x19.rpc.ListCronJobsResponse\x12=\n" +
	"\n" +
	"RunCronJob\x12\x16.rpc.RunCronJobRequest\x1a\x17.rpc.RunCronJobResponse\x12I\n" +
	"\x0eAnswerQuestion\x12\x1a.rpc.AnswerQuestionRequest\x1a\x1b.rpc.AnswerQuestionResponse\x124\n" +
	"\aHistory\x12\x13.rpc.HistoryRequest\x1a\x14.rpc.HistoryResponse\x12=\n" +
	"\n" +
	"ListAgents\x12\x16.rpc.ListAgentsRequest\x1a\x17.rpc.ListAgentsResponse\x12=\n" +
	"\n" +
	"ListSkills\x12\x16.rpc.ListSkillsRequest\x1a\x17.rpc.ListSkillsResponse\x12=\n" +
	"\n" +
	"ListConfig\x12\x16.rpc.ListConfigRequest\x1a\x17.rpc.ListConfigResponse\x12F\n" +
	"\rSettleSession\x12\x19.rpc.SettleSessionRequest\x1a\x1a.rpc.SettleSessionResponse\x127\n" +
	"\bProtocol\x12\x14.rpc.ProtocolRequest\x1a\x15.rpc.ProtocolResponse\x12:\n" +
	"\tListQueue\x12\x15.rpc.ListQueueRequest\x1a\x16.rpc.ListQueueResponse\x12@\n" +
	"\x0fRemoveQueueItem\x12\x15.rpc.QueueItemRequest\x1a\x16.rpc.QueueItemResponse\x12?\n" +
	"\x0eSteerQueueItem\x12\x15.rpc.QueueItemRequest\x1a\x16.rpc.QueueItemResponse\x12@\n" +
	"\fReorderQueue\x12\x18.rpc.ReorderQueueRequest\x1a\x16.rpc.QueueItemResponse\x12Q\n" +
	"\x12ListSessionEntries\x12\x1a.rpc.SessionEntriesRequest\x1a\x1f.rpc.ListSessionEntriesResponse\x12Q\n" +
	"\x12LoadSessionEntries\x12\x1a.rpc.SessionEntriesRequest\x1a\x1f.rpc.LoadSessionEntriesResponse\x12U\n" +
	"\x14DeleteSessionEntries\x12\x1a.rpc.SessionEntriesRequest\x1a!.rpc.DeleteSessionEntriesResponseBAZ?github.com/Rocketable/platform/internal/rocketclaw/frontend/rpcb\x06proto3"

var (
	file_web_proto_rawDescOnce sync.Once
	file_web_proto_rawDescData []byte
)

func file_web_proto_rawDescGZIP() []byte {
	file_web_proto_rawDescOnce.Do(func() {
		file_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)))
	})
	return file_web_proto_rawDescData
}

var file_web_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_web_proto_goTypes = []any{
	(PromptDelivery)(0),                  // 0: rpc.PromptDelivery
	(*ListSessionsRequest)(nil),          // 1: rpc.ListSessionsRequest
	(*Session)(nil),                      // 2: rpc.Session
	(*HistoryRequest)(nil),               // 3: rpc.HistoryRequest
	(*HistoryResponse)(nil),              // 4: rpc.HistoryResponse
	(*ListSessionsResponse)(nil),         // 5: rpc.ListSessionsResponse
	(*CreateSessionRequest)(nil),         // 6: rpc.CreateSessionRequest
	(*CreateSessionResponse)(nil),        // 7: rpc.CreateSessionResponse
	(*JoinRequest)(nil),                  // 8: rpc.JoinRequest
	(*TranscriptEvent)(nil),              // 9: rpc.TranscriptEvent
	(*PromptRequest)(nil),                // 10: rpc.PromptRequest
	(*PromptResponse)(nil),               // 11: rpc.PromptResponse
	(*CronJob)(nil),                      // 12: rpc.CronJob
	(*Agent)(nil),                        // 13: rpc.Agent
	(*ListAgentsRequest)(nil),            // 14: rpc.ListAgentsRequest
	(*ListAgentsResponse)(nil),           // 15: rpc.ListAgentsResponse
	(*Skill)(nil),                        // 16: rpc.Skill
	(*ListSkillsRequest)(nil),            // 17: rpc.ListSkillsRequest
	(*ListSkillsResponse)(nil),           // 18: rpc.ListSkillsResponse
	(*ListCronJobsRequest)(nil),          // 19: rpc.ListCronJobsRequest
	(*ListCronJobsResponse)(nil),         // 20: rpc.ListCronJobsResponse
	(*RunCronJobRequest)(nil),            // 21: rpc.RunCronJobRequest
	(*RunCronJobResponse)(nil),           // 22: rpc.RunCronJobResponse
	(*AnswerQuestionRequest)(nil),        // 23: rpc.AnswerQuestionRequest
	(*AnswerQuestionResponse)(nil),       // 24: rpc.AnswerQuestionResponse
	(*ConfigModel)(nil),                  // 25: rpc.ConfigModel
	(*ConfigChannel)(nil),                // 26: rpc.ConfigChannel
	(*ConfigView)(nil),                   // 27: rpc.ConfigView
	(*ListConfigRequest)(nil),            // 28: rpc.ListConfigRequest
	(*ListConfigResponse)(nil),           // 29: rpc.ListConfigResponse
	(*SettleSessionRequest)(nil),         // 30: rpc.SettleSessionRequest
	(*SettleSessionResponse)(nil),        // 31: rpc.SettleSessionResponse
	(*ProtocolRequest)(nil),              // 32: rpc.ProtocolRequest
	(*ProtocolResponse)(nil),             // 33: rpc.ProtocolResponse
	(*QueueItem)(nil),                    // 34: rpc.QueueItem
	(*ListQueueRequest)(nil),             // 35: rpc.ListQueueRequest
	(*ListQueueResponse)(nil),            // 36: rpc.ListQueueResponse
	(*QueueItemRequest)(nil),             // 37: rpc.QueueItemRequest
	(*QueueItemResponse)(nil),            // 38: rpc.QueueItemResponse
	(*ReorderQueueRequest)(nil),          // 39: rpc.ReorderQueueRequest
	(*SessionEntriesRequest)(nil),        // 40: rpc.SessionEntriesRequest
	(*SessionEntryMeta)(nil),             // 41: rpc.SessionEntryMeta
	(*ListSessionEntriesResponse)(nil),   // 42: rpc.ListSessionEntriesResponse
	(*SessionEntryData)(nil),             // 43: rpc.SessionEntryData
	(*LoadSessionEntriesResponse)(nil),   // 44: rpc.LoadSessionEntriesResponse
	(*DeleteSessionEntriesResponse)(nil), // 45: rpc.DeleteSessionEntriesResponse
}
var file_web_proto_depIdxs = []int32{
	9,  // 0: rpc.HistoryResponse.messages:type_name -> rpc.TranscriptEvent
	2,  // 1: rpc.ListSessionsResponse.sessions:type_name -> rpc.Session
	0,  // 2: rpc.PromptRequest.delivery:type_name -> rpc.PromptDelivery
	13, // 3: rpc.ListAgentsResponse.agents:type_name -> rpc.Agent
	16, // 4: rpc.ListSkillsResponse.skills:type_name -> rpc.Skill
	12, // 5: rpc.ListCronJobsResponse.jobs:type_name -> rpc.CronJob
	25, // 6: rpc.ConfigView.models:type_name -> rpc.ConfigModel
	26, // 7: rpc.ConfigView.slack_channels:type_name -> rpc.ConfigChannel
	27, // 8: rpc.ListConfigResponse.config:type_name -> rpc.ConfigView
	34, // 9: rpc.ListQueueResponse.items:type_name -> rpc.QueueItem
	41, // 10: rpc.ListSessionEntriesResponse.entries:type_name -> rpc.SessionEntryMeta
	43, // 11: rpc.LoadSessionEntriesResponse.entries:type_name -> rpc.SessionEntryData
	1,  // 12: rpc.Web.ListSessions:input_type -> rpc.ListSessionsRequest
	6,  // 13: rpc.Web.CreateSession:input_type -> rpc.CreateSessionRequest
	8,  // 14: rpc.Web.Join:input_type -> rpc.JoinRequest
	10, // 15: rpc.Web.Prompt:input_type -> rpc.PromptRequest
	19, // 16: rpc.Web.ListCronJobs:input_type -> rpc.ListCronJobsRequest
	21, // 17: rpc.Web.RunCronJob:input_type -> rpc.RunCronJobRequest
	23, // 18: rpc.Web.AnswerQuestion:input_type -> rpc.AnswerQuestionRequest
	3,  // 19: rpc.Web.History:input_type -> rpc.HistoryRequest
	14, // 20: rpc.Web.ListAgents:input_type -> rpc.ListAgentsRequest
	17, // 21: rpc.Web.ListSkills:input_type -> rpc.ListSkillsRequest
	28, // 22: rpc.Web.ListConfig:input_type -> rpc.ListConfigRequest
	30, // 23: rpc.Web.SettleSession:input_type -> rpc.SettleSessionRequest
	32, // 24: rpc.Web.Protocol:input_type -> rpc.ProtocolRequest
	35, // 25: rpc.Web.ListQueue:input_type -> rpc.ListQueueRequest
	37, // 26: rpc.Web.RemoveQueueItem:input_type -> rpc.QueueItemRequest
	37, // 27: rpc.Web.SteerQueueItem:input_type -> rpc.QueueItemRequest
	39, // 28: rpc.Web.ReorderQueue:input_type -> rpc.ReorderQueueRequest
	40, // 29: rpc.Web.ListSessionEntries:input_type -> rpc.SessionEntriesRequest
	40, // 30: rpc.Web.LoadSessionEntries:input_type -> rpc.SessionEntriesRequest
	40, // 31: rpc.Web.DeleteSessionEntries:input_type -> rpc.SessionEntriesRequest
	5,  // 32: rpc.Web.ListSessions:output_type -> rpc.ListSessionsResponse
	7,  // 33: rpc.Web.CreateSession:output_type -> rpc.CreateSessionResponse
	9,  // 34: rpc.Web.Join:output_type -> rpc.TranscriptEvent
	11, // 35: rpc.Web.Prompt:output_type -> rpc.PromptResponse
	20, // 36: rpc.Web.ListCronJobs:output_type -> rpc.ListCronJobsResponse
	22, // 37: rpc.Web.RunCronJob:output_type -> rpc.RunCronJobResponse
	24, // 38: rpc.Web.AnswerQuestion:output_type -> rpc.AnswerQuestionResponse
	4,  // 39: rpc.Web.History:output_type -> rpc.HistoryResponse
	15, // 40: rpc.Web.ListAgents:output_type -> rpc.ListAgentsResponse
	18, // 41: rpc.Web.ListSkills:output_type -> rpc.ListSkillsResponse
	29, // 42: rpc.Web.ListConfig:output_type -> rpc.ListConfigResponse
	31, // 43: rpc.Web.SettleSession:output_type -> rpc.SettleSessionResponse
	33, // 44: rpc.Web.Protocol:output_type -> rpc.ProtocolResponse
	36, // 45: rpc.Web.ListQueue:output_type -> rpc.ListQueueResponse
	38, // 46: rpc.Web.RemoveQueueItem:output_type -> rpc.QueueItemResponse
	38, // 47: rpc.Web.SteerQueueItem:output_type -> rpc.QueueItemResponse
	38, // 48: rpc.Web.ReorderQueue:output_type -> rpc.QueueItemResponse
	42, // 49: rpc.Web.ListSessionEntries:output_type -> rpc.ListSessionEntriesResponse
	44, // 50: rpc.Web.LoadSessionEntries:output_type -> rpc.LoadSessionEntriesResponse
	45, // 51: rpc.Web.DeleteSessionEntries:output_type -> rpc.DeleteSessionEntriesResponse
	32, // [32:52] is the sub-list for method output_type
	12, // [12:32] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_web_proto_init() }
func file_web_proto_init() {
	if File_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_proto_goTypes,
		DependencyIndexes: file_web_proto_depIdxs,
		EnumInfos:         file_web_proto_enumTypes,
		MessageInfos:      file_web_proto_msgTypes,
	}.Build()
	File_web_proto = out.File
	file_web_proto_goTypes = nil
	file_web_proto_depIdxs = nil
}
