// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"context"
	"encoding/json"
	"sync"
)

// Ensure that mockCheckpointSink does implement CheckpointSink.
// If this is not the case, regenerate this file with mockery.
var _ CheckpointSink = &mockCheckpointSink{}

// mockCheckpointSink is a mock implementation of CheckpointSink.
//
//	func TestSomethingThatUsesCheckpointSink(t *testing.T) {
//
//		// make and configure a mocked CheckpointSink
//		mockedCheckpointSink := &mockCheckpointSink{
//			ClearCompletedTurnFunc: func(context1 context.Context, s string) error {
//				panic("mock out the ClearCompletedTurn method")
//			},
//			CloseActiveTurnFunc: func(context1 context.Context, s string, publicProgressState PublicProgressState) error {
//				panic("mock out the CloseActiveTurn method")
//			},
//			RecordCompletedToolOutputFunc: func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
//				panic("mock out the RecordCompletedToolOutput method")
//			},
//			RecordOutputTraceFunc: func(context1 context.Context, s string, rawMessages []json.RawMessage) error {
//				panic("mock out the RecordOutputTrace method")
//			},
//			RecordProviderResponseFunc: func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
//				panic("mock out the RecordProviderResponse method")
//			},
//			RecordRecoveredReplayFunc: func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
//				panic("mock out the RecordRecoveredReplay method")
//			},
//			StartActiveTurnFunc: func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
//				panic("mock out the StartActiveTurn method")
//			},
//		}
//
//		// use mockedCheckpointSink in code that requires CheckpointSink
//		// and then make assertions.
//
//	}
type mockCheckpointSink struct {
	// ClearCompletedTurnFunc mocks the ClearCompletedTurn method.
	ClearCompletedTurnFunc func(context1 context.Context, s string) error

	// CloseActiveTurnFunc mocks the CloseActiveTurn method.
	CloseActiveTurnFunc func(context1 context.Context, s string, publicProgressState PublicProgressState) error

	// RecordCompletedToolOutputFunc mocks the RecordCompletedToolOutput method.
	RecordCompletedToolOutputFunc func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error

	// RecordOutputTraceFunc mocks the RecordOutputTrace method.
	RecordOutputTraceFunc func(context1 context.Context, s string, rawMessages []json.RawMessage) error

	// RecordProviderResponseFunc mocks the RecordProviderResponse method.
	RecordProviderResponseFunc func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error

	// RecordRecoveredReplayFunc mocks the RecordRecoveredReplay method.
	RecordRecoveredReplayFunc func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error

	// StartActiveTurnFunc mocks the StartActiveTurn method.
	StartActiveTurnFunc func(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearCompletedTurn holds details about calls to the ClearCompletedTurn method.
		ClearCompletedTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// CloseActiveTurn holds details about calls to the CloseActiveTurn method.
		CloseActiveTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// PublicProgressState is the publicProgressState argument value.
			PublicProgressState PublicProgressState
		}
		// RecordCompletedToolOutput holds details about calls to the RecordCompletedToolOutput method.
		RecordCompletedToolOutput []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ActiveTurnCheckpoint is the activeTurnCheckpoint argument value.
			ActiveTurnCheckpoint *ActiveTurnCheckpoint
		}
		// RecordOutputTrace holds details about calls to the RecordOutputTrace method.
		RecordOutputTrace []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// RawMessages is the rawMessages argument value.
			RawMessages []json.RawMessage
		}
		// RecordProviderResponse holds details about calls to the RecordProviderResponse method.
		RecordProviderResponse []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ActiveTurnCheckpoint is the activeTurnCheckpoint argument value.
			ActiveTurnCheckpoint *ActiveTurnCheckpoint
		}
		// RecordRecoveredReplay holds details about calls to the RecordRecoveredReplay method.
		RecordRecoveredReplay []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ActiveTurnCheckpoint is the activeTurnCheckpoint argument value.
			ActiveTurnCheckpoint *ActiveTurnCheckpoint
		}
		// StartActiveTurn holds details about calls to the StartActiveTurn method.
		StartActiveTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// ActiveTurnCheckpoint is the activeTurnCheckpoint argument value.
			ActiveTurnCheckpoint *ActiveTurnCheckpoint
		}
	}
	lockClearCompletedTurn        sync.RWMutex
	lockCloseActiveTurn           sync.RWMutex
	lockRecordCompletedToolOutput sync.RWMutex
	lockRecordOutputTrace         sync.RWMutex
	lockRecordProviderResponse    sync.RWMutex
	lockRecordRecoveredReplay     sync.RWMutex
	lockStartActiveTurn           sync.RWMutex
}

// ClearCompletedTurn calls ClearCompletedTurnFunc.
func (mock *mockCheckpointSink) ClearCompletedTurn(context1 context.Context, s string) error {
	if mock.ClearCompletedTurnFunc == nil {
		panic("mockCheckpointSink.ClearCompletedTurnFunc: method is nil but CheckpointSink.ClearCompletedTurn was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockClearCompletedTurn.Lock()
	mock.calls.ClearCompletedTurn = append(mock.calls.ClearCompletedTurn, callInfo)
	mock.lockClearCompletedTurn.Unlock()
	return mock.ClearCompletedTurnFunc(context1, s)
}

// ClearCompletedTurnCalls gets all the calls that were made to ClearCompletedTurn.
// Check the length with:
//
//	len(mockedCheckpointSink.ClearCompletedTurnCalls())
func (mock *mockCheckpointSink) ClearCompletedTurnCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockClearCompletedTurn.RLock()
	calls = mock.calls.ClearCompletedTurn
	mock.lockClearCompletedTurn.RUnlock()
	return calls
}

// CloseActiveTurn calls CloseActiveTurnFunc.
func (mock *mockCheckpointSink) CloseActiveTurn(context1 context.Context, s string, publicProgressState PublicProgressState) error {
	if mock.CloseActiveTurnFunc == nil {
		panic("mockCheckpointSink.CloseActiveTurnFunc: method is nil but CheckpointSink.CloseActiveTurn was just called")
	}
	callInfo := struct {
		Context1            context.Context
		S                   string
		PublicProgressState PublicProgressState
	}{
		Context1:            context1,
		S:                   s,
		PublicProgressState: publicProgressState,
	}
	mock.lockCloseActiveTurn.Lock()
	mock.calls.CloseActiveTurn = append(mock.calls.CloseActiveTurn, callInfo)
	mock.lockCloseActiveTurn.Unlock()
	return mock.CloseActiveTurnFunc(context1, s, publicProgressState)
}

// CloseActiveTurnCalls gets all the calls that were made to CloseActiveTurn.
// Check the length with:
//
//	len(mockedCheckpointSink.CloseActiveTurnCalls())
func (mock *mockCheckpointSink) CloseActiveTurnCalls() []struct {
	Context1            context.Context
	S                   string
	PublicProgressState PublicProgressState
} {
	var calls []struct {
		Context1            context.Context
		S                   string
		PublicProgressState PublicProgressState
	}
	mock.lockCloseActiveTurn.RLock()
	calls = mock.calls.CloseActiveTurn
	mock.lockCloseActiveTurn.RUnlock()
	return calls
}

// RecordCompletedToolOutput calls RecordCompletedToolOutputFunc.
func (mock *mockCheckpointSink) RecordCompletedToolOutput(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
	if mock.RecordCompletedToolOutputFunc == nil {
		panic("mockCheckpointSink.RecordCompletedToolOutputFunc: method is nil but CheckpointSink.RecordCompletedToolOutput was just called")
	}
	callInfo := struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}{
		Context1:             context1,
		ActiveTurnCheckpoint: activeTurnCheckpoint,
	}
	mock.lockRecordCompletedToolOutput.Lock()
	mock.calls.RecordCompletedToolOutput = append(mock.calls.RecordCompletedToolOutput, callInfo)
	mock.lockRecordCompletedToolOutput.Unlock()
	return mock.RecordCompletedToolOutputFunc(context1, activeTurnCheckpoint)
}

// RecordCompletedToolOutputCalls gets all the calls that were made to RecordCompletedToolOutput.
// Check the length with:
//
//	len(mockedCheckpointSink.RecordCompletedToolOutputCalls())
func (mock *mockCheckpointSink) RecordCompletedToolOutputCalls() []struct {
	Context1             context.Context
	ActiveTurnCheckpoint *ActiveTurnCheckpoint
} {
	var calls []struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}
	mock.lockRecordCompletedToolOutput.RLock()
	calls = mock.calls.RecordCompletedToolOutput
	mock.lockRecordCompletedToolOutput.RUnlock()
	return calls
}

// RecordOutputTrace calls RecordOutputTraceFunc.
func (mock *mockCheckpointSink) RecordOutputTrace(context1 context.Context, s string, rawMessages []json.RawMessage) error {
	if mock.RecordOutputTraceFunc == nil {
		panic("mockCheckpointSink.RecordOutputTraceFunc: method is nil but CheckpointSink.RecordOutputTrace was just called")
	}
	callInfo := struct {
		Context1    context.Context
		S           string
		RawMessages []json.RawMessage
	}{
		Context1:    context1,
		S:           s,
		RawMessages: rawMessages,
	}
	mock.lockRecordOutputTrace.Lock()
	mock.calls.RecordOutputTrace = append(mock.calls.RecordOutputTrace, callInfo)
	mock.lockRecordOutputTrace.Unlock()
	return mock.RecordOutputTraceFunc(context1, s, rawMessages)
}

// RecordOutputTraceCalls gets all the calls that were made to RecordOutputTrace.
// Check the length with:
//
//	len(mockedCheckpointSink.RecordOutputTraceCalls())
func (mock *mockCheckpointSink) RecordOutputTraceCalls() []struct {
	Context1    context.Context
	S           string
	RawMessages []json.RawMessage
} {
	var calls []struct {
		Context1    context.Context
		S           string
		RawMessages []json.RawMessage
	}
	mock.lockRecordOutputTrace.RLock()
	calls = mock.calls.RecordOutputTrace
	mock.lockRecordOutputTrace.RUnlock()
	return calls
}

// RecordProviderResponse calls RecordProviderResponseFunc.
func (mock *mockCheckpointSink) RecordProviderResponse(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
	if mock.RecordProviderResponseFunc == nil {
		panic("mockCheckpointSink.RecordProviderResponseFunc: method is nil but CheckpointSink.RecordProviderResponse was just called")
	}
	callInfo := struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}{
		Context1:             context1,
		ActiveTurnCheckpoint: activeTurnCheckpoint,
	}
	mock.lockRecordProviderResponse.Lock()
	mock.calls.RecordProviderResponse = append(mock.calls.RecordProviderResponse, callInfo)
	mock.lockRecordProviderResponse.Unlock()
	return mock.RecordProviderResponseFunc(context1, activeTurnCheckpoint)
}

// RecordProviderResponseCalls gets all the calls that were made to RecordProviderResponse.
// Check the length with:
//
//	len(mockedCheckpointSink.RecordProviderResponseCalls())
func (mock *mockCheckpointSink) RecordProviderResponseCalls() []struct {
	Context1             context.Context
	ActiveTurnCheckpoint *ActiveTurnCheckpoint
} {
	var calls []struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}
	mock.lockRecordProviderResponse.RLock()
	calls = mock.calls.RecordProviderResponse
	mock.lockRecordProviderResponse.RUnlock()
	return calls
}

// RecordRecoveredReplay calls RecordRecoveredReplayFunc.
func (mock *mockCheckpointSink) RecordRecoveredReplay(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
	if mock.RecordRecoveredReplayFunc == nil {
		panic("mockCheckpointSink.RecordRecoveredReplayFunc: method is nil but CheckpointSink.RecordRecoveredReplay was just called")
	}
	callInfo := struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}{
		Context1:             context1,
		ActiveTurnCheckpoint: activeTurnCheckpoint,
	}
	mock.lockRecordRecoveredReplay.Lock()
	mock.calls.RecordRecoveredReplay = append(mock.calls.RecordRecoveredReplay, callInfo)
	mock.lockRecordRecoveredReplay.Unlock()
	return mock.RecordRecoveredReplayFunc(context1, activeTurnCheckpoint)
}

// RecordRecoveredReplayCalls gets all the calls that were made to RecordRecoveredReplay.
// Check the length with:
//
//	len(mockedCheckpointSink.RecordRecoveredReplayCalls())
func (mock *mockCheckpointSink) RecordRecoveredReplayCalls() []struct {
	Context1             context.Context
	ActiveTurnCheckpoint *ActiveTurnCheckpoint
} {
	var calls []struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}
	mock.lockRecordRecoveredReplay.RLock()
	calls = mock.calls.RecordRecoveredReplay
	mock.lockRecordRecoveredReplay.RUnlock()
	return calls
}

// StartActiveTurn calls StartActiveTurnFunc.
func (mock *mockCheckpointSink) StartActiveTurn(context1 context.Context, activeTurnCheckpoint *ActiveTurnCheckpoint) error {
	if mock.StartActiveTurnFunc == nil {
		panic("mockCheckpointSink.StartActiveTurnFunc: method is nil but CheckpointSink.StartActiveTurn was just called")
	}
	callInfo := struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}{
		Context1:             context1,
		ActiveTurnCheckpoint: activeTurnCheckpoint,
	}
	mock.lockStartActiveTurn.Lock()
	mock.calls.StartActiveTurn = append(mock.calls.StartActiveTurn, callInfo)
	mock.lockStartActiveTurn.Unlock()
	return mock.StartActiveTurnFunc(context1, activeTurnCheckpoint)
}

// StartActiveTurnCalls gets all the calls that were made to StartActiveTurn.
// Check the length with:
//
//	len(mockedCheckpointSink.StartActiveTurnCalls())
func (mock *mockCheckpointSink) StartActiveTurnCalls() []struct {
	Context1             context.Context
	ActiveTurnCheckpoint *ActiveTurnCheckpoint
} {
	var calls []struct {
		Context1             context.Context
		ActiveTurnCheckpoint *ActiveTurnCheckpoint
	}
	mock.lockStartActiveTurn.RLock()
	calls = mock.calls.StartActiveTurn
	mock.lockStartActiveTurn.RUnlock()
	return calls
}
