// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"sync"

	"github.com/NVIDIA/OpenShell/sdk/go/openshell/v1"
)

// Ensure that mockExecStream does implement v1.ExecStream.
// If this is not the case, regenerate this file with mockery.
var _ v1.ExecStream = &mockExecStream{}

// mockExecStream is a mock implementation of v1.ExecStream.
//
//	func TestSomethingThatUsesExecStream(t *testing.T) {
//
//		// make and configure a mocked v1.ExecStream
//		mockedExecStream := &mockExecStream{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			ExitCodeFunc: func() (int, error) {
//				panic("mock out the ExitCode method")
//			},
//			NextFunc: func() (*v1.ExecChunk, error) {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedExecStream in code that requires v1.ExecStream
//		// and then make assertions.
//
//	}
type mockExecStream struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// ExitCodeFunc mocks the ExitCode method.
	ExitCodeFunc func() (int, error)

	// NextFunc mocks the Next method.
	NextFunc func() (*v1.ExecChunk, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ExitCode holds details about calls to the ExitCode method.
		ExitCode []struct {
		}
		// Next holds details about calls to the Next method.
		Next []struct {
		}
	}
	lockClose    sync.RWMutex
	lockExitCode sync.RWMutex
	lockNext     sync.RWMutex
}

// Close calls CloseFunc.
func (mock *mockExecStream) Close() error {
	if mock.CloseFunc == nil {
		panic("mockExecStream.CloseFunc: method is nil but ExecStream.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedExecStream.CloseCalls())
func (mock *mockExecStream) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ExitCode calls ExitCodeFunc.
func (mock *mockExecStream) ExitCode() (int, error) {
	if mock.ExitCodeFunc == nil {
		panic("mockExecStream.ExitCodeFunc: method is nil but ExecStream.ExitCode was just called")
	}
	callInfo := struct {
	}{}
	mock.lockExitCode.Lock()
	mock.calls.ExitCode = append(mock.calls.ExitCode, callInfo)
	mock.lockExitCode.Unlock()
	return mock.ExitCodeFunc()
}

// ExitCodeCalls gets all the calls that were made to ExitCode.
// Check the length with:
//
//	len(mockedExecStream.ExitCodeCalls())
func (mock *mockExecStream) ExitCodeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockExitCode.RLock()
	calls = mock.calls.ExitCode
	mock.lockExitCode.RUnlock()
	return calls
}

// Next calls NextFunc.
func (mock *mockExecStream) Next() (*v1.ExecChunk, error) {
	if mock.NextFunc == nil {
		panic("mockExecStream.NextFunc: method is nil but ExecStream.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedExecStream.NextCalls())
func (mock *mockExecStream) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}
