// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"context"
	"sync"

	"github.com/NVIDIA/OpenShell/sdk/go/openshell/v1"
)

// Ensure that mockExecInterface does implement v1.ExecInterface.
// If this is not the case, regenerate this file with mockery.
var _ v1.ExecInterface = &mockExecInterface{}

// mockExecInterface is a mock implementation of v1.ExecInterface.
//
//	func TestSomethingThatUsesExecInterface(t *testing.T) {
//
//		// make and configure a mocked v1.ExecInterface
//		mockedExecInterface := &mockExecInterface{
//			InteractiveFunc: func(ctx context.Context, workspace string, sandboxName string, command []string, cols uint32, rows uint32, opts ...v1.ExecOptions) (v1.InteractiveSession, error) {
//				panic("mock out the Interactive method")
//			},
//			RunFunc: func(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (*v1.ExecResult, error) {
//				panic("mock out the Run method")
//			},
//			StreamFunc: func(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (v1.ExecStream, error) {
//				panic("mock out the Stream method")
//			},
//		}
//
//		// use mockedExecInterface in code that requires v1.ExecInterface
//		// and then make assertions.
//
//	}
type mockExecInterface struct {
	// InteractiveFunc mocks the Interactive method.
	InteractiveFunc func(ctx context.Context, workspace string, sandboxName string, command []string, cols uint32, rows uint32, opts ...v1.ExecOptions) (v1.InteractiveSession, error)

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (*v1.ExecResult, error)

	// StreamFunc mocks the Stream method.
	StreamFunc func(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (v1.ExecStream, error)

	// calls tracks calls to the methods.
	calls struct {
		// Interactive holds details about calls to the Interactive method.
		Interactive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Command is the command argument value.
			Command []string
			// Cols is the cols argument value.
			Cols uint32
			// Rows is the rows argument value.
			Rows uint32
			// Opts is the opts argument value.
			Opts []v1.ExecOptions
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Command is the command argument value.
			Command []string
			// Opts is the opts argument value.
			Opts []v1.ExecOptions
		}
		// Stream holds details about calls to the Stream method.
		Stream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Command is the command argument value.
			Command []string
			// Opts is the opts argument value.
			Opts []v1.ExecOptions
		}
	}
	lockInteractive sync.RWMutex
	lockRun         sync.RWMutex
	lockStream      sync.RWMutex
}

// Interactive calls InteractiveFunc.
func (mock *mockExecInterface) Interactive(ctx context.Context, workspace string, sandboxName string, command []string, cols uint32, rows uint32, opts ...v1.ExecOptions) (v1.InteractiveSession, error) {
	if mock.InteractiveFunc == nil {
		panic("mockExecInterface.InteractiveFunc: method is nil but ExecInterface.Interactive was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Cols        uint32
		Rows        uint32
		Opts        []v1.ExecOptions
	}{
		Ctx:         ctx,
		Workspace:   workspace,
		SandboxName: sandboxName,
		Command:     command,
		Cols:        cols,
		Rows:        rows,
		Opts:        opts,
	}
	mock.lockInteractive.Lock()
	mock.calls.Interactive = append(mock.calls.Interactive, callInfo)
	mock.lockInteractive.Unlock()
	return mock.InteractiveFunc(ctx, workspace, sandboxName, command, cols, rows, opts...)
}

// InteractiveCalls gets all the calls that were made to Interactive.
// Check the length with:
//
//	len(mockedExecInterface.InteractiveCalls())
func (mock *mockExecInterface) InteractiveCalls() []struct {
	Ctx         context.Context
	Workspace   string
	SandboxName string
	Command     []string
	Cols        uint32
	Rows        uint32
	Opts        []v1.ExecOptions
} {
	var calls []struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Cols        uint32
		Rows        uint32
		Opts        []v1.ExecOptions
	}
	mock.lockInteractive.RLock()
	calls = mock.calls.Interactive
	mock.lockInteractive.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *mockExecInterface) Run(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (*v1.ExecResult, error) {
	if mock.RunFunc == nil {
		panic("mockExecInterface.RunFunc: method is nil but ExecInterface.Run was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Opts        []v1.ExecOptions
	}{
		Ctx:         ctx,
		Workspace:   workspace,
		SandboxName: sandboxName,
		Command:     command,
		Opts:        opts,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, workspace, sandboxName, command, opts...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedExecInterface.RunCalls())
func (mock *mockExecInterface) RunCalls() []struct {
	Ctx         context.Context
	Workspace   string
	SandboxName string
	Command     []string
	Opts        []v1.ExecOptions
} {
	var calls []struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Opts        []v1.ExecOptions
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Stream calls StreamFunc.
func (mock *mockExecInterface) Stream(ctx context.Context, workspace string, sandboxName string, command []string, opts ...v1.ExecOptions) (v1.ExecStream, error) {
	if mock.StreamFunc == nil {
		panic("mockExecInterface.StreamFunc: method is nil but ExecInterface.Stream was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Opts        []v1.ExecOptions
	}{
		Ctx:         ctx,
		Workspace:   workspace,
		SandboxName: sandboxName,
		Command:     command,
		Opts:        opts,
	}
	mock.lockStream.Lock()
	mock.calls.Stream = append(mock.calls.Stream, callInfo)
	mock.lockStream.Unlock()
	return mock.StreamFunc(ctx, workspace, sandboxName, command, opts...)
}

// StreamCalls gets all the calls that were made to Stream.
// Check the length with:
//
//	len(mockedExecInterface.StreamCalls())
func (mock *mockExecInterface) StreamCalls() []struct {
	Ctx         context.Context
	Workspace   string
	SandboxName string
	Command     []string
	Opts        []v1.ExecOptions
} {
	var calls []struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Command     []string
		Opts        []v1.ExecOptions
	}
	mock.lockStream.RLock()
	calls = mock.calls.Stream
	mock.lockStream.RUnlock()
	return calls
}
