// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"context"
	"encoding/json"
	"sync"
)

// Ensure that mockJournal does implement Journal.
// If this is not the case, regenerate this file with mockery.
var _ Journal = &mockJournal{}

// mockJournal is a mock implementation of Journal.
//
//	func TestSomethingThatUsesJournal(t *testing.T) {
//
//		// make and configure a mocked Journal
//		mockedJournal := &mockJournal{
//			LoadFunc: func(ctx context.Context, key string) (json.RawMessage, bool, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(ctx context.Context, key string, value json.RawMessage) error {
//				panic("mock out the Save method")
//			},
//			SaveTraceFunc: func(ctx context.Context, turnID string, trace []json.RawMessage) error {
//				panic("mock out the SaveTrace method")
//			},
//		}
//
//		// use mockedJournal in code that requires Journal
//		// and then make assertions.
//
//	}
type mockJournal struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(ctx context.Context, key string) (json.RawMessage, bool, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, key string, value json.RawMessage) error

	// SaveTraceFunc mocks the SaveTrace method.
	SaveTraceFunc func(ctx context.Context, turnID string, trace []json.RawMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value json.RawMessage
		}
		// SaveTrace holds details about calls to the SaveTrace method.
		SaveTrace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TurnID is the turnID argument value.
			TurnID string
			// Trace is the trace argument value.
			Trace []json.RawMessage
		}
	}
	lockLoad      sync.RWMutex
	lockSave      sync.RWMutex
	lockSaveTrace sync.RWMutex
}

// Load calls LoadFunc.
func (mock *mockJournal) Load(ctx context.Context, key string) (json.RawMessage, bool, error) {
	if mock.LoadFunc == nil {
		panic("mockJournal.LoadFunc: method is nil but Journal.Load was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(ctx, key)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedJournal.LoadCalls())
func (mock *mockJournal) LoadCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *mockJournal) Save(ctx context.Context, key string, value json.RawMessage) error {
	if mock.SaveFunc == nil {
		panic("mockJournal.SaveFunc: method is nil but Journal.Save was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value json.RawMessage
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, key, value)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedJournal.SaveCalls())
func (mock *mockJournal) SaveCalls() []struct {
	Ctx   context.Context
	Key   string
	Value json.RawMessage
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value json.RawMessage
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// SaveTrace calls SaveTraceFunc.
func (mock *mockJournal) SaveTrace(ctx context.Context, turnID string, trace []json.RawMessage) error {
	if mock.SaveTraceFunc == nil {
		panic("mockJournal.SaveTraceFunc: method is nil but Journal.SaveTrace was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		TurnID string
		Trace  []json.RawMessage
	}{
		Ctx:    ctx,
		TurnID: turnID,
		Trace:  trace,
	}
	mock.lockSaveTrace.Lock()
	mock.calls.SaveTrace = append(mock.calls.SaveTrace, callInfo)
	mock.lockSaveTrace.Unlock()
	return mock.SaveTraceFunc(ctx, turnID, trace)
}

// SaveTraceCalls gets all the calls that were made to SaveTrace.
// Check the length with:
//
//	len(mockedJournal.SaveTraceCalls())
func (mock *mockJournal) SaveTraceCalls() []struct {
	Ctx    context.Context
	TurnID string
	Trace  []json.RawMessage
} {
	var calls []struct {
		Ctx    context.Context
		TurnID string
		Trace  []json.RawMessage
	}
	mock.lockSaveTrace.RLock()
	calls = mock.calls.SaveTrace
	mock.lockSaveTrace.RUnlock()
	return calls
}
