// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"context"
	"sync"
)

// Ensure that mockPermissionReviewer does implement permissionReviewer.
// If this is not the case, regenerate this file with mockery.
var _ permissionReviewer = &mockPermissionReviewer{}

// mockPermissionReviewer is a mock implementation of permissionReviewer.
//
//	func TestSomethingThatUsespermissionReviewer(t *testing.T) {
//
//		// make and configure a mocked permissionReviewer
//		mockedpermissionReviewer := &mockPermissionReviewer{
//			reviewPermissionFunc: func(context1 context.Context, permissionReviewRequestMoqParam *permissionReviewRequest, chatResponseCh chan<- ChatResponse) permissionReviewDecision {
//				panic("mock out the reviewPermission method")
//			},
//		}
//
//		// use mockedpermissionReviewer in code that requires permissionReviewer
//		// and then make assertions.
//
//	}
type mockPermissionReviewer struct {
	// reviewPermissionFunc mocks the reviewPermission method.
	reviewPermissionFunc func(context1 context.Context, permissionReviewRequestMoqParam *permissionReviewRequest, chatResponseCh chan<- ChatResponse) permissionReviewDecision

	// calls tracks calls to the methods.
	calls struct {
		// reviewPermission holds details about calls to the reviewPermission method.
		reviewPermission []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// PermissionReviewRequestMoqParam is the permissionReviewRequestMoqParam argument value.
			PermissionReviewRequestMoqParam *permissionReviewRequest
			// ChatResponseCh is the chatResponseCh argument value.
			ChatResponseCh chan<- ChatResponse
		}
	}
	lockreviewPermission sync.RWMutex
}

// reviewPermission calls reviewPermissionFunc.
func (mock *mockPermissionReviewer) reviewPermission(context1 context.Context, permissionReviewRequestMoqParam *permissionReviewRequest, chatResponseCh chan<- ChatResponse) permissionReviewDecision {
	if mock.reviewPermissionFunc == nil {
		panic("mockPermissionReviewer.reviewPermissionFunc: method is nil but permissionReviewer.reviewPermission was just called")
	}
	callInfo := struct {
		Context1                        context.Context
		PermissionReviewRequestMoqParam *permissionReviewRequest
		ChatResponseCh                  chan<- ChatResponse
	}{
		Context1:                        context1,
		PermissionReviewRequestMoqParam: permissionReviewRequestMoqParam,
		ChatResponseCh:                  chatResponseCh,
	}
	mock.lockreviewPermission.Lock()
	mock.calls.reviewPermission = append(mock.calls.reviewPermission, callInfo)
	mock.lockreviewPermission.Unlock()
	return mock.reviewPermissionFunc(context1, permissionReviewRequestMoqParam, chatResponseCh)
}

// reviewPermissionCalls gets all the calls that were made to reviewPermission.
// Check the length with:
//
//	len(mockedpermissionReviewer.reviewPermissionCalls())
func (mock *mockPermissionReviewer) reviewPermissionCalls() []struct {
	Context1                        context.Context
	PermissionReviewRequestMoqParam *permissionReviewRequest
	ChatResponseCh                  chan<- ChatResponse
} {
	var calls []struct {
		Context1                        context.Context
		PermissionReviewRequestMoqParam *permissionReviewRequest
		ChatResponseCh                  chan<- ChatResponse
	}
	mock.lockreviewPermission.RLock()
	calls = mock.calls.reviewPermission
	mock.lockreviewPermission.RUnlock()
	return calls
}
