// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package rocketcode

import (
	"context"
	"sync"

	"github.com/NVIDIA/OpenShell/sdk/go/openshell/v1"
)

// Ensure that mockSandboxInterface does implement v1.SandboxInterface.
// If this is not the case, regenerate this file with mockery.
var _ v1.SandboxInterface = &mockSandboxInterface{}

// mockSandboxInterface is a mock implementation of v1.SandboxInterface.
//
//	func TestSomethingThatUsesSandboxInterface(t *testing.T) {
//
//		// make and configure a mocked v1.SandboxInterface
//		mockedSandboxInterface := &mockSandboxInterface{
//			AttachProviderFunc: func(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.AttachProviderResult, error) {
//				panic("mock out the AttachProvider method")
//			},
//			CreateFunc: func(ctx context.Context, workspace string, name string, spec *v1.SandboxSpec, labels map[string]string, opts ...v1.CreateOptions) (*v1.Sandbox, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, workspace string, name string, opts ...v1.DeleteOptions) (*v1.DeletionResult, error) {
//				panic("mock out the Delete method")
//			},
//			DetachProviderFunc: func(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.DetachProviderResult, error) {
//				panic("mock out the DetachProvider method")
//			},
//			GetFunc: func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
//				panic("mock out the Get method")
//			},
//			GetLogsFunc: func(ctx context.Context, workspace string, sandboxName string, opts ...v1.LogOption) (*v1.LogResult, error) {
//				panic("mock out the GetLogs method")
//			},
//			ListFunc: func(workspace string, opts ...v1.ListOptions) (*v1.Pager[*v1.Sandbox], error) {
//				panic("mock out the List method")
//			},
//			ListAllFunc: func(ctx context.Context, workspace string, opts ...v1.ListOptions) ([]*v1.Sandbox, error) {
//				panic("mock out the ListAll method")
//			},
//			ListAllProvidersFunc: func(ctx context.Context, workspace string, sandboxName string, opts ...v1.ListOptions) ([]*v1.Provider, error) {
//				panic("mock out the ListAllProviders method")
//			},
//			ListProvidersFunc: func(workspace string, sandboxName string, opts ...v1.ListOptions) (*v1.Pager[*v1.Provider], error) {
//				panic("mock out the ListProviders method")
//			},
//			StartFunc: func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
//				panic("mock out the Stop method")
//			},
//			WaitReadyFunc: func(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error) {
//				panic("mock out the WaitReady method")
//			},
//			WaitStoppedFunc: func(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error) {
//				panic("mock out the WaitStopped method")
//			},
//			WatchFunc: func(ctx context.Context, workspace string, name string, opts ...v1.WatchOptions) (v1.WatchInterface[*v1.Sandbox], error) {
//				panic("mock out the Watch method")
//			},
//		}
//
//		// use mockedSandboxInterface in code that requires v1.SandboxInterface
//		// and then make assertions.
//
//	}
type mockSandboxInterface struct {
	// AttachProviderFunc mocks the AttachProvider method.
	AttachProviderFunc func(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.AttachProviderResult, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, workspace string, name string, spec *v1.SandboxSpec, labels map[string]string, opts ...v1.CreateOptions) (*v1.Sandbox, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, workspace string, name string, opts ...v1.DeleteOptions) (*v1.DeletionResult, error)

	// DetachProviderFunc mocks the DetachProvider method.
	DetachProviderFunc func(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.DetachProviderResult, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error)

	// GetLogsFunc mocks the GetLogs method.
	GetLogsFunc func(ctx context.Context, workspace string, sandboxName string, opts ...v1.LogOption) (*v1.LogResult, error)

	// ListFunc mocks the List method.
	ListFunc func(workspace string, opts ...v1.ListOptions) (*v1.Pager[*v1.Sandbox], error)

	// ListAllFunc mocks the ListAll method.
	ListAllFunc func(ctx context.Context, workspace string, opts ...v1.ListOptions) ([]*v1.Sandbox, error)

	// ListAllProvidersFunc mocks the ListAllProviders method.
	ListAllProvidersFunc func(ctx context.Context, workspace string, sandboxName string, opts ...v1.ListOptions) ([]*v1.Provider, error)

	// ListProvidersFunc mocks the ListProviders method.
	ListProvidersFunc func(workspace string, sandboxName string, opts ...v1.ListOptions) (*v1.Pager[*v1.Provider], error)

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error)

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context, workspace string, name string) (*v1.Sandbox, error)

	// WaitReadyFunc mocks the WaitReady method.
	WaitReadyFunc func(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error)

	// WaitStoppedFunc mocks the WaitStopped method.
	WaitStoppedFunc func(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error)

	// WatchFunc mocks the Watch method.
	WatchFunc func(ctx context.Context, workspace string, name string, opts ...v1.WatchOptions) (v1.WatchInterface[*v1.Sandbox], error)

	// calls tracks calls to the methods.
	calls struct {
		// AttachProvider holds details about calls to the AttachProvider method.
		AttachProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// ProviderName is the providerName argument value.
			ProviderName string
			// ExpectedResourceVersion is the expectedResourceVersion argument value.
			ExpectedResourceVersion uint64
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
			// Spec is the spec argument value.
			Spec *v1.SandboxSpec
			// Labels is the labels argument value.
			Labels map[string]string
			// Opts is the opts argument value.
			Opts []v1.CreateOptions
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts []v1.DeleteOptions
		}
		// DetachProvider holds details about calls to the DetachProvider method.
		DetachProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// ProviderName is the providerName argument value.
			ProviderName string
			// ExpectedResourceVersion is the expectedResourceVersion argument value.
			ExpectedResourceVersion uint64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
		}
		// GetLogs holds details about calls to the GetLogs method.
		GetLogs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Opts is the opts argument value.
			Opts []v1.LogOption
		}
		// List holds details about calls to the List method.
		List []struct {
			// Workspace is the workspace argument value.
			Workspace string
			// Opts is the opts argument value.
			Opts []v1.ListOptions
		}
		// ListAll holds details about calls to the ListAll method.
		ListAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Opts is the opts argument value.
			Opts []v1.ListOptions
		}
		// ListAllProviders holds details about calls to the ListAllProviders method.
		ListAllProviders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Opts is the opts argument value.
			Opts []v1.ListOptions
		}
		// ListProviders holds details about calls to the ListProviders method.
		ListProviders []struct {
			// Workspace is the workspace argument value.
			Workspace string
			// SandboxName is the sandboxName argument value.
			SandboxName string
			// Opts is the opts argument value.
			Opts []v1.ListOptions
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
		}
		// WaitReady holds details about calls to the WaitReady method.
		WaitReady []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts []v1.WaitOptions
		}
		// WaitStopped holds details about calls to the WaitStopped method.
		WaitStopped []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts []v1.WaitOptions
		}
		// Watch holds details about calls to the Watch method.
		Watch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Workspace is the workspace argument value.
			Workspace string
			// Name is the name argument value.
			Name string
			// Opts is the opts argument value.
			Opts []v1.WatchOptions
		}
	}
	lockAttachProvider   sync.RWMutex
	lockCreate           sync.RWMutex
	lockDelete           sync.RWMutex
	lockDetachProvider   sync.RWMutex
	lockGet              sync.RWMutex
	lockGetLogs          sync.RWMutex
	lockList             sync.RWMutex
	lockListAll          sync.RWMutex
	lockListAllProviders sync.RWMutex
	lockListProviders    sync.RWMutex
	lockStart            sync.RWMutex
	lockStop             sync.RWMutex
	lockWaitReady        sync.RWMutex
	lockWaitStopped      sync.RWMutex
	lockWatch            sync.RWMutex
}

// AttachProvider calls AttachProviderFunc.
func (mock *mockSandboxInterface) AttachProvider(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.AttachProviderResult, error) {
	if mock.AttachProviderFunc == nil {
		panic("mockSandboxInterface.AttachProviderFunc: method is nil but SandboxInterface.AttachProvider was just called")
	}
	callInfo := struct {
		Ctx                     context.Context
		Workspace               string
		SandboxName             string
		ProviderName            string
		ExpectedResourceVersion uint64
	}{
		Ctx:                     ctx,
		Workspace:               workspace,
		SandboxName:             sandboxName,
		ProviderName:            providerName,
		ExpectedResourceVersion: expectedResourceVersion,
	}
	mock.lockAttachProvider.Lock()
	mock.calls.AttachProvider = append(mock.calls.AttachProvider, callInfo)
	mock.lockAttachProvider.Unlock()
	return mock.AttachProviderFunc(ctx, workspace, sandboxName, providerName, expectedResourceVersion)
}

// AttachProviderCalls gets all the calls that were made to AttachProvider.
// Check the length with:
//
//	len(mockedSandboxInterface.AttachProviderCalls())
func (mock *mockSandboxInterface) AttachProviderCalls() []struct {
	Ctx                     context.Context
	Workspace               string
	SandboxName             string
	ProviderName            string
	ExpectedResourceVersion uint64
} {
	var calls []struct {
		Ctx                     context.Context
		Workspace               string
		SandboxName             string
		ProviderName            string
		ExpectedResourceVersion uint64
	}
	mock.lockAttachProvider.RLock()
	calls = mock.calls.AttachProvider
	mock.lockAttachProvider.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *mockSandboxInterface) Create(ctx context.Context, workspace string, name string, spec *v1.SandboxSpec, labels map[string]string, opts ...v1.CreateOptions) (*v1.Sandbox, error) {
	if mock.CreateFunc == nil {
		panic("mockSandboxInterface.CreateFunc: method is nil but SandboxInterface.Create was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Spec      *v1.SandboxSpec
		Labels    map[string]string
		Opts      []v1.CreateOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
		Spec:      spec,
		Labels:    labels,
		Opts:      opts,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, workspace, name, spec, labels, opts...)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSandboxInterface.CreateCalls())
func (mock *mockSandboxInterface) CreateCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
	Spec      *v1.SandboxSpec
	Labels    map[string]string
	Opts      []v1.CreateOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Spec      *v1.SandboxSpec
		Labels    map[string]string
		Opts      []v1.CreateOptions
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *mockSandboxInterface) Delete(ctx context.Context, workspace string, name string, opts ...v1.DeleteOptions) (*v1.DeletionResult, error) {
	if mock.DeleteFunc == nil {
		panic("mockSandboxInterface.DeleteFunc: method is nil but SandboxInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.DeleteOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
		Opts:      opts,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, workspace, name, opts...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSandboxInterface.DeleteCalls())
func (mock *mockSandboxInterface) DeleteCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
	Opts      []v1.DeleteOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.DeleteOptions
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DetachProvider calls DetachProviderFunc.
func (mock *mockSandboxInterface) DetachProvider(ctx context.Context, workspace string, sandboxName string, providerName string, expectedResourceVersion uint64) (*v1.DetachProviderResult, error) {
	if mock.DetachProviderFunc == nil {
		panic("mockSandboxInterface.DetachProviderFunc: method is nil but SandboxInterface.DetachProvider was just called")
	}
	callInfo := struct {
		Ctx                     context.Context
		Workspace               string
		SandboxName             string
		ProviderName            string
		ExpectedResourceVersion uint64
	}{
		Ctx:                     ctx,
		Workspace:               workspace,
		SandboxName:             sandboxName,
		ProviderName:            providerName,
		ExpectedResourceVersion: expectedResourceVersion,
	}
	mock.lockDetachProvider.Lock()
	mock.calls.DetachProvider = append(mock.calls.DetachProvider, callInfo)
	mock.lockDetachProvider.Unlock()
	return mock.DetachProviderFunc(ctx, workspace, sandboxName, providerName, expectedResourceVersion)
}

// DetachProviderCalls gets all the calls that were made to DetachProvider.
// Check the length with:
//
//	len(mockedSandboxInterface.DetachProviderCalls())
func (mock *mockSandboxInterface) DetachProviderCalls() []struct {
	Ctx                     context.Context
	Workspace               string
	SandboxName             string
	ProviderName            string
	ExpectedResourceVersion uint64
} {
	var calls []struct {
		Ctx                     context.Context
		Workspace               string
		SandboxName             string
		ProviderName            string
		ExpectedResourceVersion uint64
	}
	mock.lockDetachProvider.RLock()
	calls = mock.calls.DetachProvider
	mock.lockDetachProvider.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *mockSandboxInterface) Get(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
	if mock.GetFunc == nil {
		panic("mockSandboxInterface.GetFunc: method is nil but SandboxInterface.Get was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, workspace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSandboxInterface.GetCalls())
func (mock *mockSandboxInterface) GetCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetLogs calls GetLogsFunc.
func (mock *mockSandboxInterface) GetLogs(ctx context.Context, workspace string, sandboxName string, opts ...v1.LogOption) (*v1.LogResult, error) {
	if mock.GetLogsFunc == nil {
		panic("mockSandboxInterface.GetLogsFunc: method is nil but SandboxInterface.GetLogs was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Opts        []v1.LogOption
	}{
		Ctx:         ctx,
		Workspace:   workspace,
		SandboxName: sandboxName,
		Opts:        opts,
	}
	mock.lockGetLogs.Lock()
	mock.calls.GetLogs = append(mock.calls.GetLogs, callInfo)
	mock.lockGetLogs.Unlock()
	return mock.GetLogsFunc(ctx, workspace, sandboxName, opts...)
}

// GetLogsCalls gets all the calls that were made to GetLogs.
// Check the length with:
//
//	len(mockedSandboxInterface.GetLogsCalls())
func (mock *mockSandboxInterface) GetLogsCalls() []struct {
	Ctx         context.Context
	Workspace   string
	SandboxName string
	Opts        []v1.LogOption
} {
	var calls []struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Opts        []v1.LogOption
	}
	mock.lockGetLogs.RLock()
	calls = mock.calls.GetLogs
	mock.lockGetLogs.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *mockSandboxInterface) List(workspace string, opts ...v1.ListOptions) (*v1.Pager[*v1.Sandbox], error) {
	if mock.ListFunc == nil {
		panic("mockSandboxInterface.ListFunc: method is nil but SandboxInterface.List was just called")
	}
	callInfo := struct {
		Workspace string
		Opts      []v1.ListOptions
	}{
		Workspace: workspace,
		Opts:      opts,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(workspace, opts...)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedSandboxInterface.ListCalls())
func (mock *mockSandboxInterface) ListCalls() []struct {
	Workspace string
	Opts      []v1.ListOptions
} {
	var calls []struct {
		Workspace string
		Opts      []v1.ListOptions
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListAll calls ListAllFunc.
func (mock *mockSandboxInterface) ListAll(ctx context.Context, workspace string, opts ...v1.ListOptions) ([]*v1.Sandbox, error) {
	if mock.ListAllFunc == nil {
		panic("mockSandboxInterface.ListAllFunc: method is nil but SandboxInterface.ListAll was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Opts      []v1.ListOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Opts:      opts,
	}
	mock.lockListAll.Lock()
	mock.calls.ListAll = append(mock.calls.ListAll, callInfo)
	mock.lockListAll.Unlock()
	return mock.ListAllFunc(ctx, workspace, opts...)
}

// ListAllCalls gets all the calls that were made to ListAll.
// Check the length with:
//
//	len(mockedSandboxInterface.ListAllCalls())
func (mock *mockSandboxInterface) ListAllCalls() []struct {
	Ctx       context.Context
	Workspace string
	Opts      []v1.ListOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Opts      []v1.ListOptions
	}
	mock.lockListAll.RLock()
	calls = mock.calls.ListAll
	mock.lockListAll.RUnlock()
	return calls
}

// ListAllProviders calls ListAllProvidersFunc.
func (mock *mockSandboxInterface) ListAllProviders(ctx context.Context, workspace string, sandboxName string, opts ...v1.ListOptions) ([]*v1.Provider, error) {
	if mock.ListAllProvidersFunc == nil {
		panic("mockSandboxInterface.ListAllProvidersFunc: method is nil but SandboxInterface.ListAllProviders was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Opts        []v1.ListOptions
	}{
		Ctx:         ctx,
		Workspace:   workspace,
		SandboxName: sandboxName,
		Opts:        opts,
	}
	mock.lockListAllProviders.Lock()
	mock.calls.ListAllProviders = append(mock.calls.ListAllProviders, callInfo)
	mock.lockListAllProviders.Unlock()
	return mock.ListAllProvidersFunc(ctx, workspace, sandboxName, opts...)
}

// ListAllProvidersCalls gets all the calls that were made to ListAllProviders.
// Check the length with:
//
//	len(mockedSandboxInterface.ListAllProvidersCalls())
func (mock *mockSandboxInterface) ListAllProvidersCalls() []struct {
	Ctx         context.Context
	Workspace   string
	SandboxName string
	Opts        []v1.ListOptions
} {
	var calls []struct {
		Ctx         context.Context
		Workspace   string
		SandboxName string
		Opts        []v1.ListOptions
	}
	mock.lockListAllProviders.RLock()
	calls = mock.calls.ListAllProviders
	mock.lockListAllProviders.RUnlock()
	return calls
}

// ListProviders calls ListProvidersFunc.
func (mock *mockSandboxInterface) ListProviders(workspace string, sandboxName string, opts ...v1.ListOptions) (*v1.Pager[*v1.Provider], error) {
	if mock.ListProvidersFunc == nil {
		panic("mockSandboxInterface.ListProvidersFunc: method is nil but SandboxInterface.ListProviders was just called")
	}
	callInfo := struct {
		Workspace   string
		SandboxName string
		Opts        []v1.ListOptions
	}{
		Workspace:   workspace,
		SandboxName: sandboxName,
		Opts:        opts,
	}
	mock.lockListProviders.Lock()
	mock.calls.ListProviders = append(mock.calls.ListProviders, callInfo)
	mock.lockListProviders.Unlock()
	return mock.ListProvidersFunc(workspace, sandboxName, opts...)
}

// ListProvidersCalls gets all the calls that were made to ListProviders.
// Check the length with:
//
//	len(mockedSandboxInterface.ListProvidersCalls())
func (mock *mockSandboxInterface) ListProvidersCalls() []struct {
	Workspace   string
	SandboxName string
	Opts        []v1.ListOptions
} {
	var calls []struct {
		Workspace   string
		SandboxName string
		Opts        []v1.ListOptions
	}
	mock.lockListProviders.RLock()
	calls = mock.calls.ListProviders
	mock.lockListProviders.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *mockSandboxInterface) Start(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
	if mock.StartFunc == nil {
		panic("mockSandboxInterface.StartFunc: method is nil but SandboxInterface.Start was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx, workspace, name)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedSandboxInterface.StartCalls())
func (mock *mockSandboxInterface) StartCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *mockSandboxInterface) Stop(ctx context.Context, workspace string, name string) (*v1.Sandbox, error) {
	if mock.StopFunc == nil {
		panic("mockSandboxInterface.StopFunc: method is nil but SandboxInterface.Stop was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(ctx, workspace, name)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedSandboxInterface.StopCalls())
func (mock *mockSandboxInterface) StopCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// WaitReady calls WaitReadyFunc.
func (mock *mockSandboxInterface) WaitReady(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error) {
	if mock.WaitReadyFunc == nil {
		panic("mockSandboxInterface.WaitReadyFunc: method is nil but SandboxInterface.WaitReady was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WaitOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
		Opts:      opts,
	}
	mock.lockWaitReady.Lock()
	mock.calls.WaitReady = append(mock.calls.WaitReady, callInfo)
	mock.lockWaitReady.Unlock()
	return mock.WaitReadyFunc(ctx, workspace, name, opts...)
}

// WaitReadyCalls gets all the calls that were made to WaitReady.
// Check the length with:
//
//	len(mockedSandboxInterface.WaitReadyCalls())
func (mock *mockSandboxInterface) WaitReadyCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
	Opts      []v1.WaitOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WaitOptions
	}
	mock.lockWaitReady.RLock()
	calls = mock.calls.WaitReady
	mock.lockWaitReady.RUnlock()
	return calls
}

// WaitStopped calls WaitStoppedFunc.
func (mock *mockSandboxInterface) WaitStopped(ctx context.Context, workspace string, name string, opts ...v1.WaitOptions) (*v1.Sandbox, error) {
	if mock.WaitStoppedFunc == nil {
		panic("mockSandboxInterface.WaitStoppedFunc: method is nil but SandboxInterface.WaitStopped was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WaitOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
		Opts:      opts,
	}
	mock.lockWaitStopped.Lock()
	mock.calls.WaitStopped = append(mock.calls.WaitStopped, callInfo)
	mock.lockWaitStopped.Unlock()
	return mock.WaitStoppedFunc(ctx, workspace, name, opts...)
}

// WaitStoppedCalls gets all the calls that were made to WaitStopped.
// Check the length with:
//
//	len(mockedSandboxInterface.WaitStoppedCalls())
func (mock *mockSandboxInterface) WaitStoppedCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
	Opts      []v1.WaitOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WaitOptions
	}
	mock.lockWaitStopped.RLock()
	calls = mock.calls.WaitStopped
	mock.lockWaitStopped.RUnlock()
	return calls
}

// Watch calls WatchFunc.
func (mock *mockSandboxInterface) Watch(ctx context.Context, workspace string, name string, opts ...v1.WatchOptions) (v1.WatchInterface[*v1.Sandbox], error) {
	if mock.WatchFunc == nil {
		panic("mockSandboxInterface.WatchFunc: method is nil but SandboxInterface.Watch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WatchOptions
	}{
		Ctx:       ctx,
		Workspace: workspace,
		Name:      name,
		Opts:      opts,
	}
	mock.lockWatch.Lock()
	mock.calls.Watch = append(mock.calls.Watch, callInfo)
	mock.lockWatch.Unlock()
	return mock.WatchFunc(ctx, workspace, name, opts...)
}

// WatchCalls gets all the calls that were made to Watch.
// Check the length with:
//
//	len(mockedSandboxInterface.WatchCalls())
func (mock *mockSandboxInterface) WatchCalls() []struct {
	Ctx       context.Context
	Workspace string
	Name      string
	Opts      []v1.WatchOptions
} {
	var calls []struct {
		Ctx       context.Context
		Workspace string
		Name      string
		Opts      []v1.WatchOptions
	}
	mock.lockWatch.RLock()
	calls = mock.calls.Watch
	mock.lockWatch.RUnlock()
	return calls
}
