// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"
)

// Ensure that backgroundNotesMock does implement backgroundNotes.
// If this is not the case, regenerate this file with mockery.
var _ backgroundNotes = &backgroundNotesMock{}

// backgroundNotesMock is a mock implementation of backgroundNotes.
//
//	func TestSomethingThatUsesbackgroundNotes(t *testing.T) {
//
//		// make and configure a mocked backgroundNotes
//		mockedbackgroundNotes := &backgroundNotesMock{
//			continueSubagentFunc: func(ctx context.Context, job *backgroundJob, input string) (string, error) {
//				panic("mock out the continueSubagent method")
//			},
//			noteReadyFunc: func(conversationID string)  {
//				panic("mock out the noteReady method")
//			},
//		}
//
//		// use mockedbackgroundNotes in code that requires backgroundNotes
//		// and then make assertions.
//
//	}
type backgroundNotesMock struct {
	// continueSubagentFunc mocks the continueSubagent method.
	continueSubagentFunc func(ctx context.Context, job *backgroundJob, input string) (string, error)

	// noteReadyFunc mocks the noteReady method.
	noteReadyFunc func(conversationID string)

	// calls tracks calls to the methods.
	calls struct {
		// continueSubagent holds details about calls to the continueSubagent method.
		continueSubagent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *backgroundJob
			// Input is the input argument value.
			Input string
		}
		// noteReady holds details about calls to the noteReady method.
		noteReady []struct {
			// ConversationID is the conversationID argument value.
			ConversationID string
		}
	}
	lockcontinueSubagent sync.RWMutex
	locknoteReady        sync.RWMutex
}

// continueSubagent calls continueSubagentFunc.
func (mock *backgroundNotesMock) continueSubagent(ctx context.Context, job *backgroundJob, input string) (string, error) {
	if mock.continueSubagentFunc == nil {
		panic("backgroundNotesMock.continueSubagentFunc: method is nil but backgroundNotes.continueSubagent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Job   *backgroundJob
		Input string
	}{
		Ctx:   ctx,
		Job:   job,
		Input: input,
	}
	mock.lockcontinueSubagent.Lock()
	mock.calls.continueSubagent = append(mock.calls.continueSubagent, callInfo)
	mock.lockcontinueSubagent.Unlock()
	return mock.continueSubagentFunc(ctx, job, input)
}

// continueSubagentCalls gets all the calls that were made to continueSubagent.
// Check the length with:
//
//	len(mockedbackgroundNotes.continueSubagentCalls())
func (mock *backgroundNotesMock) continueSubagentCalls() []struct {
	Ctx   context.Context
	Job   *backgroundJob
	Input string
} {
	var calls []struct {
		Ctx   context.Context
		Job   *backgroundJob
		Input string
	}
	mock.lockcontinueSubagent.RLock()
	calls = mock.calls.continueSubagent
	mock.lockcontinueSubagent.RUnlock()
	return calls
}

// noteReady calls noteReadyFunc.
func (mock *backgroundNotesMock) noteReady(conversationID string) {
	if mock.noteReadyFunc == nil {
		panic("backgroundNotesMock.noteReadyFunc: method is nil but backgroundNotes.noteReady was just called")
	}
	callInfo := struct {
		ConversationID string
	}{
		ConversationID: conversationID,
	}
	mock.locknoteReady.Lock()
	mock.calls.noteReady = append(mock.calls.noteReady, callInfo)
	mock.locknoteReady.Unlock()
	mock.noteReadyFunc(conversationID)
}

// noteReadyCalls gets all the calls that were made to noteReady.
// Check the length with:
//
//	len(mockedbackgroundNotes.noteReadyCalls())
func (mock *backgroundNotesMock) noteReadyCalls() []struct {
	ConversationID string
} {
	var calls []struct {
		ConversationID string
	}
	mock.locknoteReady.RLock()
	calls = mock.calls.noteReady
	mock.locknoteReady.RUnlock()
	return calls
}
