// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that directBridgeMock does implement directBridge.
// If this is not the case, regenerate this file with mockery.
var _ directBridge = &directBridgeMock{}

// directBridgeMock is a mock implementation of directBridge.
//
//	func TestSomethingThatUsesdirectBridge(t *testing.T) {
//
//		// make and configure a mocked directBridge
//		mockeddirectBridge := &directBridgeMock{
//			InterruptActiveTurnFunc: func() *protocol.InboundMessage {
//				panic("mock out the InterruptActiveTurn method")
//			},
//			PickLaterWorkFunc: func(ctx context.Context) error {
//				panic("mock out the PickLaterWork method")
//			},
//			RunFunc: func(ctx context.Context) error {
//				panic("mock out the Run method")
//			},
//			StopFunc: func() error {
//				panic("mock out the Stop method")
//			},
//			SubmitFunc: func(ctx context.Context, msg *protocol.InboundMessage) error {
//				panic("mock out the Submit method")
//			},
//			SwitchAgentFunc: func(agent string)  {
//				panic("mock out the SwitchAgent method")
//			},
//		}
//
//		// use mockeddirectBridge in code that requires directBridge
//		// and then make assertions.
//
//	}
type directBridgeMock struct {
	// InterruptActiveTurnFunc mocks the InterruptActiveTurn method.
	InterruptActiveTurnFunc func() *protocol.InboundMessage

	// PickLaterWorkFunc mocks the PickLaterWork method.
	PickLaterWorkFunc func(ctx context.Context) error

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context) error

	// StopFunc mocks the Stop method.
	StopFunc func() error

	// SubmitFunc mocks the Submit method.
	SubmitFunc func(ctx context.Context, msg *protocol.InboundMessage) error

	// SwitchAgentFunc mocks the SwitchAgent method.
	SwitchAgentFunc func(agent string)

	// calls tracks calls to the methods.
	calls struct {
		// InterruptActiveTurn holds details about calls to the InterruptActiveTurn method.
		InterruptActiveTurn []struct {
		}
		// PickLaterWork holds details about calls to the PickLaterWork method.
		PickLaterWork []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
		// Submit holds details about calls to the Submit method.
		Submit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg *protocol.InboundMessage
		}
		// SwitchAgent holds details about calls to the SwitchAgent method.
		SwitchAgent []struct {
			// Agent is the agent argument value.
			Agent string
		}
	}
	lockInterruptActiveTurn sync.RWMutex
	lockPickLaterWork       sync.RWMutex
	lockRun                 sync.RWMutex
	lockStop                sync.RWMutex
	lockSubmit              sync.RWMutex
	lockSwitchAgent         sync.RWMutex
}

// InterruptActiveTurn calls InterruptActiveTurnFunc.
func (mock *directBridgeMock) InterruptActiveTurn() *protocol.InboundMessage {
	if mock.InterruptActiveTurnFunc == nil {
		panic("directBridgeMock.InterruptActiveTurnFunc: method is nil but directBridge.InterruptActiveTurn was just called")
	}
	callInfo := struct {
	}{}
	mock.lockInterruptActiveTurn.Lock()
	mock.calls.InterruptActiveTurn = append(mock.calls.InterruptActiveTurn, callInfo)
	mock.lockInterruptActiveTurn.Unlock()
	return mock.InterruptActiveTurnFunc()
}

// InterruptActiveTurnCalls gets all the calls that were made to InterruptActiveTurn.
// Check the length with:
//
//	len(mockeddirectBridge.InterruptActiveTurnCalls())
func (mock *directBridgeMock) InterruptActiveTurnCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockInterruptActiveTurn.RLock()
	calls = mock.calls.InterruptActiveTurn
	mock.lockInterruptActiveTurn.RUnlock()
	return calls
}

// PickLaterWork calls PickLaterWorkFunc.
func (mock *directBridgeMock) PickLaterWork(ctx context.Context) error {
	if mock.PickLaterWorkFunc == nil {
		panic("directBridgeMock.PickLaterWorkFunc: method is nil but directBridge.PickLaterWork was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPickLaterWork.Lock()
	mock.calls.PickLaterWork = append(mock.calls.PickLaterWork, callInfo)
	mock.lockPickLaterWork.Unlock()
	return mock.PickLaterWorkFunc(ctx)
}

// PickLaterWorkCalls gets all the calls that were made to PickLaterWork.
// Check the length with:
//
//	len(mockeddirectBridge.PickLaterWorkCalls())
func (mock *directBridgeMock) PickLaterWorkCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPickLaterWork.RLock()
	calls = mock.calls.PickLaterWork
	mock.lockPickLaterWork.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *directBridgeMock) Run(ctx context.Context) error {
	if mock.RunFunc == nil {
		panic("directBridgeMock.RunFunc: method is nil but directBridge.Run was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockeddirectBridge.RunCalls())
func (mock *directBridgeMock) RunCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *directBridgeMock) Stop() error {
	if mock.StopFunc == nil {
		panic("directBridgeMock.StopFunc: method is nil but directBridge.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockeddirectBridge.StopCalls())
func (mock *directBridgeMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Submit calls SubmitFunc.
func (mock *directBridgeMock) Submit(ctx context.Context, msg *protocol.InboundMessage) error {
	if mock.SubmitFunc == nil {
		panic("directBridgeMock.SubmitFunc: method is nil but directBridge.Submit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg *protocol.InboundMessage
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSubmit.Lock()
	mock.calls.Submit = append(mock.calls.Submit, callInfo)
	mock.lockSubmit.Unlock()
	return mock.SubmitFunc(ctx, msg)
}

// SubmitCalls gets all the calls that were made to Submit.
// Check the length with:
//
//	len(mockeddirectBridge.SubmitCalls())
func (mock *directBridgeMock) SubmitCalls() []struct {
	Ctx context.Context
	Msg *protocol.InboundMessage
} {
	var calls []struct {
		Ctx context.Context
		Msg *protocol.InboundMessage
	}
	mock.lockSubmit.RLock()
	calls = mock.calls.Submit
	mock.lockSubmit.RUnlock()
	return calls
}

// SwitchAgent calls SwitchAgentFunc.
func (mock *directBridgeMock) SwitchAgent(agent string) {
	if mock.SwitchAgentFunc == nil {
		panic("directBridgeMock.SwitchAgentFunc: method is nil but directBridge.SwitchAgent was just called")
	}
	callInfo := struct {
		Agent string
	}{
		Agent: agent,
	}
	mock.lockSwitchAgent.Lock()
	mock.calls.SwitchAgent = append(mock.calls.SwitchAgent, callInfo)
	mock.lockSwitchAgent.Unlock()
	mock.SwitchAgentFunc(agent)
}

// SwitchAgentCalls gets all the calls that were made to SwitchAgent.
// Check the length with:
//
//	len(mockeddirectBridge.SwitchAgentCalls())
func (mock *directBridgeMock) SwitchAgentCalls() []struct {
	Agent string
} {
	var calls []struct {
		Agent string
	}
	mock.lockSwitchAgent.RLock()
	calls = mock.calls.SwitchAgent
	mock.lockSwitchAgent.RUnlock()
	return calls
}
