// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that outboundPublisherMock does implement protocol.OutboundPublisher.
// If this is not the case, regenerate this file with mockery.
var _ protocol.OutboundPublisher = &outboundPublisherMock{}

// outboundPublisherMock is a mock implementation of protocol.OutboundPublisher.
//
//	func TestSomethingThatUsesOutboundPublisher(t *testing.T) {
//
//		// make and configure a mocked protocol.OutboundPublisher
//		mockedOutboundPublisher := &outboundPublisherMock{
//			PublishOutboundFunc: func(context1 context.Context, outboundMessage *protocol.OutboundMessage) error {
//				panic("mock out the PublishOutbound method")
//			},
//		}
//
//		// use mockedOutboundPublisher in code that requires protocol.OutboundPublisher
//		// and then make assertions.
//
//	}
type outboundPublisherMock struct {
	// PublishOutboundFunc mocks the PublishOutbound method.
	PublishOutboundFunc func(context1 context.Context, outboundMessage *protocol.OutboundMessage) error

	// calls tracks calls to the methods.
	calls struct {
		// PublishOutbound holds details about calls to the PublishOutbound method.
		PublishOutbound []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// OutboundMessage is the outboundMessage argument value.
			OutboundMessage *protocol.OutboundMessage
		}
	}
	lockPublishOutbound sync.RWMutex
}

// PublishOutbound calls PublishOutboundFunc.
func (mock *outboundPublisherMock) PublishOutbound(context1 context.Context, outboundMessage *protocol.OutboundMessage) error {
	if mock.PublishOutboundFunc == nil {
		panic("outboundPublisherMock.PublishOutboundFunc: method is nil but OutboundPublisher.PublishOutbound was just called")
	}
	callInfo := struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}{
		Context1:        context1,
		OutboundMessage: outboundMessage,
	}
	mock.lockPublishOutbound.Lock()
	mock.calls.PublishOutbound = append(mock.calls.PublishOutbound, callInfo)
	mock.lockPublishOutbound.Unlock()
	return mock.PublishOutboundFunc(context1, outboundMessage)
}

// PublishOutboundCalls gets all the calls that were made to PublishOutbound.
// Check the length with:
//
//	len(mockedOutboundPublisher.PublishOutboundCalls())
func (mock *outboundPublisherMock) PublishOutboundCalls() []struct {
	Context1        context.Context
	OutboundMessage *protocol.OutboundMessage
} {
	var calls []struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}
	mock.lockPublishOutbound.RLock()
	calls = mock.calls.PublishOutbound
	mock.lockPublishOutbound.RUnlock()
	return calls
}
