// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"
)

// Ensure that runLockWorkMock does implement runLockWork.
// If this is not the case, regenerate this file with mockery.
var _ runLockWork = &runLockWorkMock{}

// runLockWorkMock is a mock implementation of runLockWork.
//
//	func TestSomethingThatUsesrunLockWork(t *testing.T) {
//
//		// make and configure a mocked runLockWork
//		mockedrunLockWork := &runLockWorkMock{
//			RunFunc: func(context1 context.Context) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedrunLockWork in code that requires runLockWork
//		// and then make assertions.
//
//	}
type runLockWorkMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(context1 context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *runLockWorkMock) Run(context1 context.Context) error {
	if mock.RunFunc == nil {
		panic("runLockWorkMock.RunFunc: method is nil but runLockWork.Run was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(context1)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedrunLockWork.RunCalls())
func (mock *runLockWorkMock) RunCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
