// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that slackFrontendMock does implement SlackFrontend.
// If this is not the case, regenerate this file with mockery.
var _ SlackFrontend = &slackFrontendMock{}

// slackFrontendMock is a mock implementation of SlackFrontend.
//
//	func TestSomethingThatUsesSlackFrontend(t *testing.T) {
//
//		// make and configure a mocked SlackFrontend
//		mockedSlackFrontend := &slackFrontendMock{
//			EditCronjobRootFooterFunc: func(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error {
//				panic("mock out the EditCronjobRootFooter method")
//			},
//			SendCronjobRootFunc: func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
//				panic("mock out the SendCronjobRoot method")
//			},
//			StartFunc: func(context1 context.Context) error {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(context1 context.Context) error {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedSlackFrontend in code that requires SlackFrontend
//		// and then make assertions.
//
//	}
type slackFrontendMock struct {
	// EditCronjobRootFooterFunc mocks the EditCronjobRootFooter method.
	EditCronjobRootFooterFunc func(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error

	// SendCronjobRootFunc mocks the SendCronjobRoot method.
	SendCronjobRootFunc func(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error)

	// StartFunc mocks the Start method.
	StartFunc func(context1 context.Context) error

	// StopFunc mocks the Stop method.
	StopFunc func(context1 context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// EditCronjobRootFooter holds details about calls to the EditCronjobRootFooter method.
		EditCronjobRootFooter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg *protocol.OutboundMessage
			// Root is the root argument value.
			Root protocol.TextConversationTarget
			// ConversationID is the conversationID argument value.
			ConversationID string
		}
		// SendCronjobRoot holds details about calls to the SendCronjobRoot method.
		SendCronjobRoot []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// OutboundMessage is the outboundMessage argument value.
			OutboundMessage *protocol.OutboundMessage
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
	}
	lockEditCronjobRootFooter sync.RWMutex
	lockSendCronjobRoot       sync.RWMutex
	lockStart                 sync.RWMutex
	lockStop                  sync.RWMutex
}

// EditCronjobRootFooter calls EditCronjobRootFooterFunc.
func (mock *slackFrontendMock) EditCronjobRootFooter(ctx context.Context, msg *protocol.OutboundMessage, root protocol.TextConversationTarget, conversationID string) error {
	if mock.EditCronjobRootFooterFunc == nil {
		panic("slackFrontendMock.EditCronjobRootFooterFunc: method is nil but SlackFrontend.EditCronjobRootFooter was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Msg            *protocol.OutboundMessage
		Root           protocol.TextConversationTarget
		ConversationID string
	}{
		Ctx:            ctx,
		Msg:            msg,
		Root:           root,
		ConversationID: conversationID,
	}
	mock.lockEditCronjobRootFooter.Lock()
	mock.calls.EditCronjobRootFooter = append(mock.calls.EditCronjobRootFooter, callInfo)
	mock.lockEditCronjobRootFooter.Unlock()
	return mock.EditCronjobRootFooterFunc(ctx, msg, root, conversationID)
}

// EditCronjobRootFooterCalls gets all the calls that were made to EditCronjobRootFooter.
// Check the length with:
//
//	len(mockedSlackFrontend.EditCronjobRootFooterCalls())
func (mock *slackFrontendMock) EditCronjobRootFooterCalls() []struct {
	Ctx            context.Context
	Msg            *protocol.OutboundMessage
	Root           protocol.TextConversationTarget
	ConversationID string
} {
	var calls []struct {
		Ctx            context.Context
		Msg            *protocol.OutboundMessage
		Root           protocol.TextConversationTarget
		ConversationID string
	}
	mock.lockEditCronjobRootFooter.RLock()
	calls = mock.calls.EditCronjobRootFooter
	mock.lockEditCronjobRootFooter.RUnlock()
	return calls
}

// SendCronjobRoot calls SendCronjobRootFunc.
func (mock *slackFrontendMock) SendCronjobRoot(context1 context.Context, outboundMessage *protocol.OutboundMessage) (protocol.TextConversationTarget, error) {
	if mock.SendCronjobRootFunc == nil {
		panic("slackFrontendMock.SendCronjobRootFunc: method is nil but SlackFrontend.SendCronjobRoot was just called")
	}
	callInfo := struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}{
		Context1:        context1,
		OutboundMessage: outboundMessage,
	}
	mock.lockSendCronjobRoot.Lock()
	mock.calls.SendCronjobRoot = append(mock.calls.SendCronjobRoot, callInfo)
	mock.lockSendCronjobRoot.Unlock()
	return mock.SendCronjobRootFunc(context1, outboundMessage)
}

// SendCronjobRootCalls gets all the calls that were made to SendCronjobRoot.
// Check the length with:
//
//	len(mockedSlackFrontend.SendCronjobRootCalls())
func (mock *slackFrontendMock) SendCronjobRootCalls() []struct {
	Context1        context.Context
	OutboundMessage *protocol.OutboundMessage
} {
	var calls []struct {
		Context1        context.Context
		OutboundMessage *protocol.OutboundMessage
	}
	mock.lockSendCronjobRoot.RLock()
	calls = mock.calls.SendCronjobRoot
	mock.lockSendCronjobRoot.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *slackFrontendMock) Start(context1 context.Context) error {
	if mock.StartFunc == nil {
		panic("slackFrontendMock.StartFunc: method is nil but SlackFrontend.Start was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(context1)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedSlackFrontend.StartCalls())
func (mock *slackFrontendMock) StartCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *slackFrontendMock) Stop(context1 context.Context) error {
	if mock.StopFunc == nil {
		panic("slackFrontendMock.StopFunc: method is nil but SlackFrontend.Stop was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	return mock.StopFunc(context1)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedSlackFrontend.StopCalls())
func (mock *slackFrontendMock) StopCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
