// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that startupSteerSurfaceMock does implement startupSteerSurface.
// If this is not the case, regenerate this file with mockery.
var _ startupSteerSurface = &startupSteerSurfaceMock{}

// startupSteerSurfaceMock is a mock implementation of startupSteerSurface.
//
//	func TestSomethingThatUsesstartupSteerSurface(t *testing.T) {
//
//		// make and configure a mocked startupSteerSurface
//		mockedstartupSteerSurface := &startupSteerSurfaceMock{
//			DiscardPendingSteersFunc: func(context1 context.Context, pendingSteers []protocol.PendingSteer)  {
//				panic("mock out the DiscardPendingSteers method")
//			},
//			RestorePendingSteersFunc: func(s string, pendingSteers []protocol.PendingSteer)  {
//				panic("mock out the RestorePendingSteers method")
//			},
//		}
//
//		// use mockedstartupSteerSurface in code that requires startupSteerSurface
//		// and then make assertions.
//
//	}
type startupSteerSurfaceMock struct {
	// DiscardPendingSteersFunc mocks the DiscardPendingSteers method.
	DiscardPendingSteersFunc func(context1 context.Context, pendingSteers []protocol.PendingSteer)

	// RestorePendingSteersFunc mocks the RestorePendingSteers method.
	RestorePendingSteersFunc func(s string, pendingSteers []protocol.PendingSteer)

	// calls tracks calls to the methods.
	calls struct {
		// DiscardPendingSteers holds details about calls to the DiscardPendingSteers method.
		DiscardPendingSteers []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// PendingSteers is the pendingSteers argument value.
			PendingSteers []protocol.PendingSteer
		}
		// RestorePendingSteers holds details about calls to the RestorePendingSteers method.
		RestorePendingSteers []struct {
			// S is the s argument value.
			S string
			// PendingSteers is the pendingSteers argument value.
			PendingSteers []protocol.PendingSteer
		}
	}
	lockDiscardPendingSteers sync.RWMutex
	lockRestorePendingSteers sync.RWMutex
}

// DiscardPendingSteers calls DiscardPendingSteersFunc.
func (mock *startupSteerSurfaceMock) DiscardPendingSteers(context1 context.Context, pendingSteers []protocol.PendingSteer) {
	if mock.DiscardPendingSteersFunc == nil {
		panic("startupSteerSurfaceMock.DiscardPendingSteersFunc: method is nil but startupSteerSurface.DiscardPendingSteers was just called")
	}
	callInfo := struct {
		Context1      context.Context
		PendingSteers []protocol.PendingSteer
	}{
		Context1:      context1,
		PendingSteers: pendingSteers,
	}
	mock.lockDiscardPendingSteers.Lock()
	mock.calls.DiscardPendingSteers = append(mock.calls.DiscardPendingSteers, callInfo)
	mock.lockDiscardPendingSteers.Unlock()
	mock.DiscardPendingSteersFunc(context1, pendingSteers)
}

// DiscardPendingSteersCalls gets all the calls that were made to DiscardPendingSteers.
// Check the length with:
//
//	len(mockedstartupSteerSurface.DiscardPendingSteersCalls())
func (mock *startupSteerSurfaceMock) DiscardPendingSteersCalls() []struct {
	Context1      context.Context
	PendingSteers []protocol.PendingSteer
} {
	var calls []struct {
		Context1      context.Context
		PendingSteers []protocol.PendingSteer
	}
	mock.lockDiscardPendingSteers.RLock()
	calls = mock.calls.DiscardPendingSteers
	mock.lockDiscardPendingSteers.RUnlock()
	return calls
}

// RestorePendingSteers calls RestorePendingSteersFunc.
func (mock *startupSteerSurfaceMock) RestorePendingSteers(s string, pendingSteers []protocol.PendingSteer) {
	if mock.RestorePendingSteersFunc == nil {
		panic("startupSteerSurfaceMock.RestorePendingSteersFunc: method is nil but startupSteerSurface.RestorePendingSteers was just called")
	}
	callInfo := struct {
		S             string
		PendingSteers []protocol.PendingSteer
	}{
		S:             s,
		PendingSteers: pendingSteers,
	}
	mock.lockRestorePendingSteers.Lock()
	mock.calls.RestorePendingSteers = append(mock.calls.RestorePendingSteers, callInfo)
	mock.lockRestorePendingSteers.Unlock()
	mock.RestorePendingSteersFunc(s, pendingSteers)
}

// RestorePendingSteersCalls gets all the calls that were made to RestorePendingSteers.
// Check the length with:
//
//	len(mockedstartupSteerSurface.RestorePendingSteersCalls())
func (mock *startupSteerSurfaceMock) RestorePendingSteersCalls() []struct {
	S             string
	PendingSteers []protocol.PendingSteer
} {
	var calls []struct {
		S             string
		PendingSteers []protocol.PendingSteer
	}
	mock.lockRestorePendingSteers.RLock()
	calls = mock.calls.RestorePendingSteers
	mock.lockRestorePendingSteers.RUnlock()
	return calls
}
