// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package backend

import (
	"context"
	"sync"
)

// Ensure that startupRecoveryStoreMock does implement startupRecoveryStore.
// If this is not the case, regenerate this file with mockery.
var _ startupRecoveryStore = &startupRecoveryStoreMock{}

// startupRecoveryStoreMock is a mock implementation of startupRecoveryStore.
//
//	func TestSomethingThatUsesstartupRecoveryStore(t *testing.T) {
//
//		// make and configure a mocked startupRecoveryStore
//		mockedstartupRecoveryStore := &startupRecoveryStoreMock{
//			ClearActiveTurnFunc: func(context1 context.Context, s string) error {
//				panic("mock out the ClearActiveTurn method")
//			},
//			ExternalMCPSessionByConversationIDFunc: func(s string) (string, ExternalMCPSessionState, bool, error) {
//				panic("mock out the ExternalMCPSessionByConversationID method")
//			},
//			RecoverableActiveTurnsFunc: func(context1 context.Context) ([]ActiveTurnState, error) {
//				panic("mock out the RecoverableActiveTurns method")
//			},
//			StopGoalFunc: func(s string) error {
//				panic("mock out the StopGoal method")
//			},
//			ThreadFunc: func(s string) (ThreadState, bool, error) {
//				panic("mock out the Thread method")
//			},
//		}
//
//		// use mockedstartupRecoveryStore in code that requires startupRecoveryStore
//		// and then make assertions.
//
//	}
type startupRecoveryStoreMock struct {
	// ClearActiveTurnFunc mocks the ClearActiveTurn method.
	ClearActiveTurnFunc func(context1 context.Context, s string) error

	// ExternalMCPSessionByConversationIDFunc mocks the ExternalMCPSessionByConversationID method.
	ExternalMCPSessionByConversationIDFunc func(s string) (string, ExternalMCPSessionState, bool, error)

	// RecoverableActiveTurnsFunc mocks the RecoverableActiveTurns method.
	RecoverableActiveTurnsFunc func(context1 context.Context) ([]ActiveTurnState, error)

	// StopGoalFunc mocks the StopGoal method.
	StopGoalFunc func(s string) error

	// ThreadFunc mocks the Thread method.
	ThreadFunc func(s string) (ThreadState, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClearActiveTurn holds details about calls to the ClearActiveTurn method.
		ClearActiveTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// ExternalMCPSessionByConversationID holds details about calls to the ExternalMCPSessionByConversationID method.
		ExternalMCPSessionByConversationID []struct {
			// S is the s argument value.
			S string
		}
		// RecoverableActiveTurns holds details about calls to the RecoverableActiveTurns method.
		RecoverableActiveTurns []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// StopGoal holds details about calls to the StopGoal method.
		StopGoal []struct {
			// S is the s argument value.
			S string
		}
		// Thread holds details about calls to the Thread method.
		Thread []struct {
			// S is the s argument value.
			S string
		}
	}
	lockClearActiveTurn                    sync.RWMutex
	lockExternalMCPSessionByConversationID sync.RWMutex
	lockRecoverableActiveTurns             sync.RWMutex
	lockStopGoal                           sync.RWMutex
	lockThread                             sync.RWMutex
}

// ClearActiveTurn calls ClearActiveTurnFunc.
func (mock *startupRecoveryStoreMock) ClearActiveTurn(context1 context.Context, s string) error {
	if mock.ClearActiveTurnFunc == nil {
		panic("startupRecoveryStoreMock.ClearActiveTurnFunc: method is nil but startupRecoveryStore.ClearActiveTurn was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockClearActiveTurn.Lock()
	mock.calls.ClearActiveTurn = append(mock.calls.ClearActiveTurn, callInfo)
	mock.lockClearActiveTurn.Unlock()
	return mock.ClearActiveTurnFunc(context1, s)
}

// ClearActiveTurnCalls gets all the calls that were made to ClearActiveTurn.
// Check the length with:
//
//	len(mockedstartupRecoveryStore.ClearActiveTurnCalls())
func (mock *startupRecoveryStoreMock) ClearActiveTurnCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockClearActiveTurn.RLock()
	calls = mock.calls.ClearActiveTurn
	mock.lockClearActiveTurn.RUnlock()
	return calls
}

// ExternalMCPSessionByConversationID calls ExternalMCPSessionByConversationIDFunc.
func (mock *startupRecoveryStoreMock) ExternalMCPSessionByConversationID(s string) (string, ExternalMCPSessionState, bool, error) {
	if mock.ExternalMCPSessionByConversationIDFunc == nil {
		panic("startupRecoveryStoreMock.ExternalMCPSessionByConversationIDFunc: method is nil but startupRecoveryStore.ExternalMCPSessionByConversationID was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockExternalMCPSessionByConversationID.Lock()
	mock.calls.ExternalMCPSessionByConversationID = append(mock.calls.ExternalMCPSessionByConversationID, callInfo)
	mock.lockExternalMCPSessionByConversationID.Unlock()
	return mock.ExternalMCPSessionByConversationIDFunc(s)
}

// ExternalMCPSessionByConversationIDCalls gets all the calls that were made to ExternalMCPSessionByConversationID.
// Check the length with:
//
//	len(mockedstartupRecoveryStore.ExternalMCPSessionByConversationIDCalls())
func (mock *startupRecoveryStoreMock) ExternalMCPSessionByConversationIDCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockExternalMCPSessionByConversationID.RLock()
	calls = mock.calls.ExternalMCPSessionByConversationID
	mock.lockExternalMCPSessionByConversationID.RUnlock()
	return calls
}

// RecoverableActiveTurns calls RecoverableActiveTurnsFunc.
func (mock *startupRecoveryStoreMock) RecoverableActiveTurns(context1 context.Context) ([]ActiveTurnState, error) {
	if mock.RecoverableActiveTurnsFunc == nil {
		panic("startupRecoveryStoreMock.RecoverableActiveTurnsFunc: method is nil but startupRecoveryStore.RecoverableActiveTurns was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockRecoverableActiveTurns.Lock()
	mock.calls.RecoverableActiveTurns = append(mock.calls.RecoverableActiveTurns, callInfo)
	mock.lockRecoverableActiveTurns.Unlock()
	return mock.RecoverableActiveTurnsFunc(context1)
}

// RecoverableActiveTurnsCalls gets all the calls that were made to RecoverableActiveTurns.
// Check the length with:
//
//	len(mockedstartupRecoveryStore.RecoverableActiveTurnsCalls())
func (mock *startupRecoveryStoreMock) RecoverableActiveTurnsCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockRecoverableActiveTurns.RLock()
	calls = mock.calls.RecoverableActiveTurns
	mock.lockRecoverableActiveTurns.RUnlock()
	return calls
}

// StopGoal calls StopGoalFunc.
func (mock *startupRecoveryStoreMock) StopGoal(s string) error {
	if mock.StopGoalFunc == nil {
		panic("startupRecoveryStoreMock.StopGoalFunc: method is nil but startupRecoveryStore.StopGoal was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockStopGoal.Lock()
	mock.calls.StopGoal = append(mock.calls.StopGoal, callInfo)
	mock.lockStopGoal.Unlock()
	return mock.StopGoalFunc(s)
}

// StopGoalCalls gets all the calls that were made to StopGoal.
// Check the length with:
//
//	len(mockedstartupRecoveryStore.StopGoalCalls())
func (mock *startupRecoveryStoreMock) StopGoalCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockStopGoal.RLock()
	calls = mock.calls.StopGoal
	mock.lockStopGoal.RUnlock()
	return calls
}

// Thread calls ThreadFunc.
func (mock *startupRecoveryStoreMock) Thread(s string) (ThreadState, bool, error) {
	if mock.ThreadFunc == nil {
		panic("startupRecoveryStoreMock.ThreadFunc: method is nil but startupRecoveryStore.Thread was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockThread.Lock()
	mock.calls.Thread = append(mock.calls.Thread, callInfo)
	mock.lockThread.Unlock()
	return mock.ThreadFunc(s)
}

// ThreadCalls gets all the calls that were made to Thread.
// Check the length with:
//
//	len(mockedstartupRecoveryStore.ThreadCalls())
func (mock *startupRecoveryStoreMock) ThreadCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockThread.RLock()
	calls = mock.calls.Thread
	mock.lockThread.RUnlock()
	return calls
}
