// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package slackconnector

import (
	"context"
	"iter"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/frontend"
	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that backendMock does implement frontend.Backend.
// If this is not the case, regenerate this file with mockery.
var _ frontend.Backend = &backendMock{}

// backendMock is a mock implementation of frontend.Backend.
//
//	func TestSomethingThatUsesBackend(t *testing.T) {
//
//		// make and configure a mocked frontend.Backend
//		mockedBackend := &backendMock{
//			AnswerQuestionFunc: func(context1 context.Context, s string, s1 string, askUserQuestionAnswer protocol.AskUserQuestionAnswer) error {
//				panic("mock out the AnswerQuestion method")
//			},
//			BackgroundJobsFunc: func(context1 context.Context, s string) ([]protocol.BackgroundJob, bool, error) {
//				panic("mock out the BackgroundJobs method")
//			},
//			ClearRevertFunc: func(context1 context.Context, s string) error {
//				panic("mock out the ClearRevert method")
//			},
//			CompletionNotesFunc: func(context1 context.Context, s string, strings []string) ([]protocol.BackgroundJob, error) {
//				panic("mock out the CompletionNotes method")
//			},
//			CreateConversationFunc: func(context1 context.Context, conversation protocol.Conversation) error {
//				panic("mock out the CreateConversation method")
//			},
//			DeleteQueueItemFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the DeleteQueueItem method")
//			},
//			ListConversationsFunc: func(context1 context.Context) ([]protocol.Conversation, error) {
//				panic("mock out the ListConversations method")
//			},
//			MoveToBackgroundFunc: func(s string) (bool, error) {
//				panic("mock out the MoveToBackground method")
//			},
//			PendingQuestionsFunc: func(context1 context.Context, s string) ([]protocol.AskUserQuestionRequest, error) {
//				panic("mock out the PendingQuestions method")
//			},
//			PopQueueItemFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the PopQueueItem method")
//			},
//			PromoteQueueItemFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the PromoteQueueItem method")
//			},
//			QueueItemsFunc: func(s string) ([]protocol.ThreadQueueItem, error) {
//				panic("mock out the QueueItems method")
//			},
//			ReorderQueueItemsFunc: func(s string, strings []string) error {
//				panic("mock out the ReorderQueueItems method")
//			},
//			RunTurnFunc: func(context1 context.Context, inboundMessage *protocol.InboundMessage) error {
//				panic("mock out the RunTurn method")
//			},
//			StageRevertFunc: func(context1 context.Context, s string, s1 string) (string, string, error) {
//				panic("mock out the StageRevert method")
//			},
//			StartGoalFunc: func(context1 context.Context, inboundMessage *protocol.InboundMessage, goalRequest protocol.GoalRequest) error {
//				panic("mock out the StartGoal method")
//			},
//			StashQueueItemFunc: func(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error {
//				panic("mock out the StashQueueItem method")
//			},
//			StopBackgroundJobFunc: func(context1 context.Context, s string, s1 string) (bool, error) {
//				panic("mock out the StopBackgroundJob method")
//			},
//			SubscribeFunc: func(context1 context.Context) iter.Seq[protocol.Event] {
//				panic("mock out the Subscribe method")
//			},
//			SwitchConversationAgentFunc: func(s string, s1 string) (bool, error) {
//				panic("mock out the SwitchConversationAgent method")
//			},
//			SyncConversationFunc: func(context1 context.Context, s string, s1 string) error {
//				panic("mock out the SyncConversation method")
//			},
//			WorkflowDescriptionsFunc: func() ([]protocol.WorkflowDescription, error) {
//				panic("mock out the WorkflowDescriptions method")
//			},
//		}
//
//		// use mockedBackend in code that requires frontend.Backend
//		// and then make assertions.
//
//	}
type backendMock struct {
	// AnswerQuestionFunc mocks the AnswerQuestion method.
	AnswerQuestionFunc func(context1 context.Context, s string, s1 string, askUserQuestionAnswer protocol.AskUserQuestionAnswer) error

	// BackgroundJobsFunc mocks the BackgroundJobs method.
	BackgroundJobsFunc func(context1 context.Context, s string) ([]protocol.BackgroundJob, bool, error)

	// ClearRevertFunc mocks the ClearRevert method.
	ClearRevertFunc func(context1 context.Context, s string) error

	// CompletionNotesFunc mocks the CompletionNotes method.
	CompletionNotesFunc func(context1 context.Context, s string, strings []string) ([]protocol.BackgroundJob, error)

	// CreateConversationFunc mocks the CreateConversation method.
	CreateConversationFunc func(context1 context.Context, conversation protocol.Conversation) error

	// DeleteQueueItemFunc mocks the DeleteQueueItem method.
	DeleteQueueItemFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// ListConversationsFunc mocks the ListConversations method.
	ListConversationsFunc func(context1 context.Context) ([]protocol.Conversation, error)

	// MoveToBackgroundFunc mocks the MoveToBackground method.
	MoveToBackgroundFunc func(s string) (bool, error)

	// PendingQuestionsFunc mocks the PendingQuestions method.
	PendingQuestionsFunc func(context1 context.Context, s string) ([]protocol.AskUserQuestionRequest, error)

	// PopQueueItemFunc mocks the PopQueueItem method.
	PopQueueItemFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// PromoteQueueItemFunc mocks the PromoteQueueItem method.
	PromoteQueueItemFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// QueueItemsFunc mocks the QueueItems method.
	QueueItemsFunc func(s string) ([]protocol.ThreadQueueItem, error)

	// ReorderQueueItemsFunc mocks the ReorderQueueItems method.
	ReorderQueueItemsFunc func(s string, strings []string) error

	// RunTurnFunc mocks the RunTurn method.
	RunTurnFunc func(context1 context.Context, inboundMessage *protocol.InboundMessage) error

	// StageRevertFunc mocks the StageRevert method.
	StageRevertFunc func(context1 context.Context, s string, s1 string) (string, string, error)

	// StartGoalFunc mocks the StartGoal method.
	StartGoalFunc func(context1 context.Context, inboundMessage *protocol.InboundMessage, goalRequest protocol.GoalRequest) error

	// StashQueueItemFunc mocks the StashQueueItem method.
	StashQueueItemFunc func(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error

	// StopBackgroundJobFunc mocks the StopBackgroundJob method.
	StopBackgroundJobFunc func(context1 context.Context, s string, s1 string) (bool, error)

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(context1 context.Context) iter.Seq[protocol.Event]

	// SwitchConversationAgentFunc mocks the SwitchConversationAgent method.
	SwitchConversationAgentFunc func(s string, s1 string) (bool, error)

	// SyncConversationFunc mocks the SyncConversation method.
	SyncConversationFunc func(context1 context.Context, s string, s1 string) error

	// WorkflowDescriptionsFunc mocks the WorkflowDescriptions method.
	WorkflowDescriptionsFunc func() ([]protocol.WorkflowDescription, error)

	// calls tracks calls to the methods.
	calls struct {
		// AnswerQuestion holds details about calls to the AnswerQuestion method.
		AnswerQuestion []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
			// AskUserQuestionAnswer is the askUserQuestionAnswer argument value.
			AskUserQuestionAnswer protocol.AskUserQuestionAnswer
		}
		// BackgroundJobs holds details about calls to the BackgroundJobs method.
		BackgroundJobs []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// ClearRevert holds details about calls to the ClearRevert method.
		ClearRevert []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// CompletionNotes holds details about calls to the CompletionNotes method.
		CompletionNotes []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// Strings is the strings argument value.
			Strings []string
		}
		// CreateConversation holds details about calls to the CreateConversation method.
		CreateConversation []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// Conversation is the conversation argument value.
			Conversation protocol.Conversation
		}
		// DeleteQueueItem holds details about calls to the DeleteQueueItem method.
		DeleteQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// ListConversations holds details about calls to the ListConversations method.
		ListConversations []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// MoveToBackground holds details about calls to the MoveToBackground method.
		MoveToBackground []struct {
			// S is the s argument value.
			S string
		}
		// PendingQuestions holds details about calls to the PendingQuestions method.
		PendingQuestions []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
		}
		// PopQueueItem holds details about calls to the PopQueueItem method.
		PopQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// PromoteQueueItem holds details about calls to the PromoteQueueItem method.
		PromoteQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// QueueItems holds details about calls to the QueueItems method.
		QueueItems []struct {
			// S is the s argument value.
			S string
		}
		// ReorderQueueItems holds details about calls to the ReorderQueueItems method.
		ReorderQueueItems []struct {
			// S is the s argument value.
			S string
			// Strings is the strings argument value.
			Strings []string
		}
		// RunTurn holds details about calls to the RunTurn method.
		RunTurn []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// InboundMessage is the inboundMessage argument value.
			InboundMessage *protocol.InboundMessage
		}
		// StageRevert holds details about calls to the StageRevert method.
		StageRevert []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// StartGoal holds details about calls to the StartGoal method.
		StartGoal []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// InboundMessage is the inboundMessage argument value.
			InboundMessage *protocol.InboundMessage
			// GoalRequest is the goalRequest argument value.
			GoalRequest protocol.GoalRequest
		}
		// StashQueueItem holds details about calls to the StashQueueItem method.
		StashQueueItem []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// ThreadQueueItem is the threadQueueItem argument value.
			ThreadQueueItem *protocol.ThreadQueueItem
		}
		// StopBackgroundJob holds details about calls to the StopBackgroundJob method.
		StopBackgroundJob []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
		}
		// SwitchConversationAgent holds details about calls to the SwitchConversationAgent method.
		SwitchConversationAgent []struct {
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// SyncConversation holds details about calls to the SyncConversation method.
		SyncConversation []struct {
			// Context1 is the context1 argument value.
			Context1 context.Context
			// S is the s argument value.
			S string
			// S1 is the s1 argument value.
			S1 string
		}
		// WorkflowDescriptions holds details about calls to the WorkflowDescriptions method.
		WorkflowDescriptions []struct {
		}
	}
	lockAnswerQuestion          sync.RWMutex
	lockBackgroundJobs          sync.RWMutex
	lockClearRevert             sync.RWMutex
	lockCompletionNotes         sync.RWMutex
	lockCreateConversation      sync.RWMutex
	lockDeleteQueueItem         sync.RWMutex
	lockListConversations       sync.RWMutex
	lockMoveToBackground        sync.RWMutex
	lockPendingQuestions        sync.RWMutex
	lockPopQueueItem            sync.RWMutex
	lockPromoteQueueItem        sync.RWMutex
	lockQueueItems              sync.RWMutex
	lockReorderQueueItems       sync.RWMutex
	lockRunTurn                 sync.RWMutex
	lockStageRevert             sync.RWMutex
	lockStartGoal               sync.RWMutex
	lockStashQueueItem          sync.RWMutex
	lockStopBackgroundJob       sync.RWMutex
	lockSubscribe               sync.RWMutex
	lockSwitchConversationAgent sync.RWMutex
	lockSyncConversation        sync.RWMutex
	lockWorkflowDescriptions    sync.RWMutex
}

// AnswerQuestion calls AnswerQuestionFunc.
func (mock *backendMock) AnswerQuestion(context1 context.Context, s string, s1 string, askUserQuestionAnswer protocol.AskUserQuestionAnswer) error {
	if mock.AnswerQuestionFunc == nil {
		panic("backendMock.AnswerQuestionFunc: method is nil but Backend.AnswerQuestion was just called")
	}
	callInfo := struct {
		Context1              context.Context
		S                     string
		S1                    string
		AskUserQuestionAnswer protocol.AskUserQuestionAnswer
	}{
		Context1:              context1,
		S:                     s,
		S1:                    s1,
		AskUserQuestionAnswer: askUserQuestionAnswer,
	}
	mock.lockAnswerQuestion.Lock()
	mock.calls.AnswerQuestion = append(mock.calls.AnswerQuestion, callInfo)
	mock.lockAnswerQuestion.Unlock()
	return mock.AnswerQuestionFunc(context1, s, s1, askUserQuestionAnswer)
}

// AnswerQuestionCalls gets all the calls that were made to AnswerQuestion.
// Check the length with:
//
//	len(mockedBackend.AnswerQuestionCalls())
func (mock *backendMock) AnswerQuestionCalls() []struct {
	Context1              context.Context
	S                     string
	S1                    string
	AskUserQuestionAnswer protocol.AskUserQuestionAnswer
} {
	var calls []struct {
		Context1              context.Context
		S                     string
		S1                    string
		AskUserQuestionAnswer protocol.AskUserQuestionAnswer
	}
	mock.lockAnswerQuestion.RLock()
	calls = mock.calls.AnswerQuestion
	mock.lockAnswerQuestion.RUnlock()
	return calls
}

// BackgroundJobs calls BackgroundJobsFunc.
func (mock *backendMock) BackgroundJobs(context1 context.Context, s string) ([]protocol.BackgroundJob, bool, error) {
	if mock.BackgroundJobsFunc == nil {
		panic("backendMock.BackgroundJobsFunc: method is nil but Backend.BackgroundJobs was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockBackgroundJobs.Lock()
	mock.calls.BackgroundJobs = append(mock.calls.BackgroundJobs, callInfo)
	mock.lockBackgroundJobs.Unlock()
	return mock.BackgroundJobsFunc(context1, s)
}

// BackgroundJobsCalls gets all the calls that were made to BackgroundJobs.
// Check the length with:
//
//	len(mockedBackend.BackgroundJobsCalls())
func (mock *backendMock) BackgroundJobsCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockBackgroundJobs.RLock()
	calls = mock.calls.BackgroundJobs
	mock.lockBackgroundJobs.RUnlock()
	return calls
}

// ClearRevert calls ClearRevertFunc.
func (mock *backendMock) ClearRevert(context1 context.Context, s string) error {
	if mock.ClearRevertFunc == nil {
		panic("backendMock.ClearRevertFunc: method is nil but Backend.ClearRevert was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockClearRevert.Lock()
	mock.calls.ClearRevert = append(mock.calls.ClearRevert, callInfo)
	mock.lockClearRevert.Unlock()
	return mock.ClearRevertFunc(context1, s)
}

// ClearRevertCalls gets all the calls that were made to ClearRevert.
// Check the length with:
//
//	len(mockedBackend.ClearRevertCalls())
func (mock *backendMock) ClearRevertCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockClearRevert.RLock()
	calls = mock.calls.ClearRevert
	mock.lockClearRevert.RUnlock()
	return calls
}

// CompletionNotes calls CompletionNotesFunc.
func (mock *backendMock) CompletionNotes(context1 context.Context, s string, strings []string) ([]protocol.BackgroundJob, error) {
	if mock.CompletionNotesFunc == nil {
		panic("backendMock.CompletionNotesFunc: method is nil but Backend.CompletionNotes was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		Strings  []string
	}{
		Context1: context1,
		S:        s,
		Strings:  strings,
	}
	mock.lockCompletionNotes.Lock()
	mock.calls.CompletionNotes = append(mock.calls.CompletionNotes, callInfo)
	mock.lockCompletionNotes.Unlock()
	return mock.CompletionNotesFunc(context1, s, strings)
}

// CompletionNotesCalls gets all the calls that were made to CompletionNotes.
// Check the length with:
//
//	len(mockedBackend.CompletionNotesCalls())
func (mock *backendMock) CompletionNotesCalls() []struct {
	Context1 context.Context
	S        string
	Strings  []string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		Strings  []string
	}
	mock.lockCompletionNotes.RLock()
	calls = mock.calls.CompletionNotes
	mock.lockCompletionNotes.RUnlock()
	return calls
}

// CreateConversation calls CreateConversationFunc.
func (mock *backendMock) CreateConversation(context1 context.Context, conversation protocol.Conversation) error {
	if mock.CreateConversationFunc == nil {
		panic("backendMock.CreateConversationFunc: method is nil but Backend.CreateConversation was just called")
	}
	callInfo := struct {
		Context1     context.Context
		Conversation protocol.Conversation
	}{
		Context1:     context1,
		Conversation: conversation,
	}
	mock.lockCreateConversation.Lock()
	mock.calls.CreateConversation = append(mock.calls.CreateConversation, callInfo)
	mock.lockCreateConversation.Unlock()
	return mock.CreateConversationFunc(context1, conversation)
}

// CreateConversationCalls gets all the calls that were made to CreateConversation.
// Check the length with:
//
//	len(mockedBackend.CreateConversationCalls())
func (mock *backendMock) CreateConversationCalls() []struct {
	Context1     context.Context
	Conversation protocol.Conversation
} {
	var calls []struct {
		Context1     context.Context
		Conversation protocol.Conversation
	}
	mock.lockCreateConversation.RLock()
	calls = mock.calls.CreateConversation
	mock.lockCreateConversation.RUnlock()
	return calls
}

// DeleteQueueItem calls DeleteQueueItemFunc.
func (mock *backendMock) DeleteQueueItem(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.DeleteQueueItemFunc == nil {
		panic("backendMock.DeleteQueueItemFunc: method is nil but Backend.DeleteQueueItem was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockDeleteQueueItem.Lock()
	mock.calls.DeleteQueueItem = append(mock.calls.DeleteQueueItem, callInfo)
	mock.lockDeleteQueueItem.Unlock()
	return mock.DeleteQueueItemFunc(context1, s, s1)
}

// DeleteQueueItemCalls gets all the calls that were made to DeleteQueueItem.
// Check the length with:
//
//	len(mockedBackend.DeleteQueueItemCalls())
func (mock *backendMock) DeleteQueueItemCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockDeleteQueueItem.RLock()
	calls = mock.calls.DeleteQueueItem
	mock.lockDeleteQueueItem.RUnlock()
	return calls
}

// ListConversations calls ListConversationsFunc.
func (mock *backendMock) ListConversations(context1 context.Context) ([]protocol.Conversation, error) {
	if mock.ListConversationsFunc == nil {
		panic("backendMock.ListConversationsFunc: method is nil but Backend.ListConversations was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockListConversations.Lock()
	mock.calls.ListConversations = append(mock.calls.ListConversations, callInfo)
	mock.lockListConversations.Unlock()
	return mock.ListConversationsFunc(context1)
}

// ListConversationsCalls gets all the calls that were made to ListConversations.
// Check the length with:
//
//	len(mockedBackend.ListConversationsCalls())
func (mock *backendMock) ListConversationsCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockListConversations.RLock()
	calls = mock.calls.ListConversations
	mock.lockListConversations.RUnlock()
	return calls
}

// MoveToBackground calls MoveToBackgroundFunc.
func (mock *backendMock) MoveToBackground(s string) (bool, error) {
	if mock.MoveToBackgroundFunc == nil {
		panic("backendMock.MoveToBackgroundFunc: method is nil but Backend.MoveToBackground was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockMoveToBackground.Lock()
	mock.calls.MoveToBackground = append(mock.calls.MoveToBackground, callInfo)
	mock.lockMoveToBackground.Unlock()
	return mock.MoveToBackgroundFunc(s)
}

// MoveToBackgroundCalls gets all the calls that were made to MoveToBackground.
// Check the length with:
//
//	len(mockedBackend.MoveToBackgroundCalls())
func (mock *backendMock) MoveToBackgroundCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockMoveToBackground.RLock()
	calls = mock.calls.MoveToBackground
	mock.lockMoveToBackground.RUnlock()
	return calls
}

// PendingQuestions calls PendingQuestionsFunc.
func (mock *backendMock) PendingQuestions(context1 context.Context, s string) ([]protocol.AskUserQuestionRequest, error) {
	if mock.PendingQuestionsFunc == nil {
		panic("backendMock.PendingQuestionsFunc: method is nil but Backend.PendingQuestions was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
	}{
		Context1: context1,
		S:        s,
	}
	mock.lockPendingQuestions.Lock()
	mock.calls.PendingQuestions = append(mock.calls.PendingQuestions, callInfo)
	mock.lockPendingQuestions.Unlock()
	return mock.PendingQuestionsFunc(context1, s)
}

// PendingQuestionsCalls gets all the calls that were made to PendingQuestions.
// Check the length with:
//
//	len(mockedBackend.PendingQuestionsCalls())
func (mock *backendMock) PendingQuestionsCalls() []struct {
	Context1 context.Context
	S        string
} {
	var calls []struct {
		Context1 context.Context
		S        string
	}
	mock.lockPendingQuestions.RLock()
	calls = mock.calls.PendingQuestions
	mock.lockPendingQuestions.RUnlock()
	return calls
}

// PopQueueItem calls PopQueueItemFunc.
func (mock *backendMock) PopQueueItem(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.PopQueueItemFunc == nil {
		panic("backendMock.PopQueueItemFunc: method is nil but Backend.PopQueueItem was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockPopQueueItem.Lock()
	mock.calls.PopQueueItem = append(mock.calls.PopQueueItem, callInfo)
	mock.lockPopQueueItem.Unlock()
	return mock.PopQueueItemFunc(context1, s, s1)
}

// PopQueueItemCalls gets all the calls that were made to PopQueueItem.
// Check the length with:
//
//	len(mockedBackend.PopQueueItemCalls())
func (mock *backendMock) PopQueueItemCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockPopQueueItem.RLock()
	calls = mock.calls.PopQueueItem
	mock.lockPopQueueItem.RUnlock()
	return calls
}

// PromoteQueueItem calls PromoteQueueItemFunc.
func (mock *backendMock) PromoteQueueItem(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.PromoteQueueItemFunc == nil {
		panic("backendMock.PromoteQueueItemFunc: method is nil but Backend.PromoteQueueItem was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockPromoteQueueItem.Lock()
	mock.calls.PromoteQueueItem = append(mock.calls.PromoteQueueItem, callInfo)
	mock.lockPromoteQueueItem.Unlock()
	return mock.PromoteQueueItemFunc(context1, s, s1)
}

// PromoteQueueItemCalls gets all the calls that were made to PromoteQueueItem.
// Check the length with:
//
//	len(mockedBackend.PromoteQueueItemCalls())
func (mock *backendMock) PromoteQueueItemCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockPromoteQueueItem.RLock()
	calls = mock.calls.PromoteQueueItem
	mock.lockPromoteQueueItem.RUnlock()
	return calls
}

// QueueItems calls QueueItemsFunc.
func (mock *backendMock) QueueItems(s string) ([]protocol.ThreadQueueItem, error) {
	if mock.QueueItemsFunc == nil {
		panic("backendMock.QueueItemsFunc: method is nil but Backend.QueueItems was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockQueueItems.Lock()
	mock.calls.QueueItems = append(mock.calls.QueueItems, callInfo)
	mock.lockQueueItems.Unlock()
	return mock.QueueItemsFunc(s)
}

// QueueItemsCalls gets all the calls that were made to QueueItems.
// Check the length with:
//
//	len(mockedBackend.QueueItemsCalls())
func (mock *backendMock) QueueItemsCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockQueueItems.RLock()
	calls = mock.calls.QueueItems
	mock.lockQueueItems.RUnlock()
	return calls
}

// ReorderQueueItems calls ReorderQueueItemsFunc.
func (mock *backendMock) ReorderQueueItems(s string, strings []string) error {
	if mock.ReorderQueueItemsFunc == nil {
		panic("backendMock.ReorderQueueItemsFunc: method is nil but Backend.ReorderQueueItems was just called")
	}
	callInfo := struct {
		S       string
		Strings []string
	}{
		S:       s,
		Strings: strings,
	}
	mock.lockReorderQueueItems.Lock()
	mock.calls.ReorderQueueItems = append(mock.calls.ReorderQueueItems, callInfo)
	mock.lockReorderQueueItems.Unlock()
	return mock.ReorderQueueItemsFunc(s, strings)
}

// ReorderQueueItemsCalls gets all the calls that were made to ReorderQueueItems.
// Check the length with:
//
//	len(mockedBackend.ReorderQueueItemsCalls())
func (mock *backendMock) ReorderQueueItemsCalls() []struct {
	S       string
	Strings []string
} {
	var calls []struct {
		S       string
		Strings []string
	}
	mock.lockReorderQueueItems.RLock()
	calls = mock.calls.ReorderQueueItems
	mock.lockReorderQueueItems.RUnlock()
	return calls
}

// RunTurn calls RunTurnFunc.
func (mock *backendMock) RunTurn(context1 context.Context, inboundMessage *protocol.InboundMessage) error {
	if mock.RunTurnFunc == nil {
		panic("backendMock.RunTurnFunc: method is nil but Backend.RunTurn was just called")
	}
	callInfo := struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
	}{
		Context1:       context1,
		InboundMessage: inboundMessage,
	}
	mock.lockRunTurn.Lock()
	mock.calls.RunTurn = append(mock.calls.RunTurn, callInfo)
	mock.lockRunTurn.Unlock()
	return mock.RunTurnFunc(context1, inboundMessage)
}

// RunTurnCalls gets all the calls that were made to RunTurn.
// Check the length with:
//
//	len(mockedBackend.RunTurnCalls())
func (mock *backendMock) RunTurnCalls() []struct {
	Context1       context.Context
	InboundMessage *protocol.InboundMessage
} {
	var calls []struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
	}
	mock.lockRunTurn.RLock()
	calls = mock.calls.RunTurn
	mock.lockRunTurn.RUnlock()
	return calls
}

// StageRevert calls StageRevertFunc.
func (mock *backendMock) StageRevert(context1 context.Context, s string, s1 string) (string, string, error) {
	if mock.StageRevertFunc == nil {
		panic("backendMock.StageRevertFunc: method is nil but Backend.StageRevert was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockStageRevert.Lock()
	mock.calls.StageRevert = append(mock.calls.StageRevert, callInfo)
	mock.lockStageRevert.Unlock()
	return mock.StageRevertFunc(context1, s, s1)
}

// StageRevertCalls gets all the calls that were made to StageRevert.
// Check the length with:
//
//	len(mockedBackend.StageRevertCalls())
func (mock *backendMock) StageRevertCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockStageRevert.RLock()
	calls = mock.calls.StageRevert
	mock.lockStageRevert.RUnlock()
	return calls
}

// StartGoal calls StartGoalFunc.
func (mock *backendMock) StartGoal(context1 context.Context, inboundMessage *protocol.InboundMessage, goalRequest protocol.GoalRequest) error {
	if mock.StartGoalFunc == nil {
		panic("backendMock.StartGoalFunc: method is nil but Backend.StartGoal was just called")
	}
	callInfo := struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
		GoalRequest    protocol.GoalRequest
	}{
		Context1:       context1,
		InboundMessage: inboundMessage,
		GoalRequest:    goalRequest,
	}
	mock.lockStartGoal.Lock()
	mock.calls.StartGoal = append(mock.calls.StartGoal, callInfo)
	mock.lockStartGoal.Unlock()
	return mock.StartGoalFunc(context1, inboundMessage, goalRequest)
}

// StartGoalCalls gets all the calls that were made to StartGoal.
// Check the length with:
//
//	len(mockedBackend.StartGoalCalls())
func (mock *backendMock) StartGoalCalls() []struct {
	Context1       context.Context
	InboundMessage *protocol.InboundMessage
	GoalRequest    protocol.GoalRequest
} {
	var calls []struct {
		Context1       context.Context
		InboundMessage *protocol.InboundMessage
		GoalRequest    protocol.GoalRequest
	}
	mock.lockStartGoal.RLock()
	calls = mock.calls.StartGoal
	mock.lockStartGoal.RUnlock()
	return calls
}

// StashQueueItem calls StashQueueItemFunc.
func (mock *backendMock) StashQueueItem(context1 context.Context, s string, threadQueueItem *protocol.ThreadQueueItem) error {
	if mock.StashQueueItemFunc == nil {
		panic("backendMock.StashQueueItemFunc: method is nil but Backend.StashQueueItem was just called")
	}
	callInfo := struct {
		Context1        context.Context
		S               string
		ThreadQueueItem *protocol.ThreadQueueItem
	}{
		Context1:        context1,
		S:               s,
		ThreadQueueItem: threadQueueItem,
	}
	mock.lockStashQueueItem.Lock()
	mock.calls.StashQueueItem = append(mock.calls.StashQueueItem, callInfo)
	mock.lockStashQueueItem.Unlock()
	return mock.StashQueueItemFunc(context1, s, threadQueueItem)
}

// StashQueueItemCalls gets all the calls that were made to StashQueueItem.
// Check the length with:
//
//	len(mockedBackend.StashQueueItemCalls())
func (mock *backendMock) StashQueueItemCalls() []struct {
	Context1        context.Context
	S               string
	ThreadQueueItem *protocol.ThreadQueueItem
} {
	var calls []struct {
		Context1        context.Context
		S               string
		ThreadQueueItem *protocol.ThreadQueueItem
	}
	mock.lockStashQueueItem.RLock()
	calls = mock.calls.StashQueueItem
	mock.lockStashQueueItem.RUnlock()
	return calls
}

// StopBackgroundJob calls StopBackgroundJobFunc.
func (mock *backendMock) StopBackgroundJob(context1 context.Context, s string, s1 string) (bool, error) {
	if mock.StopBackgroundJobFunc == nil {
		panic("backendMock.StopBackgroundJobFunc: method is nil but Backend.StopBackgroundJob was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockStopBackgroundJob.Lock()
	mock.calls.StopBackgroundJob = append(mock.calls.StopBackgroundJob, callInfo)
	mock.lockStopBackgroundJob.Unlock()
	return mock.StopBackgroundJobFunc(context1, s, s1)
}

// StopBackgroundJobCalls gets all the calls that were made to StopBackgroundJob.
// Check the length with:
//
//	len(mockedBackend.StopBackgroundJobCalls())
func (mock *backendMock) StopBackgroundJobCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockStopBackgroundJob.RLock()
	calls = mock.calls.StopBackgroundJob
	mock.lockStopBackgroundJob.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *backendMock) Subscribe(context1 context.Context) iter.Seq[protocol.Event] {
	if mock.SubscribeFunc == nil {
		panic("backendMock.SubscribeFunc: method is nil but Backend.Subscribe was just called")
	}
	callInfo := struct {
		Context1 context.Context
	}{
		Context1: context1,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(context1)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedBackend.SubscribeCalls())
func (mock *backendMock) SubscribeCalls() []struct {
	Context1 context.Context
} {
	var calls []struct {
		Context1 context.Context
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// SwitchConversationAgent calls SwitchConversationAgentFunc.
func (mock *backendMock) SwitchConversationAgent(s string, s1 string) (bool, error) {
	if mock.SwitchConversationAgentFunc == nil {
		panic("backendMock.SwitchConversationAgentFunc: method is nil but Backend.SwitchConversationAgent was just called")
	}
	callInfo := struct {
		S  string
		S1 string
	}{
		S:  s,
		S1: s1,
	}
	mock.lockSwitchConversationAgent.Lock()
	mock.calls.SwitchConversationAgent = append(mock.calls.SwitchConversationAgent, callInfo)
	mock.lockSwitchConversationAgent.Unlock()
	return mock.SwitchConversationAgentFunc(s, s1)
}

// SwitchConversationAgentCalls gets all the calls that were made to SwitchConversationAgent.
// Check the length with:
//
//	len(mockedBackend.SwitchConversationAgentCalls())
func (mock *backendMock) SwitchConversationAgentCalls() []struct {
	S  string
	S1 string
} {
	var calls []struct {
		S  string
		S1 string
	}
	mock.lockSwitchConversationAgent.RLock()
	calls = mock.calls.SwitchConversationAgent
	mock.lockSwitchConversationAgent.RUnlock()
	return calls
}

// SyncConversation calls SyncConversationFunc.
func (mock *backendMock) SyncConversation(context1 context.Context, s string, s1 string) error {
	if mock.SyncConversationFunc == nil {
		panic("backendMock.SyncConversationFunc: method is nil but Backend.SyncConversation was just called")
	}
	callInfo := struct {
		Context1 context.Context
		S        string
		S1       string
	}{
		Context1: context1,
		S:        s,
		S1:       s1,
	}
	mock.lockSyncConversation.Lock()
	mock.calls.SyncConversation = append(mock.calls.SyncConversation, callInfo)
	mock.lockSyncConversation.Unlock()
	return mock.SyncConversationFunc(context1, s, s1)
}

// SyncConversationCalls gets all the calls that were made to SyncConversation.
// Check the length with:
//
//	len(mockedBackend.SyncConversationCalls())
func (mock *backendMock) SyncConversationCalls() []struct {
	Context1 context.Context
	S        string
	S1       string
} {
	var calls []struct {
		Context1 context.Context
		S        string
		S1       string
	}
	mock.lockSyncConversation.RLock()
	calls = mock.calls.SyncConversation
	mock.lockSyncConversation.RUnlock()
	return calls
}

// WorkflowDescriptions calls WorkflowDescriptionsFunc.
func (mock *backendMock) WorkflowDescriptions() ([]protocol.WorkflowDescription, error) {
	if mock.WorkflowDescriptionsFunc == nil {
		panic("backendMock.WorkflowDescriptionsFunc: method is nil but Backend.WorkflowDescriptions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockWorkflowDescriptions.Lock()
	mock.calls.WorkflowDescriptions = append(mock.calls.WorkflowDescriptions, callInfo)
	mock.lockWorkflowDescriptions.Unlock()
	return mock.WorkflowDescriptionsFunc()
}

// WorkflowDescriptionsCalls gets all the calls that were made to WorkflowDescriptions.
// Check the length with:
//
//	len(mockedBackend.WorkflowDescriptionsCalls())
func (mock *backendMock) WorkflowDescriptionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockWorkflowDescriptions.RLock()
	calls = mock.calls.WorkflowDescriptions
	mock.lockWorkflowDescriptions.RUnlock()
	return calls
}
