// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package slackconnector

import (
	"context"
	"sync"
	"time"
)

// Ensure that channelFactsStoreMock does implement channelFactsStore.
// If this is not the case, regenerate this file with mockery.
var _ channelFactsStore = &channelFactsStoreMock{}

// channelFactsStoreMock is a mock implementation of channelFactsStore.
//
//	func TestSomethingThatUseschannelFactsStore(t *testing.T) {
//
//		// make and configure a mocked channelFactsStore
//		mockedchannelFactsStore := &channelFactsStoreMock{
//			ChannelFactFunc: func(ctx context.Context, workspaceID string, channelID string) (string, bool, error) {
//				panic("mock out the ChannelFact method")
//			},
//			RecordChannelFactFunc: func(ctx context.Context, workspaceID string, channelID string, name string, observedAt time.Time) error {
//				panic("mock out the RecordChannelFact method")
//			},
//			SlackChannelIDsFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the SlackChannelIDs method")
//			},
//		}
//
//		// use mockedchannelFactsStore in code that requires channelFactsStore
//		// and then make assertions.
//
//	}
type channelFactsStoreMock struct {
	// ChannelFactFunc mocks the ChannelFact method.
	ChannelFactFunc func(ctx context.Context, workspaceID string, channelID string) (string, bool, error)

	// RecordChannelFactFunc mocks the RecordChannelFact method.
	RecordChannelFactFunc func(ctx context.Context, workspaceID string, channelID string, name string, observedAt time.Time) error

	// SlackChannelIDsFunc mocks the SlackChannelIDs method.
	SlackChannelIDsFunc func(ctx context.Context) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChannelFact holds details about calls to the ChannelFact method.
		ChannelFact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// ChannelID is the channelID argument value.
			ChannelID string
		}
		// RecordChannelFact holds details about calls to the RecordChannelFact method.
		RecordChannelFact []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// WorkspaceID is the workspaceID argument value.
			WorkspaceID string
			// ChannelID is the channelID argument value.
			ChannelID string
			// Name is the name argument value.
			Name string
			// ObservedAt is the observedAt argument value.
			ObservedAt time.Time
		}
		// SlackChannelIDs holds details about calls to the SlackChannelIDs method.
		SlackChannelIDs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockChannelFact       sync.RWMutex
	lockRecordChannelFact sync.RWMutex
	lockSlackChannelIDs   sync.RWMutex
}

// ChannelFact calls ChannelFactFunc.
func (mock *channelFactsStoreMock) ChannelFact(ctx context.Context, workspaceID string, channelID string) (string, bool, error) {
	if mock.ChannelFactFunc == nil {
		panic("channelFactsStoreMock.ChannelFactFunc: method is nil but channelFactsStore.ChannelFact was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		ChannelID   string
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		ChannelID:   channelID,
	}
	mock.lockChannelFact.Lock()
	mock.calls.ChannelFact = append(mock.calls.ChannelFact, callInfo)
	mock.lockChannelFact.Unlock()
	return mock.ChannelFactFunc(ctx, workspaceID, channelID)
}

// ChannelFactCalls gets all the calls that were made to ChannelFact.
// Check the length with:
//
//	len(mockedchannelFactsStore.ChannelFactCalls())
func (mock *channelFactsStoreMock) ChannelFactCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	ChannelID   string
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		ChannelID   string
	}
	mock.lockChannelFact.RLock()
	calls = mock.calls.ChannelFact
	mock.lockChannelFact.RUnlock()
	return calls
}

// RecordChannelFact calls RecordChannelFactFunc.
func (mock *channelFactsStoreMock) RecordChannelFact(ctx context.Context, workspaceID string, channelID string, name string, observedAt time.Time) error {
	if mock.RecordChannelFactFunc == nil {
		panic("channelFactsStoreMock.RecordChannelFactFunc: method is nil but channelFactsStore.RecordChannelFact was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		WorkspaceID string
		ChannelID   string
		Name        string
		ObservedAt  time.Time
	}{
		Ctx:         ctx,
		WorkspaceID: workspaceID,
		ChannelID:   channelID,
		Name:        name,
		ObservedAt:  observedAt,
	}
	mock.lockRecordChannelFact.Lock()
	mock.calls.RecordChannelFact = append(mock.calls.RecordChannelFact, callInfo)
	mock.lockRecordChannelFact.Unlock()
	return mock.RecordChannelFactFunc(ctx, workspaceID, channelID, name, observedAt)
}

// RecordChannelFactCalls gets all the calls that were made to RecordChannelFact.
// Check the length with:
//
//	len(mockedchannelFactsStore.RecordChannelFactCalls())
func (mock *channelFactsStoreMock) RecordChannelFactCalls() []struct {
	Ctx         context.Context
	WorkspaceID string
	ChannelID   string
	Name        string
	ObservedAt  time.Time
} {
	var calls []struct {
		Ctx         context.Context
		WorkspaceID string
		ChannelID   string
		Name        string
		ObservedAt  time.Time
	}
	mock.lockRecordChannelFact.RLock()
	calls = mock.calls.RecordChannelFact
	mock.lockRecordChannelFact.RUnlock()
	return calls
}

// SlackChannelIDs calls SlackChannelIDsFunc.
func (mock *channelFactsStoreMock) SlackChannelIDs(ctx context.Context) ([]string, error) {
	if mock.SlackChannelIDsFunc == nil {
		panic("channelFactsStoreMock.SlackChannelIDsFunc: method is nil but channelFactsStore.SlackChannelIDs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockSlackChannelIDs.Lock()
	mock.calls.SlackChannelIDs = append(mock.calls.SlackChannelIDs, callInfo)
	mock.lockSlackChannelIDs.Unlock()
	return mock.SlackChannelIDsFunc(ctx)
}

// SlackChannelIDsCalls gets all the calls that were made to SlackChannelIDs.
// Check the length with:
//
//	len(mockedchannelFactsStore.SlackChannelIDsCalls())
func (mock *channelFactsStoreMock) SlackChannelIDsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockSlackChannelIDs.RLock()
	calls = mock.calls.SlackChannelIDs
	mock.lockSlackChannelIDs.RUnlock()
	return calls
}
