// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package slackconnector

import (
	"context"
	"sync"

	"github.com/Rocketable/platform/internal/rocketclaw/protocol"
)

// Ensure that primaryTextRouterMock does implement protocol.PrimaryTextRouter.
// If this is not the case, regenerate this file with mockery.
var _ protocol.PrimaryTextRouter = &primaryTextRouterMock{}

// primaryTextRouterMock is a mock implementation of protocol.PrimaryTextRouter.
//
//	func TestSomethingThatUsesPrimaryTextRouter(t *testing.T) {
//
//		// make and configure a mocked protocol.PrimaryTextRouter
//		mockedPrimaryTextRouter := &primaryTextRouterMock{
//			InterruptThreadFunc: func(target protocol.TextConversationTarget) (*protocol.InboundMessage, error) {
//				panic("mock out the InterruptThread method")
//			},
//			MentionThreadFunc: func(target protocol.TextConversationTarget) (bool, bool, error) {
//				panic("mock out the MentionThread method")
//			},
//			SubmitMentionFunc: func(ctx context.Context, agent string, target protocol.TextConversationTarget, inbound *protocol.InboundMessage) (bool, error) {
//				panic("mock out the SubmitMention method")
//			},
//			WebURLFunc: func(ctx context.Context, conversationID string) (string, error) {
//				panic("mock out the WebURL method")
//			},
//		}
//
//		// use mockedPrimaryTextRouter in code that requires protocol.PrimaryTextRouter
//		// and then make assertions.
//
//	}
type primaryTextRouterMock struct {
	// InterruptThreadFunc mocks the InterruptThread method.
	InterruptThreadFunc func(target protocol.TextConversationTarget) (*protocol.InboundMessage, error)

	// MentionThreadFunc mocks the MentionThread method.
	MentionThreadFunc func(target protocol.TextConversationTarget) (bool, bool, error)

	// SubmitMentionFunc mocks the SubmitMention method.
	SubmitMentionFunc func(ctx context.Context, agent string, target protocol.TextConversationTarget, inbound *protocol.InboundMessage) (bool, error)

	// WebURLFunc mocks the WebURL method.
	WebURLFunc func(ctx context.Context, conversationID string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// InterruptThread holds details about calls to the InterruptThread method.
		InterruptThread []struct {
			// Target is the target argument value.
			Target protocol.TextConversationTarget
		}
		// MentionThread holds details about calls to the MentionThread method.
		MentionThread []struct {
			// Target is the target argument value.
			Target protocol.TextConversationTarget
		}
		// SubmitMention holds details about calls to the SubmitMention method.
		SubmitMention []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Agent is the agent argument value.
			Agent string
			// Target is the target argument value.
			Target protocol.TextConversationTarget
			// Inbound is the inbound argument value.
			Inbound *protocol.InboundMessage
		}
		// WebURL holds details about calls to the WebURL method.
		WebURL []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConversationID is the conversationID argument value.
			ConversationID string
		}
	}
	lockInterruptThread sync.RWMutex
	lockMentionThread   sync.RWMutex
	lockSubmitMention   sync.RWMutex
	lockWebURL          sync.RWMutex
}

// InterruptThread calls InterruptThreadFunc.
func (mock *primaryTextRouterMock) InterruptThread(target protocol.TextConversationTarget) (*protocol.InboundMessage, error) {
	if mock.InterruptThreadFunc == nil {
		panic("primaryTextRouterMock.InterruptThreadFunc: method is nil but PrimaryTextRouter.InterruptThread was just called")
	}
	callInfo := struct {
		Target protocol.TextConversationTarget
	}{
		Target: target,
	}
	mock.lockInterruptThread.Lock()
	mock.calls.InterruptThread = append(mock.calls.InterruptThread, callInfo)
	mock.lockInterruptThread.Unlock()
	return mock.InterruptThreadFunc(target)
}

// InterruptThreadCalls gets all the calls that were made to InterruptThread.
// Check the length with:
//
//	len(mockedPrimaryTextRouter.InterruptThreadCalls())
func (mock *primaryTextRouterMock) InterruptThreadCalls() []struct {
	Target protocol.TextConversationTarget
} {
	var calls []struct {
		Target protocol.TextConversationTarget
	}
	mock.lockInterruptThread.RLock()
	calls = mock.calls.InterruptThread
	mock.lockInterruptThread.RUnlock()
	return calls
}

// MentionThread calls MentionThreadFunc.
func (mock *primaryTextRouterMock) MentionThread(target protocol.TextConversationTarget) (bool, bool, error) {
	if mock.MentionThreadFunc == nil {
		panic("primaryTextRouterMock.MentionThreadFunc: method is nil but PrimaryTextRouter.MentionThread was just called")
	}
	callInfo := struct {
		Target protocol.TextConversationTarget
	}{
		Target: target,
	}
	mock.lockMentionThread.Lock()
	mock.calls.MentionThread = append(mock.calls.MentionThread, callInfo)
	mock.lockMentionThread.Unlock()
	return mock.MentionThreadFunc(target)
}

// MentionThreadCalls gets all the calls that were made to MentionThread.
// Check the length with:
//
//	len(mockedPrimaryTextRouter.MentionThreadCalls())
func (mock *primaryTextRouterMock) MentionThreadCalls() []struct {
	Target protocol.TextConversationTarget
} {
	var calls []struct {
		Target protocol.TextConversationTarget
	}
	mock.lockMentionThread.RLock()
	calls = mock.calls.MentionThread
	mock.lockMentionThread.RUnlock()
	return calls
}

// SubmitMention calls SubmitMentionFunc.
func (mock *primaryTextRouterMock) SubmitMention(ctx context.Context, agent string, target protocol.TextConversationTarget, inbound *protocol.InboundMessage) (bool, error) {
	if mock.SubmitMentionFunc == nil {
		panic("primaryTextRouterMock.SubmitMentionFunc: method is nil but PrimaryTextRouter.SubmitMention was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Agent   string
		Target  protocol.TextConversationTarget
		Inbound *protocol.InboundMessage
	}{
		Ctx:     ctx,
		Agent:   agent,
		Target:  target,
		Inbound: inbound,
	}
	mock.lockSubmitMention.Lock()
	mock.calls.SubmitMention = append(mock.calls.SubmitMention, callInfo)
	mock.lockSubmitMention.Unlock()
	return mock.SubmitMentionFunc(ctx, agent, target, inbound)
}

// SubmitMentionCalls gets all the calls that were made to SubmitMention.
// Check the length with:
//
//	len(mockedPrimaryTextRouter.SubmitMentionCalls())
func (mock *primaryTextRouterMock) SubmitMentionCalls() []struct {
	Ctx     context.Context
	Agent   string
	Target  protocol.TextConversationTarget
	Inbound *protocol.InboundMessage
} {
	var calls []struct {
		Ctx     context.Context
		Agent   string
		Target  protocol.TextConversationTarget
		Inbound *protocol.InboundMessage
	}
	mock.lockSubmitMention.RLock()
	calls = mock.calls.SubmitMention
	mock.lockSubmitMention.RUnlock()
	return calls
}

// WebURL calls WebURLFunc.
func (mock *primaryTextRouterMock) WebURL(ctx context.Context, conversationID string) (string, error) {
	if mock.WebURLFunc == nil {
		panic("primaryTextRouterMock.WebURLFunc: method is nil but PrimaryTextRouter.WebURL was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ConversationID string
	}{
		Ctx:            ctx,
		ConversationID: conversationID,
	}
	mock.lockWebURL.Lock()
	mock.calls.WebURL = append(mock.calls.WebURL, callInfo)
	mock.lockWebURL.Unlock()
	return mock.WebURLFunc(ctx, conversationID)
}

// WebURLCalls gets all the calls that were made to WebURL.
// Check the length with:
//
//	len(mockedPrimaryTextRouter.WebURLCalls())
func (mock *primaryTextRouterMock) WebURLCalls() []struct {
	Ctx            context.Context
	ConversationID string
} {
	var calls []struct {
		Ctx            context.Context
		ConversationID string
	}
	mock.lockWebURL.RLock()
	calls = mock.calls.WebURL
	mock.lockWebURL.RUnlock()
	return calls
}
